### ISSUE TITLE
[Bug]: 因无法下载字体导致添加水印被跳过

### ISSUE THREAD

**Issue by LiarOnce** [Kuingsmile/PicList#102]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [x] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.6.2

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

按如图所示配置水印，但无论是何种路径方式均无法应用字体：
![image](https://github.com/Kuingsmile/PicList/assets/11171892/660d93d1-c5eb-44af-9b5e-29f15365e27a)

已尝试以下地址均失败：
```text
C:/Users/LiarOnce/AppData/Local/Microsoft/Windows/Fonts/SourceHanSansSC-Regular.otf
C:\\Users\\LiarOnce\\AppData\\Local\\Microsoft\\Windows\\Fonts\\SourceHanSansSC-Regular.otf
file:///C:/Users/LiarOnce/AppData/Local/Microsoft/Windows/Fonts/SourceHanSansSC-Regular.otf
```

### 相关日志 | Logs

```text
2023-10-07 00:31:04 [PicList INFO] Download ttf file. 
2023-10-07 00:31:04 [PicList ERROR] Download ttf file failed. 
2023-10-07 00:31:04 [PicList WARN] Download ttf file failed, skip add watermark. 
```

**Comment by Kuingsmile** [comment]
@LiarOnce 

`C:\Users\test\AppData\Local\Microsoft\Windows\Fonts\LXGWWenKaiScreenR.ttf`
`C:/Users/ma_sh/AppData/Local/Microsoft/Windows/Fonts/LXGWWenKaiScreenR.ttf`

上面的路径我试了下都是可以的，你看下是不是因为水印颜色没调整的原因，原来默认用的透明色 `rgba(204, 204, 204, 0.45)`，如果是白色或者浅色背景的图片会看不出来加了水印，调整下颜色试试

![image](https://github.com/Kuingsmile/PicList/assets/96409857/da81636f-1bdb-440c-ba2e-427a072fcad4)
![image](https://github.com/Kuingsmile/PicList/assets/96409857/cc95b36a-c463-4a9a-8b37-cd05c9378a3e)

**Comment by LiarOnce** [comment]
@Kuingsmile 

我将颜色设置成`rgba(0, 0, 0, 1)`了（使用白色图片测试），在日志上依然显示下载字体失败：
![image](https://github.com/Kuingsmile/PicList/assets/11171892/e929e435-d425-4473-9c06-8c390f45d2e9)

**Comment by LiarOnce** [comment]
问题解决了，现在可以正常添加水印。

原因是无论是否使用自定义字体，且无论水印类型是文字还是图片（已尝试图片类型的水印结果相同），都必须让黑体的字体文件（即`%APPDATA%\piclist\assets\simhei.ttf`）存在才能够添加成功。

**Comment by Kuingsmile** [comment]
> 问题解决了，现在可以正常添加水印。
> 
> 原因是无论是否使用自定义字体，且无论水印类型是文字还是图片（已尝试图片类型的水印结果相同），都必须让黑体的字体文件（即`%APPDATA%\piclist\assets\simhei.ttf`）存在才能够添加成功。

好的 这里应该是个bug 我调整下黑体字体文件的判断逻辑
