### ISSUE TITLE
[Feature]: Server 支持 表单上传

### ISSUE THREAD

**Issue by renmu123** [Kuingsmile/PicList#103]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.6.2

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

`/upload` 接口目前只支持上传剪贴板图片以及通过传递绝对路径来进行上传。

希望可以支持通过`formData`直接上传二进制文件，这样在某些场景下可以将应用部署在服务器，不需要在本地启动。

我觉得把sever部分单独拎出来做一个项目也是可以的，或者放在 `piclist-core` 中，如果是服务器场景可能是不需要GUI的

https://github.com/Molunerfinn/PicGo/issues/428
https://github.com/renmu123/obsidian-image-auto-upload-plugin/issues/112

**Comment by Kuingsmile** [comment]
我测试下 应该可以添加进来

**Comment by renmu123** [comment]
我觉得把sever部分单独拎出来做一个项目也是可以的，或者放在 piclist-core 中，如果是服务器场景可能是不需要GUI的~~我是win-nas不在意内存~~

**Comment by Kuingsmile** [comment]
> 我觉得把sever部分单独拎出来做一个项目也是可以的，或者放在 piclist-core 中，如果是服务器场景可能是不需要GUI的~我是win-nas不在意内存~

加core里应该是可以的

**Comment by Kuingsmile** [comment]
> 我觉得把sever部分单独拎出来做一个项目也是可以的，或者放在 piclist-core 中，如果是服务器场景可能是不需要GUI的~我是win-nas不在意内存~

https://github.com/Kuingsmile/PicList-Core/commit/4447c9d2a917cb10f725ffb89922643b76f0987d

已经在PicList-Core里添加了server部分，可以通过`picgo-server`启动，桌面版的马上也会添加formData的支持

![image](https://github.com/Kuingsmile/PicList/assets/96409857/a5c7666c-923b-4645-9ab8-03243902d3d3)

**Comment by Kuingsmile** [comment]
桌面版的`formData`支持已添加

![image](https://github.com/Kuingsmile/PicList/assets/96409857/b654d685-2b66-4368-b48b-3ba8f69430ca)
