### ISSUE TITLE
[Bug]: 关于使用watt toolkit v2.8.6打开GitHub加速时会导致上传失败

### ISSUE THREAD

**Issue by GXY-Allen** [Kuingsmile/PicList#106]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.6.4

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

![20231016221407.png](https://raw.githubusercontent.com/GXY-Allen/images/main/2023/10/20231016221407.png)
![20231016221314.png](https://raw.githubusercontent.com/GXY-Allen/images/main/2023/10/20231016221314.png)

### 相关日志 | Logs

```
2023-10-16 22:13:51 [PicList ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/GXY-Allen/images/contents/2023/10/20231016221351.png",
  "statusCode": 0,
  "message": "unable to verify the first certificate",
  "stack": "Error: unable to verify the first certificate\n    at AxiosError.from (C:\\Program Files\\PicList\\resources\\app.asar\\node_modules\\axios\\dist\\node\\axios.cjs:837:14)\n    at RedirectableRequest.handleRequestError (C:\\Program Files\\PicList\\resources\\app.asar\\node_modules\\axios\\dist\\node\\axios.cjs:3016:25)\n    at RedirectableRequest.emit (node:events:513:28)\n    at eventHandlers.<computed> (C:\\Program Files\\PicList\\resources\\app.asar\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:513:28)\n    at TLSSocket.socketErrorListener (node:_http_client:481:9)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
```

**Comment by Kuingsmile** [comment]
@GXY-Allen  你好，感谢反馈，经过下载watt toolkit测试发现是由于该软件代理Github API时，使用了自签证书，导致通过https上传失败，通过给axios代理添加`rejectUnauthorized: false`，问题已解决。

修复会在下个版本带出。

**Comment by Kuingsmile** [comment]
另外经过测试，加速模式选择为System或者PAC时，现版本PicList也可以正常上传
![image](https://github.com/Kuingsmile/PicList/assets/96409857/1e413415-1a0f-48bc-af3c-ed2e215bb062)
