### ISSUE TITLE
[Bug]: 上传失败 403

### ISSUE THREAD

**Issue by mobilestack** [Kuingsmile/PicList#107]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.6.4

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

使用 smms.app 存储，上传图片，就会失败。

Mac 是最新的 14.0 Sonoma 系统。

smms的 apitoken 没问题，之前是可以上传的，没有动过。

直接在 smms 网站上传，也是成功的

遇到 403 的错误，有可能是哪些问题呢？

### 相关日志 | Logs

<img width="650" alt="image" src="https://github.com/Kuingsmile/PicList/assets/5794691/6a96fe68-0a1a-4a5e-b15e-f22309e74817">

返回的内容有点长，直接返回了一个网页数据，里面的部分内容

<img width="1383" alt="image" src="https://github.com/Kuingsmile/PicList/assets/5794691/5db1ba4e-8802-48a6-b9b6-977916d79026">

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/96409857/eaabe6bd-2675-45fe-9302-e149b0ea0a98)
这一行有点奇怪，试下重新保存或者新建一个smms的配置文件再上传看看 ，我自己这边没有能复现出你这个错误，这边能排查到的错误如下，但都没有和你一样的
如果token填错是
![image](https://github.com/Kuingsmile/PicList/assets/96409857/ad1d9457-f6bb-4a9b-acf7-20ca34699362)
不填token是
![image](https://github.com/Kuingsmile/PicList/assets/96409857/f4aa11da-4953-45f0-954d-8bff001fc222)
一次性上传太多图片是
![image](https://github.com/Kuingsmile/PicList/assets/96409857/71cff091-a6f3-4335-8a34-3349588d9901)

**Comment by mobilestack** [comment]
新建了配置再上传，也还是不行。

在 smms 里面更新了 token，也还是不行。

奇怪的是在云端相册的管理位置，也拉不下来图片

打开和关闭 vpn，也都不行。奇怪了。

<img width="1200" alt="Snipaste_2023-10-17_19-08-00" src="https://github.com/Kuingsmile/PicList/assets/5794691/5676a227-0920-40f3-baac-0ab324868239">

**Comment by Kuingsmile** [comment]
> 新建了配置再上传，也还是不行。
> 
> 在 smms 里面更新了 token，也还是不行。
> 
> 奇怪的是在云端相册的管理位置，也拉不下来图片
> 
> 打开和关闭 vpn，也都不行。奇怪了。
> 
> <img alt="Snipaste_2023-10-17_19-08-00" width="1200" src="https://user-images.githubusercontent.com/5794691/275812723-5676a227-0920-40f3-baac-0ab324868239.png">

看看和piclist.log同目录下的manage.log里的内容有什么报错么  目录应该是`~/Library/Application Support/piclist/data.json`

**Comment by Kuingsmile** [comment]
> 新建了配置再上传，也还是不行。
> 
> 在 smms 里面更新了 token，也还是不行。
> 
> 奇怪的是在云端相册的管理位置，也拉不下来图片
> 
> 打开和关闭 vpn，也都不行。奇怪了。
> 
> <img alt="Snipaste_2023-10-17_19-08-00" width="1200" src="https://user-images.githubusercontent.com/5794691/275812723-5676a227-0920-40f3-baac-0ab324868239.png">

看下`~/Library/Application Support/piclist/manage.log`文件里有什么报错信息么

**Comment by mobilestack** [comment]
<img width="1148" alt="image" src="https://github.com/Kuingsmile/PicList/assets/5794691/a695d364-da11-43fb-bec2-6c7426f0b65d">

最后一条的日志是这样的

**Comment by Kuingsmile** [comment]
这个日志也看不出啥。。。我去虚拟机里装了个macOS试了下也没问题。。诡异

![image](https://github.com/Kuingsmile/PicList/assets/96409857/7ed227c2-a00a-4585-987c-4251d405ae36)

**Comment by mobilestack** [comment]
非常感谢了！
那回头看有人是否也报同样的错误吧，我也回头再试下彻底删除后重新装一遍再试试。
