### ISSUE TITLE
[Feature]: 转换格式选择

### ISSUE THREAD

**Issue by cli-r** [Kuingsmile/PicList#109]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.6.2

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

我上传到图床的图片是webp格式，如果添加的图片是相同的webp格式依然会被转码。
希望能添加若格式相同则图片不被转码的功能。
谢谢。

**Comment by Kuingsmile** [comment]
已添加
