### ISSUE TITLE
[Feature]: 希望可以将 `~/Download/piclistTemp` 换成 `/tmp/piclistTemp`

### ISSUE THREAD

**Issue by Mrered** [Kuingsmile/PicList#112]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.6.6

### 系统信息 | System Information

Mac(arm64)

### 功能请求 | Feature request

如题，希望可以将 `~/Download/piclistTemp` 换成 `/tmp/piclistTemp`

**Comment by Kuingsmile** [comment]
添加了新的设置项来指定缓存文件夹目录

**Comment by Mrered** [comment]
`/tmp` 目录是 macOS 默认缓存位置，建议将软件缓存放到该目录下
