### ISSUE TITLE
[Feature]: 支持更换电脑后相册也能显示数据

### ISSUE THREAD

**Issue by Devinaille** [Kuingsmile/PicList#114]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.6.7

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

换了电脑以后，相册里全是空的，希望能将信息也同步上传到图床

**Comment by Kuingsmile** [comment]
可以手动复制`%APPDATA%\piclist\`目录下的 piclist.db和piclist.db.bak文件，然后替换掉新电脑同名文件。
