### ISSUE TITLE
[Feature]: 手动调整水印边距

### ISSUE THREAD

**Issue by wanyunr** [Kuingsmile/PicList#115]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.6.7

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

可以手动调整水印边距 🙏
![image](https://github.com/Kuingsmile/PicList/assets/105478325/4a3c4249-d399-424d-922a-43b5e1a41e4b)
---
![image](https://github.com/Kuingsmile/PicList/assets/105478325/64b4d13d-b239-4fa0-bd0f-b40545b1c30c)
默认的水印位置有点太靠边，很容易被遮挡

**Comment by Kuingsmile** [comment]
我测试下

**Comment by Kuingsmile** [comment]
使用的sharp库暂时没有设置边距的选项 会保持跟踪 但暂时不会增加该功能
