### ISSUE TITLE
[Feature]: 请问这个问题是什么情况，cpu占了一大半

### ISSUE THREAD

**Issue by ydh1cnn6** [Kuingsmile/PicList#117]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.6.7

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

长时间cpu占用60左右，这是正常现象吗？
![image](https://github.com/Kuingsmile/PicList/assets/64244993/4a54cf17-d494-4dbf-b11f-f6dcec8bb932)
电脑配置一般，但应该没那么离谱吧
![image](https://github.com/Kuingsmile/PicList/assets/64244993/a1c4b6ee-c981-4b71-a38e-e48fe5ded375)

**Comment by Kuingsmile** [comment]
有点离谱 我CPU比你的还差 也没这么高。。
![image](https://github.com/Kuingsmile/PicList/assets/96409857/8ee6e4b5-9b46-46c4-8d35-4b14ca8069c9)
![image](https://github.com/Kuingsmile/PicList/assets/96409857/0d0d20bb-ddc0-483b-8b81-e2f183cc1f66)

开控制台，录制下性能报告看看是什么操作或者页面的时候CPU占用有问题
![image](https://github.com/Kuingsmile/PicList/assets/96409857/d032705f-b867-4555-8e6b-c824df032f64)

**Comment by ydh1cnn6** [comment]
在控制台不太会看，Performance monitor 看起来是占用 cpu 很少，基本是 0.1。
![image.png](https://raw.githubusercontent.com/ydh1cnn6/pic/master/202312051010919.png)
但是任务管理器一直是占用 60 左右
![image.png](https://raw.githubusercontent.com/ydh1cnn6/pic/master/202312051013925.png)

**Comment by ydh1cnn6** [comment]
重启电脑后问题解决，麻烦作者了。不理解为什么，可能是新安装导致或者电脑的统计的问题吧
![image](https://github.com/Kuingsmile/PicList/assets/64244993/6530ade8-dc8c-4bfb-8569-c9db3bf63184)

**Comment by Kuingsmile** [comment]
修复了一个可能的原因
