### ISSUE TITLE
[Feature]: 增加docker部署server端

### ISSUE THREAD

**Issue by somnifex** [Kuingsmile/PicList#118]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

latest

### 系统信息 | System Information

All

### 功能请求 | Feature request

封装docker便于部署，暴漏server端口，持久化config文件

**Comment by Kuingsmile** [comment]
这里指的是docker部署piclist-core吧

**Comment by somnifex** [comment]
> 这里指的是docker部署piclist-core吧

是的，封装一个piclist-core容器

**Comment by Kuingsmile** [comment]
> > 这里指的是docker部署piclist-core吧
> 
> 是的，封装一个piclist-core容器

可 我测试测试 后续的更新会在piclist-core的仓库内

**Comment by somnifex** [comment]
> > > 这里指的是docker部署piclist-core吧
> > 
> > 
> > 是的，封装一个piclist-core容器
> 
> 可 我测试测试 后续的更新会在piclist-core的仓库内

我对Dockerfile不是很熟，可能大概这样:
```bash
FROM alpine
# 安装 Node.js 和 npm
RUN apk add --no-cache nodejs npm
# 安装 sharp 依赖
RUN npm install sharp
RUN npm install piclist -g
# 暴露端口  
EXPOSE 36677
# 数据卷,用于挂载配置
VOLUME /config 
# 启动命令  
CMD ["picgo-server", "-c", "/config/config.json"]  
```

**Comment by Kuingsmile** [comment]
added https://github.com/Kuingsmile/PicList/commit/2de1a1f0f67e5acdb9d1469388f81b9f46d3dcc2
