### ISSUE TITLE
缩小后显示不正常[Bug]: 

### ISSUE THREAD

**Issue by zzkuner** [Kuingsmile/PicList#12]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.2.2

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

![image](https://user-images.githubusercontent.com/57533394/221185927-24d68151-2ed0-4189-83c1-4e5e285da047.png)

**Comment by Kuingsmile** [comment]
> ### 前置阅读 | Pre-reading
> * [x]  [文档/Doc](https://picgo.github.io/PicGo-Doc/)
> * [x]  [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
> * [x]  [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)
> 
> ### PicList的版本 | PicList Version
> 1.2.2
> 
> ### 系统信息 | System Information
> Windows
> 
> ### 问题重现 | Bug reproduce
> ![image](https://user-images.githubusercontent.com/57533394/221185927-24d68151-2ed0-4189-83c1-4e5e285da047.png)
> 
> ### 相关日志 | Logs
> _No response_

已了解，目前为了保证左边菜单文字显示完全，固定了左边的宽度，所以右边的界面当宽度太小时会侵占过去，不过这个界面的方块确实有点大了，我下个版本把这里的布局还有通用设置的布局改一改，尽量优化下显示效果。

不过为了保证显示完全，推荐不要缩小的太窄使用~~

**Comment by zzkuner** [comment]
好的，谢谢，主要是习惯了picgo的大小，就想弄小点

**Comment by Kuingsmile** [comment]
> 好的，谢谢，主要是习惯了picgo的大小，就想弄小点

嗯嗯 picgo的窗口大小是固定不能调整的，所以源码里很多的宽度是写死的，我在改的时候很多还木有完全修改为响应式布局，后面会逐步优化~

感谢使用，欢迎提建议和意见~
