### ISSUE TITLE
[Feature]: 上传成功自动复制“自定义链接”

### ISSUE THREAD

**Issue by raylzhang** [Kuingsmile/PicList#120]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.6.8

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

Question: 设置了自定义链接，并开启“上传成功后自动复制URL”，请问如何才能实现上传成功后自动复制我设置的“自定义链接”呢？现在依然复制的是URL，手动在相册中点复制可以成功复制成自定义链接

### 相关日志 | Logs

Question: 设置了自定义链接，并开启“上传成功后自动复制URL”，请问如何才能实现上传成功后自动复制我设置的“自定义链接”呢？现在依然复制的是URL，手动在相册中点复制可以成功复制成自定义链接

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/96409857/65b16f2a-7a1f-4f9a-ba9d-70a9dab01130)
上传前这里选择Custom
