### ISSUE TITLE
[Bug]: 转换格式webp比png的还要大

### ISSUE THREAD

**Issue by jiajiala** [Kuingsmile/PicList#121]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.6.8

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

开启了图片转换，但是webp的图比png格式还要大
webp不是应该比png小么

### 相关日志 | Logs

……

**Comment by Kuingsmile** [comment]
与图片相关 并不一定webp就比png小
