### ISSUE TITLE
[Bug]: 管理界面对 GitHub 文件重命名失败

### ISSUE THREAD

**Issue by brickloo** [Kuingsmile/PicList#122]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.6.8

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

在管理页面尝试重命名时失败，但是测试上传删除操作都是正常的，应该可以排除网络问题
![image](https://github.com/Kuingsmile/PicList/assets/101409360/8df0406e-2958-4dc3-adb2-d4a86575b40b)
![image](https://github.com/Kuingsmile/PicList/assets/101409360/bb782ffb-dadb-478f-9ad1-11abf74f188b)
顺便，管理界面通过正则替换实现重命名感觉还是麻烦了点，希望有空可以考虑一下单文件的重命名功能（？）

### 相关日志 | Logs

2023-12-25 16:24:13 [PicList INFO] [PicList Server] is listening at 36677 of 0.0.0.0 
2023-12-25 16:24:13 [PicList INFO] File server is running, http://localhost:36699 
（就只有这么多了，看起来没有有用的信息）

**Comment by Kuingsmile** [comment]
manage界面的log在`manage.log`文件里哈，和piclist.log文件在相同目录下，麻烦看下有记录么，或者同时开下控制台看一下报错信息

**Comment by brickloo** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/101409360/b859ff9c-8bd5-4802-ade2-1c1949436f8f)
因为 piclist.log 是像上图直接点击打开的，所以找到它的路径有点困难……或许可以考虑优化一下这一点？最后发现微软记事本对 piclist.log 进行另存为操作能自动定位到文件的位置，在 C:\Users\<username>\AppData\Roaming\piclist 里面
但是我好像并没有看到里面有 manage.log 文件（
![image](https://github.com/Kuingsmile/PicList/assets/101409360/33152c1f-53f6-43be-bda1-ecff1c0fb3d5)
搜索 log 也只有这些文件
![image](https://github.com/Kuingsmile/PicList/assets/101409360/ccaa9930-a726-4935-86aa-e29f2f11899b)
控制台我也不太懂应该怎么开orz

**Comment by Kuingsmile** [comment]
> 点击打开的，所以找到它的路

manage.log的打开方式我优化一下 我先自己测试下github改名这个

**Comment by Kuingsmile** [comment]
确认了下目前Github的管理部分不支持重命名操作，因为使用restful API的话没有办法单条请求完成，需要组合操作比较复杂，而且需要产生最少两条commit记录。 但也做了些优化，比如上面提到的manage.log的快速打开按钮，以及现在如果对应图床不支持重命名操作，不会显示重命名按钮，避免误解。

**Comment by brickloo** [comment]
明白了，辛苦了ＯＫ(ゝω・´★)
