### ISSUE TITLE
[Bug]: svg格式的图片开启“是否移除EXIF信息”选项上传后，文件受损无法正常显示

### ISSUE THREAD

**Issue by FunnyCavy** [Kuingsmile/PicList#123]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.6.8

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

若开启 `是否移除EXIF信息` 选项，将SVG格式的图片上传后，文件受损，下载后使用编辑器打开变成了乱码。

关闭 `是否移除EXIF信息` 选项后恢复正常。

**Comment by Kuingsmile** [comment]
我测试下
