### ISSUE TITLE
[Feature]: 希望可自定义并细化格式转换的规则

### ISSUE THREAD

**Issue by FunnyCavy** [Kuingsmile/PicList#124]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.6.8

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

现在的格式转换只能选择一种格式，希望可以让用户自己配置规则，根据上传的原格式自动选择转换后的格式。

如：
- .png -> .webp
- .jpg -> .webp
- .gif -> 不变
- .svg -> 不变

**Comment by Kuingsmile** [comment]
Good idea! 年底各种工作有点忙，会在有时间时尽快实现

**Comment by Kuingsmile** [comment]
已实现

**Comment by FunnyCavy** [comment]
> 已实现

@Kuingsmile 现在是如何配置 .svg -> 不变 这样的需求的？配置 `{"svg": "svg"}` 后依旧有问题，上传后的文件打开查看变乱码了，配置 `{"svg": null}` 后再次打开设置面板会显示 `[object Object]`

**Comment by Kuingsmile** [comment]
> > 已实现
> 
> @Kuingsmile 现在是如何配置 .svg -> 不变 这样的需求的？配置 `{"svg": "svg"}` 后依旧有问题，上传后的文件打开查看变乱码了，配置 `{"svg": null}` 后再次打开设置面板会显示 `[object Object]`

svg比较特殊，过了处理流程就会乱码，后面我单独给排除出处理过程，object显示这个我修复下
