### ISSUE TITLE
[Bug]: 升级的时候提示，Piclist无法关闭

### ISSUE THREAD

**Issue by jixintangen** [Kuingsmile/PicList#125]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.6.8

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

![1703726548914](https://github.com/Kuingsmile/PicList/assets/54758278/f2ab2166-76ae-4f11-b74a-f945788cb4f9)
提示有新版版升级，点击之后，出现了这个问题，重启电脑后，直接下载安装包安装，也会提示这个

**Comment by Kuingsmile** [comment]
关掉PicList的开机启动，然后任务管理器里关掉所有piclist进程，或者重启电脑再试下

**Comment by jixintangen** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/54758278/5805967b-0590-44da-af1d-a347a4eb04de)
试过了，不行，卸载重装的时候发现了，这个错误，估计是杀毒软件误删了什么文件，破坏了安装文件的完整性。目前重装正常了，排除bug问题。
