### ISSUE TITLE
[Feature]: 建议侧边栏的手册按钮直接唤醒电脑默认浏览器

### ISSUE THREAD

**Issue by wanyunr** [Kuingsmile/PicList#128]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.6.8

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

1. 建议侧边栏的手册按钮直接唤醒电脑默认浏览器，现在那个有点问题(跳到Github还要登录，没法Star了😲)，还看不到链接栏
![image](https://github.com/Kuingsmile/PicList/assets/105478325/d6edc703-d76a-44ab-98a6-81cab119f0fb)

2. 更新弹窗可以复制链接手动下载（网络问题，后台不知道要下到什么时候）
感谢🙏

**Comment by Kuingsmile** [comment]
> ### 前置阅读 | Pre-reading
> * [x]  [文档/Doc](https://piclist.cn/)
> * [x]  [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
> * [x]  [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)
> 
> ### PicList的版本 | PicList Version
> v2.6.8
> 
> ### 系统信息 | System Information
> Windows
> 
> ### 功能请求 | Feature request
> 1. 建议侧边栏的手册按钮直接唤醒电脑默认浏览器，现在那个有点问题(跳到Github还要登录，没法Star了😲)，还看不到链接栏
>    ![image](https://private-user-images.githubusercontent.com/105478325/293461373-d6edc703-d76a-44ab-98a6-81cab119f0fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwNzkzNjMsIm5iZiI6MTcwNDA3OTA2MywicGF0aCI6Ii8xMDU0NzgzMjUvMjkzNDYxMzczLWQ2ZWRjNzAzLWQ3NmEtNDRhYi05OGE2LTgxY2FiMTE5ZjBmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMVQwMzE3NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjIxOTBlMTU1YTlkMzhiMjk1NTUxODUzZWZmYzAwZmI3NGViY2I3NDJmMWM5MTc4N2IxMjE4ODVlY2QzNzY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2g6G7wav8PgqW5FqWuWtQ2xXAYAJ7nGAXS1p5LMgmMU)
> 2. 更新弹窗可以复制链接手动下载（网络问题，后台不知道要下到什么时候）
>    感谢🙏

1. 会提供一个选项，是内置浏览还是浏览器打开，第一次点击询问，同时可以后续保持
2. 会添加选项，复制新版本发布页的链接到剪贴板供手动下载使用

**Comment by Kuingsmile** [comment]
第一项已添加 https://github.com/Kuingsmile/PicList/commit/e4f957d67dab368d3a9fea621c244d5131e2d52c

**Comment by Kuingsmile** [comment]
已添加完毕
