### ISSUE TITLE
[Bug]: 各类重命名规则逻辑混乱与冲突

### ISSUE THREAD

**Issue by FunnyCavy** [Kuingsmile/PicList#130]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.7.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

现在重命名的设置项有：
- 上传前重命名
- 时间戳重命名
- 高级重命名

但是目前的逻辑较为混乱，表现如下：
- 关闭`上传前重命名`后，`时间戳重命名`和`高级重命名`的设置依然生效
- 打开`上传前重命名` `时间戳重命名`，弹出文件重命名窗口时选择取消，文件**保留**原名
- 打开`上传前重命名` `高级重命名`，弹出文件重命名窗口时选择取消，文件**不保留**原名，为高级重命名后的名称

希望将重命名的配置抽取为一个页面，比如分为重命名开关和重命名规则，规则包含手动、根据时间戳、高级重命名的设置，或是其他形式，这样逻辑比较统一

**Comment by Kuingsmile** [comment]
上传前重命名准确度说是手动重命名，命名上有误导性，会修改一下，另外这里的逻辑后面我考虑怎么优化下
