### ISSUE TITLE
[Feature]: webdav添加后缀的功能

### ISSUE THREAD

**Issue by ma3252788** [Kuingsmile/PicList#131]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.7.0

### 系统信息 | System Information

Mac(arm64)

### 功能请求 | Feature request

webdav貌似没有增加自定义后缀的功能，大佬可以增加一下吗？
由于我这里无法直接传到又拍云，所以采用alist挂载又拍云， 然后piclist用webdav挂载alist来间接上传到又拍云。
其他都很好用，就是webdav差了一个增加自定义后缀的功能，一人血书求增加！
谢谢谢谢。

**Comment by Kuingsmile** [comment]
可以

**Comment by ma3252788** [comment]
感谢大佬！
