### ISSUE TITLE
[Feature]: 如何使用Cloudflare R2作为图床？

### ISSUE THREAD

**Issue by toyo2333** [Kuingsmile/PicList#132]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

最新

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

如何支持S3的API呢? 现有图床里没找到

**Comment by Kuingsmile** [comment]
安装插件https://github.com/wayjam/picgo-plugin-s3
