### ISSUE TITLE
[Feature]: 关于 docker 版本的 changelog

### ISSUE THREAD

**Issue by lvbibir** [Kuingsmile/PicList#133]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v1.7.0 (docker image tag)

### 系统信息 | System Information

Linux

### 功能请求 | Feature request

查阅了 piclist 和 piclist-core 的仓库, 以及 https://piclist.cn 和 dockerhub 均未找到 docker 版本的更新说明, 似乎也不跟着 piclist 或者 piclist-core 的版本走

目前部署的是 `1.7.0` 版本的, 体验很好, 但是偶尔还是想更新一下体验新功能的, 没有 changelog 不太敢随便更新

**Comment by Kuingsmile** [comment]
跟着piclist-core的更新走的，后面我在core的release里加下更新说明

**Comment by Kuingsmile** [comment]
https://github.com/Kuingsmile/PicList-Core/releases

**Comment by lvbibir** [comment]
感谢，昨天看的时候 docker tag 更新到 1.7.x 了，但是 piclist-core 的版本还是 1.3.0

**Comment by Kuingsmile** [comment]
> 感谢，昨天看的时候 docker tag 更新到 1.7.x 了，但是 piclist-core 的版本还是 1.3.0

之前一直没去同步写core的release文档 我以为没人看来着
