### ISSUE TITLE
[Bug]: 2.70,2.68版本无法安装插件 s3

### ISSUE THREAD

**Issue by yuanyuanyuan** [Kuingsmile/PicList#134]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.70,2.68

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

![image](https://github.com/Kuingsmile/PicList/assets/5524061/d9cda3b9-7ef9-46b3-a1b1-6416d94988dd)
一直显示安装中

手动离线安装也不行

**Comment by Kuingsmile** [comment]
https://github.com/wayjam/picgo-plugin-s3/issues/39  好像picgo的新版也安不上 考虑到s3的通用性，下个版本会把s3加到内置图床里

**Comment by yuanyuanyuan** [comment]
我用 picgo  2.3 版本反而装得上，这个兼容有点神奇。

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/96409857/5c4ba40d-2f67-48b6-9ea7-ecaee4a7c53f)
我刚才卸载了s3插件，又重新安装是ok的。 看下log文件你安装的时候的报错是啥。
另外我的node版本是18.16.0，还有修改下插件安装镜像到淘宝源试试？设置路径为`设置-高级设置-设置代理和镜像地址-插件安装镜像`

**Comment by yuanyuanyuan** [comment]
我重新测试了，还是不行，等待到一定时间，就超时自动关闭 piclist 了

t 子是换过的

**Comment by Kuingsmile** [comment]
已在最新提交中添加，下一版本中带出
