### ISSUE TITLE
[Bug]: 管理功能的问题

### ISSUE THREAD

**Issue by toyo2333** [Kuingsmile/PicList#135]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

最新

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

我管理功能打开s3（Cloudflare R2）的桶，里面列出的图片，但点了后都是x，发现软件拼的url是错的，是http://桶名.xxxx.r2.cloudflarestorage.com。

我没有启用自定义域名，而是用的R2.dev 子域

找了半天不知道在哪里改最后发现是左上角有一个框里R2.dev 填进去就好了

。。。虽然说最后搞定了，但也花了半个小时配置了2编。

可能这不是bug，但几乎将我劝退了。。

**Comment by Kuingsmile** [comment]
> ### 前置阅读 | Pre-reading
> * [x]  [文档/Doc](https://piclist.cn/)
> * [x]  [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
> * [x]  [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)
> 
> ### PicList的版本 | PicList Version
> 最新
> 
> ### 系统信息 | System Information
> Windows
> 
> ### 问题重现 | Bug reproduce
> 我管理功能打开s3（Cloudflare R2）的桶，里面列出的图片，但点了后都是x，发现软件拼的url是错的，是[http://桶名.xxxx.r2.cloudflarestorage.com。](http://%E6%A1%B6%E5%90%8D.xxxx.r2.cloudflarestorage.com%E3%80%82)
> 
> 我没有启用自定义域名，而是用的R2.dev 子域
> 
> 找了半天不知道在哪里改最后发现是左上角有一个框里R2.dev 填进去就好了
> 
> 。。。虽然说最后搞定了，但也花了半个小时配置了2编。
> 
> 可能这不是bug，但几乎将我劝退了。。
> 
> ### 相关日志 | Logs
> _No response_

后面会完善下手册对应部分的说明
