### ISSUE TITLE
[Bug]: 关于相册功能的困惑

### ISSUE THREAD

**Issue by toyo2333** [Kuingsmile/PicList#136]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

最新

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

今天遇到个问题。我在开启管理功能之前，一直使用相册来管理R2图床的（我一直是勾选那个删除云端的开关的，打开的）

开启管理功能后，看到我的R2图床上有92个文件（在管理看到的），然后相册里有104个文件（相册没有计数功能我笨办法数的），最后发现几个在相册的图片有重复的。这里首先有个疑问，为啥会出现重复？

这时候我从相册点删除（选中了那个删除云端），结果相册重复的是删掉了了，清理完成后相册是92个了对上了，但是云端上也没了。。。管理里看只有80个，那12个重复的源文件被删了。 导致我的Obsdian笔记图裂了。。。。

这里就是第二个困惑了，这个相册和管理我就有点晕了。我该不该在相册里开启云端呢？目前应该怎么管理图床是最合适的做法呢？

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/96409857/5e00140d-870d-44eb-9e87-d1959b15e978)
相册顶部栏有计数的

**Comment by Kuingsmile** [comment]
@toyo2333  相册和管理的逻辑如下：
1. 相册为本地数据库，记录本机所有的上传历史，当从相册删除时，如果开启了`云端删除`，那么会同时删掉本地记录和远程文件。
2. 管理为云存储浏览和管理，看到的文件是当前云端的最新状态，删除会直接导致云端文件消失。

所以如果你看到了相册文件数目大于管理中看到的文件数，大概率可能是之前在obsidian上传了文件，然后只在其他地方移除了云端文件，没有移除相册的本地上传记录。

另外使用obsidan和r2做图床，我目前也是这个配置。

我的使用方案如下，供参考：
1. 相册保持云端删除开启，但不会主动从相册删除文件。
2. 在obsidan的`image-auto-upload-plugin`如下配置：
![image](https://github.com/Kuingsmile/PicList/assets/96409857/1baf18ec-d400-4739-8ddf-f53ff487f36f)
分别设置上传接口和删除接口
3. 在obsidan中进行上传和删除操作，如果上传错了图片或者图片不再需要，先选中完整链接，然后右键点击，在弹出菜单选择`使用PicList`删除，这时因为开了相册的云端删除，所以会同时移除本地记录和远程文件，保证了记录的一致性
![image](https://github.com/Kuingsmile/PicList/assets/96409857/b94c3fc0-2b94-4531-91e7-dc91e5efeed0)

**Comment by toyo2333** [comment]
谢谢。我也是这么设置了的。但我的OB里右键图片链接，没有你那个“使用PicList删除”。 这个是需要安装额外插件还是需要开关哪一项配置呢？

**Comment by Kuingsmile** [comment]
> 谢谢。我也是这么设置了的。但我的OB里右键图片链接，没有你那个“使用PicList删除”。 这个是需要安装额外插件还是需要开关哪一项配置呢？

不需要额外设置，选中完整的markdown格式图片链接（一般是`![xxx](xxx)`）之后右键，然后会有这个选项

**Comment by toyo2333** [comment]
好的。我再找找原因。

再请教一个问题。关于笔记图片的压缩

我的使用场景是：windows- 我用snipaste截图，然后在obsidian里粘贴，uploder插件就直接调用piclist上传了。

我看piclist现在已经支持了图片压缩和格式转换。这一块我该怎么设置比较好呢？

感谢回复

**Comment by Kuingsmile** [comment]
> 好的。我再找找原因。
> 
> 再请教一个问题。关于笔记图片的压缩
> 
> 我的使用场景是：windows- 我用snipaste截图，然后在obsidian里粘贴，uploder插件就直接调用piclist上传了。
> 
> 我看piclist现在已经支持了图片压缩和格式转换。这一块我该怎么设置比较好呢？
> 
> 感谢回复

我也是用的snipaste，自带的压缩和格式转换发生在上传前处理过程中，需要根据你自己的需求，我一般会转换为webp格式

**Comment by toyo2333** [comment]
> > 好的。我再找找原因。
> > 再请教一个问题。关于笔记图片的压缩
> > 我的使用场景是：windows- 我用snipaste截图，然后在obsidian里粘贴，uploder插件就直接调用piclist上传了。
> > 我看piclist现在已经支持了图片压缩和格式转换。这一块我该怎么设置比较好呢？
> > 感谢回复
> 
> 我也是用的snipaste，自带的压缩和格式转换发生在上传前处理过程中，需要根据你自己的需求，我一般会转换为webp格式

谢谢。我都不知道有webp，拉到最下面才看到。

另外，请问，你的JPG压缩支持MozJPEG格式么？https://squoosh.app/ 提供了两种，默认用的就是这个

**Comment by Kuingsmile** [comment]
> > > 好的。我再找找原因。
> > > 再请教一个问题。关于笔记图片的压缩
> > > 我的使用场景是：windows- 我用snipaste截图，然后在obsidian里粘贴，uploder插件就直接调用piclist上传了。
> > > 我看piclist现在已经支持了图片压缩和格式转换。这一块我该怎么设置比较好呢？
> > > 感谢回复
> > 
> > 
> > 我也是用的snipaste，自带的压缩和格式转换发生在上传前处理过程中，需要根据你自己的需求，我一般会转换为webp格式
> 
> 谢谢。我都不知道有webp，拉到最下面才看到。
> 
> 另外，请问，你的JPG压缩支持MozJPEG格式么？https://squoosh.app/ 提供了两种，默认用的就是这个

可以支持，我会修改下默认启用mozJPEG

**Comment by Kuingsmile** [comment]
https://github.com/Kuingsmile/PicList/commit/98abeaa35c76e3c37e890ca854cb957559b5ddd5

**Comment by toyo2333** [comment]
> [98abeaa](https://github.com/Kuingsmile/PicList/commit/98abeaa35c76e3c37e890ca854cb957559b5ddd5)

对了，请问，你转换功能里，jpeg和jpg有什么区别？这两种现在默认都是mozJPEG么？

**Comment by Kuingsmile** [comment]
没有本质区别 都是mozJPEG
