### ISSUE TITLE
[Bug]: 关于R2管理功能Token权限的问题

### ISSUE THREAD

**Issue by toyo2333** [Kuingsmile/PicList#137]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

最新

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

请问下是不是CF R2的管理功能必须要用的令牌权限的最高级别那个？R2的令牌权限由4个

- 管理员读和写: 允许创建、列出和删除存储桶，编辑存储桶配置，以及列出、写入和读取对象
- 管理员只读: 允许列出存储桶和查看存储桶配置，以及列出和读取对象。
- 对象读和写: 允许读取、写入和列出特定存储桶中的对象。
- 对象只读: 允许读取和列出特定存储桶中的对象。

我R2上有2个桶，一个是做图床用的，一个是做笔记同步用的。用第三个level那个权限都正常，但如果要进入管理，就得是第一个管理员读和写，否则进入管理里是什么都看不到的

我在软件界面上也没有看到创建桶、设置桶配置等功能，为什么要这么高的权限呢?

盼望解答。

我问这个问题是因为，我用于笔记同步的那个桶是没有对外开放访问的。这意味着，我通过piclist管理进去后
1. 顶部那个URL我无论填什么都不对，我没有自定义域名，也没有启用R2.dev子域。
2. 该桶里面的Markdown文件也是打不开的 
管理它也没有意译。

**Comment by Kuingsmile** [comment]
你没有设置自定义域名不代表其它用户没有这个需求，需要最高权限是为了能列出全部的存储桶
