### ISSUE TITLE
[Bug]: 相册URL改名的问题

### ISSUE THREAD

**Issue by toyo2333** [Kuingsmile/PicList#138]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

最新

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

用的是R2，已经在R2把图片的目录结果做了调整：2024/01 改为 202401，即可
https://xx.r2.dev/2024/01/cfce4d74cd8cfb06bdb7e0e41ab32fc2.jpg
改为
https://xx.r2.dev/202401/cfce4d74cd8cfb06bdb7e0e41ab32fc2.jpg

现在我打算把相册里的图片的URL也修改一下。

1. 在相册里点“修改”，然后进行修改，比如我把我的92张图片里 `2024/01 `改为 `202401`，此时点'确定'，没有弹出修改成功或失败的提示框，这个时候，我再进去在搜`2024/01` 发现有30多个，于是再进行一轮才全部改完。这里问题是：`点击确定，没有修改结果的popup，我都不知道有30多个失败了50多个成功了。`

2. 这个时候我再去相册里点任意一个图片的复制信息功能，复制出来的url还是2024/01而不是202401，挑了很多图片都是这样，这是修改失败了么？可是我再去“修改”里面搜`2024/01`已经搜不到了是0个，搜`202401`就能搜到92个。在相册里的“搜索URL”里也只能搜到`202401`，那么问题就是为什么我复制图片的信息复制出来的URL里还是`2024/01`，我重启过程序，还是这样。你这些相册里的照片不是读取云服务器上的照片么？为什么URL错误了照片还能显示出来呢？

补充：我想了下，我点修改之前，是点了全选按钮的，然后再点修改进行上述操作。

**Comment by Kuingsmile** [comment]
改目录这个操作我需要测试下，测试后进行跟进

**Comment by Kuingsmile** [comment]
复现定位成功，已在 https://github.com/Kuingsmile/PicList/commit/0e81ccdf81747dd0aeee77565397ea1532bc34b1
进行修复
