### ISSUE TITLE
[Bug]: 现在无法上传图片到图床（之前一直可以，配置以及网络代理均为变动）

### ISSUE THREAD

**Issue by lightcoming** [Kuingsmile/PicList#139]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

latest(v2.7.0)

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

![image](https://github.com/Kuingsmile/PicList/assets/71441743/525d2269-5ad1-4a52-a18c-12a3ac11c100)
如图在管理中无法查看smms图床中的内容，也无法通过该工具上传到图床，而浏览器里是可以上传的

### 相关日志 | Logs

2024-01-14 09:19:50 [PicList ERROR] {
  "method": "POST",
  "url": "https://smms.app/api/v2/upload",
  "statusCode": 0,
  "message": "connect ETIMEDOUT 172.67.219.23:443",
  "stack": "Error: connect ETIMEDOUT 172.67.219.23:443\n    at AxiosError.from (D:\\Program Files\\PicList\\resources\\app.asar\\node_modules\\axios\\dist\\node\\axios.cjs:837:14)\n    at RedirectableRequest.handleRequestError (D:\\Program Files\\PicList\\resources\\app.asar\\node_modules\\axios\\dist\\node\\axios.cjs:3083:25)\n    at RedirectableRequest.emit (node:events:513:28)\n    at eventHandlers.<computed> (D:\\Program Files\\PicList\\resources\\app.asar\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:513:28)\n    at TLSSocket.socketErrorListener (node:_http_client:481:9)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
}

**Comment by Kuingsmile** [comment]
我这边测试没有异常，检查下你的网络，smms.app在我这边是可以直连的

`"message": "connect ETIMEDOUT 172.67.219.23:443",`从这个报错看是网络问题

**Comment by Kuingsmile** [comment]
172.67.219.23我查了下是cloudflare的cdn地址，让这个地址走下翻墙代理试试

**Comment by lightcoming** [comment]
> 172.67.219.23我查了下是cloudflare的cdn地址，让这个地址走下翻墙代理试试

谢谢~，走代理就可以了，有点奇怪，smms.app浏览器不需要通过代理，而这个软件之前也不需要代理，最近却需要代理了

**Comment by BrickerZou** [comment]
我也一样的问题，之前用smms不需要代理，设置代理也不行
