### ISSUE TITLE
批量编辑文件名

### ISSUE THREAD

**Issue by yenan3** [Kuingsmile/PicList#14]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v1.3.0

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

希望能有编辑（批量编辑）云端文件名的功能

**Comment by Kuingsmile** [comment]
> ### 前置阅读 | Pre-reading
> * [x]  [文档/Doc](https://picgo.github.io/PicGo-Doc/)
> * [x]  [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
> * [x]  [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)
> 
> ### PicList的版本 | PicList Version
> v1.3.0
> 
> ### 系统信息 | System Information
> Windows
> 
> ### 功能请求 | Feature request
> 希望能有编辑（批量编辑）云端文件名的功能

我试下，这里的需求可以更具体一点么，比如需要不要做占位符替换，使用{Y} {md5} 或者随机字符串等，或者还是通过固定前缀加递增数字进行区分的形式。

或者更直接一点，提供两个输入框，分别是匹配用的正则表达式和希望替换的字符

**Comment by yenan3** [comment]
这一点挺不错的：提供两个输入框，分别是匹配用的正则表达式和希望替换的字符

**Comment by Kuingsmile** [comment]
> 这一点挺不错的：提供两个输入框，分别是匹配用的正则表达式和希望替换的字符

好的 大概了解了 我想想怎么弄~

**Comment by Kuingsmile** [comment]
![image](https://user-images.githubusercontent.com/96409857/222101967-a0f63fad-b010-4269-b948-21bac6cf8145.png)
已基本完成开发，预计下个版本带出 @yenan3

**Comment by yenan3** [comment]
感谢感谢🙏
