### ISSUE TITLE
[Bug]: 程序无法持续在后台运行

### ISSUE THREAD

**Issue by ghost** [Kuingsmile/PicList#141]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.7.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

如题, 我为程序设置了静默启动. 但是在Obsidian中上传图片时收到了empty response, 此时PicList并未在运行, 在系统托盘也找不到软件图标. 希望能得到帮助和解答, 谢谢!

**Comment by ghost** [comment]
此外, 如果PicList在任务栏运行, 在Obsidian中试图上传图片时PicList会直接退出.

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/96409857/82ca7489-7b7f-47d0-bcec-61cb5c368a76)
静默启动指的是启动的时候不显示主界面，不是自动启动

**Comment by Kuingsmile** [comment]
> 此外, 如果PicList在任务栏运行, 在Obsidian中试图上传图片时PicList会直接退出.
![image](https://github.com/Kuingsmile/PicList/assets/96409857/9b10b07a-164d-40d8-a583-3b6febaaecae)

使用的什么图床，在`高级设置-设置日志文件`里打开GUI日志文件看下是什么报错
