### ISSUE TITLE
[Feature]: 请问考虑支持Gitee吗？

### ISSUE THREAD

**Issue by ma3252788** [Kuingsmile/PicList#142]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.7.1

### 系统信息 | System Information

Mac

### 功能请求 | Feature request

目前好像只支持GitHub，我按照格式填了Gitee的信息，发现报401错误，看了log，是API地址的事。

请问大佬后面会增加Gitee的支持吗？

**Comment by Kuingsmile** [comment]
目前有插件支持，可以直接搜索gitee安装
![image](https://github.com/Kuingsmile/PicList/assets/96409857/afbdd1f9-34b1-458a-bd37-d40bc4bb587e)

https://github.com/zhanghuid/picgo-plugin-gitee
https://github.com/lizhuangs/picgo-plugin-gitee-uploader#readme

**Comment by ma3252788** [comment]
> 目前有插件支持，可以直接搜索gitee安装 ![image](https://private-user-images.githubusercontent.com/96409857/297954682-afbdd1f9-34b1-458a-bd37-d40bc4bb587e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDI5MTYsIm5iZiI6MTcwNTY0MjYxNiwicGF0aCI6Ii85NjQwOTg1Ny8yOTc5NTQ2ODItYWZiZGQxZjktMzRiMS00NThhLWJkMzctZDQwYmM0YmI1ODdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA1MzY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlOThkOWYxZWQ2NzgwMzc3NmQ4ZThmYjVkNzZmNjU4MDhiMGM3NTJkMjI4MjdhNTM4Zjc3ZGMwYjE1MmI2MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D0GEIeU-CcffMgL_fs0PCE2C9dgGg85pQO2Xxh2hqt0)
> 
> https://github.com/zhanghuid/picgo-plugin-gitee https://github.com/lizhuangs/picgo-plugin-gitee-uploader#readme

谢谢大佬。我刚刚测试了下，发现报错：

```
2024-01-19 13:52:44 [PicList INFO] Before transform 
2024-01-19 13:52:44 [PicList INFO] Transforming... Current transformer is [path] 
2024-01-19 13:52:44 [PicList INFO] Before upload 
2024-01-19 13:52:44 [PicList INFO] beforeUploadPlugins: renameFn running 
2024-01-19 13:52:44 [PicList INFO] Uploading... Current uploader is [gitee] 
2024-01-19 13:52:44 [PicList INFO] [上传操作]异常：Request failed with status code 403 
2024-01-19 13:52:44 [PicList SUCCESS] 
```

网上查了下，貌似Gitee有防盗链，估计以后用不了了。。
