### ISSUE TITLE
[Bug]: 又拍云API出错

### ISSUE THREAD

**Issue by ma3252788** [Kuingsmile/PicList#143]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.7.1

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

本地两台电脑，一台电脑正常，一台电脑报错。
我看了log，应该是API无法访问，不过很是奇怪，同样的网络，为啥一个可以一个不行。
就是这个：https://v0.api.upyun.com/

我发现v0不行，但是v1可以。

<img width="745" alt="image" src="https://github.com/Kuingsmile/PicList/assets/22229456/7d1dd4c0-c668-4424-93a7-32a34a973bbd">
<img width="605" alt="image" src="https://github.com/Kuingsmile/PicList/assets/22229456/3971dd23-376a-482c-9057-6ea511be8707">

所以，大佬，可不可以增加一个选项，可以自定义API地址呀？

### 相关日志 | Logs

2024-01-19 14:00:47 [PicList ERROR] {
  "method": "PUT",
  "url": "https://v0.api.upyun.com/machuc/machie/81.jpg",
  "statusCode": 0,
  "message": "read ECONNRESET",
  "stack": "Error: read ECONNRESET\n    at AxiosError.from (/Applications/PicList.app/Contents/Resources/app.asar/node_modules/axios/dist/node/axios.cjs:837:14)\n    at RedirectableRequest.handleRequestError (/Applications/PicList.app/Contents/Resources/app.asar/node_modules/axios/dist/node/axios.cjs:3083:25)\n    at RedirectableRequest.emit (node:events:513:28)\n    at eventHandlers.<computed> (/Applications/PicList.app/Contents/Resources/app.asar/node_modules/follow-redirects/index.js:14:24)\n    at ClientRequest.emit (node:events:513:28)\n    at TLSSocket.socketErrorListener (node:_http_client:481:9)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
}

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/96409857/9f74ae36-5846-4b8f-8e77-5f39e301515a)
v0是自动选择线路的接口地址，v1是电信的，我试了下我这v0是ok的，检查下两台电脑网络的差异？
![image](https://github.com/Kuingsmile/PicList/assets/96409857/63f9fcf4-e4ba-4422-993b-6b720d834e63)

**Comment by ma3252788** [comment]
> ![image](https://private-user-images.githubusercontent.com/96409857/297970046-9f74ae36-5846-4b8f-8e77-5f39e301515a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDUxODcsIm5iZiI6MTcwNTY0NDg4NywicGF0aCI6Ii85NjQwOTg1Ny8yOTc5NzAwNDYtOWY3NGFlMzYtNTg0Ni00YjhmLThlNzctNWYzOWUzMDE1MTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA2MTQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MjkxZmViMjM2MjdjOTY0MWY1MTAyODUyNmRkMzg0NTE5ZTM5NTFmODUzNTFmMWE1OTc3YTgwMjdlMWYwNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QFqny0jcS1kNurPUGPdD_ZKDD6UPCjbIdeX89-107P4) v0是自动选择线路的接口地址，v1是电信的，我试了下我这v0是ok的，检查下两台电脑网络的差异？ ![image](https://private-user-images.githubusercontent.com/96409857/297970256-63f9fcf4-e4ba-4422-993b-6b720d834e63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDUxODcsIm5iZiI6MTcwNTY0NDg4NywicGF0aCI6Ii85NjQwOTg1Ny8yOTc5NzAyNTYtNjNmOWZjZjQtZTRiYS00NDIyLTk5M2ItNmI3MjBkODM0ZTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA2MTQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxNGIyZDhlYWZiYzlmMWZiNDdjNDY4ZTE3Yjg2YzBhMThmYWYwNDY1MmUwYjdlNmFhNzA4YzExYWQ2OGIxOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IaQ9BgCsfctcrfFIt23ZuWRhOlf_p9l8Ag39v1i0zN8)

两个电脑环境一致，在同一个WiFi下面，都没有用代理。。。所以我感觉挺奇怪的。。

我刚刚找了第三台电脑测试，也是无法访问，就只有那一台可以。。

v1、v2和v3我这里手动测试都能打开，但是换成v0的时候就不行了

**Comment by Kuingsmile** [comment]
> > ![image](https://private-user-images.githubusercontent.com/96409857/297970046-9f74ae36-5846-4b8f-8e77-5f39e301515a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDUxODcsIm5iZiI6MTcwNTY0NDg4NywicGF0aCI6Ii85NjQwOTg1Ny8yOTc5NzAwNDYtOWY3NGFlMzYtNTg0Ni00YjhmLThlNzctNWYzOWUzMDE1MTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA2MTQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MjkxZmViMjM2MjdjOTY0MWY1MTAyODUyNmRkMzg0NTE5ZTM5NTFmODUzNTFmMWE1OTc3YTgwMjdlMWYwNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QFqny0jcS1kNurPUGPdD_ZKDD6UPCjbIdeX89-107P4) v0是自动选择线路的接口地址，v1是电信的，我试了下我这v0是ok的，检查下两台电脑网络的差异？ ![image](https://private-user-images.githubusercontent.com/96409857/297970256-63f9fcf4-e4ba-4422-993b-6b720d834e63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDUxODcsIm5iZiI6MTcwNTY0NDg4NywicGF0aCI6Ii85NjQwOTg1Ny8yOTc5NzAyNTYtNjNmOWZjZjQtZTRiYS00NDIyLTk5M2ItNmI3MjBkODM0ZTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA2MTQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxNGIyZDhlYWZiYzlmMWZiNDdjNDY4ZTE3Yjg2YzBhMThmYWYwNDY1MmUwYjdlNmFhNzA4YzExYWQ2OGIxOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IaQ9BgCsfctcrfFIt23ZuWRhOlf_p9l8Ag39v1i0zN8)
> 
> 两个电脑环境一致，在同一个WiFi下面，都没有用代理。。。所以我感觉挺奇怪的。。
> 
> 我刚刚找了第三台电脑测试，也是无法访问，就只有那一台可以。。
> 
> v1、v2和v3我这里手动测试都能打开，但是换成v0的时候就不行了

这么诡异的嘛 可以加一个自定义api地址，修改量不多，但具体为啥v0不能访问就不清楚了

**Comment by ma3252788** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/96409857/297970046-9f74ae36-5846-4b8f-8e77-5f39e301515a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDUxODcsIm5iZiI6MTcwNTY0NDg4NywicGF0aCI6Ii85NjQwOTg1Ny8yOTc5NzAwNDYtOWY3NGFlMzYtNTg0Ni00YjhmLThlNzctNWYzOWUzMDE1MTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA2MTQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MjkxZmViMjM2MjdjOTY0MWY1MTAyODUyNmRkMzg0NTE5ZTM5NTFmODUzNTFmMWE1OTc3YTgwMjdlMWYwNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QFqny0jcS1kNurPUGPdD_ZKDD6UPCjbIdeX89-107P4) v0是自动选择线路的接口地址，v1是电信的，我试了下我这v0是ok的，检查下两台电脑网络的差异？ ![image](https://private-user-images.githubusercontent.com/96409857/297970256-63f9fcf4-e4ba-4422-993b-6b720d834e63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDUxODcsIm5iZiI6MTcwNTY0NDg4NywicGF0aCI6Ii85NjQwOTg1Ny8yOTc5NzAyNTYtNjNmOWZjZjQtZTRiYS00NDIyLTk5M2ItNmI3MjBkODM0ZTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA2MTQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxNGIyZDhlYWZiYzlmMWZiNDdjNDY4ZTE3Yjg2YzBhMThmYWYwNDY1MmUwYjdlNmFhNzA4YzExYWQ2OGIxOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IaQ9BgCsfctcrfFIt23ZuWRhOlf_p9l8Ag39v1i0zN8)
> > 
> > 
> > 两个电脑环境一致，在同一个WiFi下面，都没有用代理。。。所以我感觉挺奇怪的。。
> > 我刚刚找了第三台电脑测试，也是无法访问，就只有那一台可以。。
> > v1、v2和v3我这里手动测试都能打开，但是换成v0的时候就不行了
> 
> 这么诡异的嘛 可以加一个自定义api地址，修改量不多，但具体为啥v0不能访问就不清楚了

😌，确实挺诡异。。这个问题好几天了，我这几天都是用代理访问又拍云。后来2.7.1出来之后，就换成webdav了。。

今天看log才发现是v0这个API选择的问题。。

谢谢大佬！！

**Comment by Kuingsmile** [comment]
已在最新提交添加，下一版本带出
