### ISSUE TITLE
[Bug]: 当我使用smms、nextcloud作为图床时测试，我无法给图片加任何水印

### ISSUE THREAD

**Issue by glxaa** [Kuingsmile/PicList#146]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.7.2

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

水印配置如下：
![image](https://github.com/Kuingsmile/PicList/assets/119774429/2165c1a0-c326-444a-b033-e77959975f39)
上传成功后还是原图样式：
![image](https://github.com/Kuingsmile/PicList/assets/119774429/4f717be6-f71f-430d-be2b-0f25af261ef3)

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/96409857/6348624a-bdee-436d-b057-7429afedd3eb)
留空

**Comment by glxaa** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/119774429/3c53f10f-88ef-4086-aac8-13aeaa824d67)
我看本地有字体文件来着
并且，我尝试是否能添图片水印
![image](https://github.com/Kuingsmile/PicList/assets/119774429/a58627f9-83ec-45bf-a5a3-3af61a20f50f)
不论是否留空图片地址，都没有产生图片，我不确定这是BUG还是我配置的问题。
不过这并不影响我喜爱并且使用它。

**Comment by Kuingsmile** [comment]
> ![image](https://private-user-images.githubusercontent.com/119774429/298824268-3c53f10f-88ef-4086-aac8-13aeaa824d67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5OTEzMDEsIm5iZiI6MTcwNTk5MTAwMSwicGF0aCI6Ii8xMTk3NzQ0MjkvMjk4ODI0MjY4LTNjNTNmMTBmLTg4ZWYtNDA4Ni1hYWM4LTEzYWVhYTgyNGQ2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QwNjIzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDg0ZWQ5YmMxODRlMjkxMTEzOTUxYWM1OTkyYTU4ZjhiYjM4ZTRkMTFjZWJlMzJkM2ZlOGFhNjdkNTYyYjY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NQTJnReWfjX8jSORFOjMfQaA_KY1hpPAu8XHJueI2rE) 我看本地有字体文件来着 并且，我尝试是否能添图片水印 ![image](https://private-user-images.githubusercontent.com/119774429/298825252-a58627f9-83ec-45bf-a5a3-3af61a20f50f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5OTEzMDEsIm5iZiI6MTcwNTk5MTAwMSwicGF0aCI6Ii8xMTk3NzQ0MjkvMjk4ODI1MjUyLWE1ODYyN2Y5LTgzZWMtNDViZi1hNWEzLTNhZjYxYTIwZjUwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QwNjIzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjk3ODVmYmQ2ZjMyMTdlM2M0NzRlZWE2YmRmZWJhNDk0Y2NhNTI1NWQ4MThiYTMwODJiZWIzYzhlY2M2NGJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JoeZAW0n4Ly-4y8jc2d-MTXIMFgWf-pnRw-2zfs7yAs) 不论是否留空图片地址，都没有产生图片，我不确定这是BUG还是我配置的问题。 不过这并不影响我喜爱并且使用它。

你之前填的字体路径中的`%APPDATA%`是windows下的特殊标记，不是绝对路径，没有办法识别。另外请检查设置完后是否进行了保存。
我本地测试了文字和图片水印均未复现出问题。
