### ISSUE TITLE
[Bug]: 图床AWS S3上传图片名错误

### ISSUE THREAD

**Issue by zhang-nianqiang** [Kuingsmile/PicList#148]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.7.2

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

sorry! it's me again!
我第一次使用软件,抱歉!
上传图片后我发现在图床里的图片名是"githubpage"我的桶里的路径名,
![image](https://github.com/Kuingsmile/PicList/assets/19368999/6ee40d8a-4332-41cf-b55a-0d96223d9265)
但在相册里是正常的
![image](https://github.com/Kuingsmile/PicList/assets/19368999/50e865ab-07da-4031-9a1c-a50873f39e2c)
我想知道我在哪里有错误呢!
![image](https://github.com/Kuingsmile/PicList/assets/19368999/d78c7bff-a63a-42d4-a366-f4ce94c18cd8)
请求帮助!

**Comment by Kuingsmile** [comment]
参考https://github.com/wayjam/picgo-plugin-s3
路径应该写成`githubpage/{fullName}`

**Comment by Kuingsmile** [comment]
内置S3图床的对应文档还没来得及写，可以先参考上面插件的，基本一样。后面我会在官方文档里更新使用说明。
