### ISSUE TITLE
从浏览器上上传图片

### ISSUE THREAD

**Issue by pkufool** [Kuingsmile/PicList#153]
很棒的项目！ 如题，有这个开发计划吗？

**Comment by Kuingsmile** [comment]
> 很棒的项目！ 如题，有这个开发计划吗？

之前写过一个纯前端静态网页版本，但存在几个问题：
1. 跨域问题，这个有试过用cors-anywhere去绕过，但仍然需要搭个后端服务
2. 剪贴板图片的获取问题
3. 图片处理/水印/压缩等高级功能无法实现或处理速度比较慢的问题

如果要加个后台的话，那就成了需要自己部署的图床项目了，目前已经有很多成熟的项目，没必要重复开发

PS:pku校友？

**Comment by pkufool** [comment]
> 之前写过一个纯前端静态网页版本，但存在几个问题

代码有开源吗？

> 如果要加个后台的话，那就成了需要自己部署的图床项目了，目前已经有很多成熟的项目，没必要重复开发

确实，目前已经很好了，浏览器其实是一个比较边缘的需求，比如临时外出不是自己的电脑，或者使用公用电脑等。
 
> PS:pku校友？

哈哈，互粉一下？🤦‍

**Comment by Kuingsmile** [comment]
> 项目了，目前已经有很多成熟的项目，没必要



> > 之前写过一个纯前端静态网页版本，但存在几个问题
> 
> 代码有开源吗？
> 
> > 如果要加个后台的话，那就成了需要自己部署的图床项目了，目前已经有很多成熟的项目，没必要重复开发
> 
> 确实，目前已经很好了，浏览器其实是一个比较边缘的需求，比如临时外出不是自己的电脑，或者使用公用电脑等。
> 
> > PS:pku校友？
> 
> 哈哈，互粉一下？🤦‍

followed~~  网页版的其实就是提取了这个项目的前台部分改的，写了下感觉不太可行就删掉了.
