### ISSUE TITLE
[Bug]: 上传图片会自动修改图片名

### ISSUE THREAD

**Issue by lianyant** [Kuingsmile/PicList#154]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.7.3

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

当我上传一个名为"有村架纯.png”的图片时，首先在在相册区域是这样的：
![QQ截图20240131003718](https://github.com/Kuingsmile/PicList/assets/52623744/1542c301-71de-43d1-88bf-8b430badf898)

我点击它也无法预览（一直转圈）：
![QQ截图20240131003804](https://github.com/Kuingsmile/PicList/assets/52623744/0126d4bf-3f61-4bac-b425-e8359421976c)

然后我去到腾讯云cos中去查看这个图片，确实有上传到腾讯云端了，但是文件名不对：
![image-20240131003922503](https://github.com/Kuingsmile/PicList/assets/52623744/c4e4480a-cb25-4731-b384-e22463f56387)
发现时自动在文件名之前加了个“undefined”.

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/96409857/e7c01714-bc25-4cd6-9fa1-c436fd302550)
这三个设置都是关闭状态么 还有腾讯云怎么配置的 我测试了下没有能复现
![image](https://github.com/Kuingsmile/PicList/assets/96409857/18f61b91-c3b2-47ad-b85f-860d72cb2146)

**Comment by lianyant** [comment]
已解决，看了下。是此处的原因导致的：
![QQ截图20240131230317](https://github.com/Kuingsmile/PicList/assets/52623744/cac87331-7b24-41ff-b473-02ea40e0b9e3)

这个一开始是关闭状态的，我将其开启之后就正常了。 建议以后的版本中默认将开关开启就行了!

感谢您的回答
