### ISSUE TITLE
[Bug]: 3个问题

### ISSUE THREAD

**Issue by toyo2333** [Kuingsmile/PicList#155]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

最新

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

1. 图床管理里，按修改时间排序功能无效
2. 图床上传设置的图床配置名是可以重复的，比如我可以建立2个同名的都叫post（可以通过导入方式填写），这样复制API的时候2个api相同，那么怎么知道调用的是哪个配置？
3. disableBucketPrefixToURL/是否禁用存储桶前缀 这个变量命名是disable，是不是错了，ui里填写的是false，实际上是不启用把？默认值是什么？

**Comment by Kuingsmile** [comment]
1. 测试可以，你无效的是哪个图床
2. 这种自己手动修改下配置名就好了
3. 这个沿用了插件https://github.com/wayjam/picgo-plugin-s3  的设置，默认值false,这部分的代码来自插件，不过我刚才看了下这里的代码有点问题，保存的设置值是字符串，所以这个设置实际上没有起作用，会一直禁用存储桶前缀，这里我修复下

**Comment by Kuingsmile** [comment]
第三个问题在最新提交 https://github.com/Kuingsmile/PicList/commit/914ec15361bde953f8fe9be045c830c79b89b4e4 修复

**Comment by toyo2333** [comment]
> 1. 测试可以，你无效的是哪个图床

是S3 CF R2

> 3. 这个沿用了插件https://github.com/wayjam/picgo-plugin-s3  的设置，默认值false,这部分的代码来自插件，不过我刚才看了下这里的代码有点问题，保存的设置值是字符串，所以这个设置实际上没有起作用，会一直禁用存储桶前缀，这里我修复下

我现在这个地方写的是false，更新后会怎么样？到底通常应该是禁用前缀还是应该带上前缀好？

**Comment by toyo2333** [comment]
再补充一个bug4

我一个jpg的图片160kb，然后通过图片处理设置压缩
- 质量70
- 转换给是为jpg
- 去除exif信息

结构压出来后size还变大了到240kb

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/96409857/dcadb477-c347-4cf5-b11c-0e4b13d1f782)
R2我这边也可以 正常的 另外目录不支持时间排序

设置为false R2就不用管了，维持false就行

**Comment by Kuingsmile** [comment]
> 再补充一个bug4
> 
> 我一个jpg的图片160kb，然后通过图片处理设置压缩
> 
> * 质量70
> * 转换给是为jpg
> * 去除exif信息
> 
> 结构压出来后size还变大了到240kb

这个跟图片有关 不算bug 不保证一定变小 我用200Kb的图片测试是到40Kb

**Comment by toyo2333** [comment]
> ![image](https://private-user-images.githubusercontent.com/96409857/301073817-dcadb477-c347-4cf5-b11c-0e4b13d1f782.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2ODg2MDMsIm5iZiI6MTcwNjY4ODMwMywicGF0aCI6Ii85NjQwOTg1Ny8zMDEwNzM4MTctZGNhZGI0NzctYzM0Ny00Y2Y1LWIxMWMtMGU0YjEzZDFmNzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDA4MDUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2MTk1NTc2MWE5ZTU5MzhjMDQ3MTFiNjAyYzg2Zjc3Y2E5ODJiYjk5ZDYzZTNjNzgyNzM5ZGY1YmVmOWQzOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UTE5zZtMqwTvMyuJywLYB25J8tleD4knsCfJsUenCaI) R2我这边也可以 正常的 另外目录不支持时间排序
> 
> 设置为false R2就不用管了，维持false就行

你先点按大小排序，再点按时间排序。

**Comment by Kuingsmile** [comment]
> > ![image](https://private-user-images.githubusercontent.com/96409857/301073817-dcadb477-c347-4cf5-b11c-0e4b13d1f782.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2ODg2MDMsIm5iZiI6MTcwNjY4ODMwMywicGF0aCI6Ii85NjQwOTg1Ny8zMDEwNzM4MTctZGNhZGI0NzctYzM0Ny00Y2Y1LWIxMWMtMGU0YjEzZDFmNzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDA4MDUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2MTk1NTc2MWE5ZTU5MzhjMDQ3MTFiNjAyYzg2Zjc3Y2E5ODJiYjk5ZDYzZTNjNzgyNzM5ZGY1YmVmOWQzOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UTE5zZtMqwTvMyuJywLYB25J8tleD4knsCfJsUenCaI) R2我这边也可以 正常的 另外目录不支持时间排序
> > 设置为false R2就不用管了，维持false就行
> 
> 你先点按大小排序，再点按时间排序。
![screenshots](https://github.com/Kuingsmile/PicList/assets/96409857/4f6a6886-b200-40d8-a590-207044f34946)
也没问题呀

**Comment by toyo2333** [comment]
> > 也没问题呀

那就不知道了。。我是在子目录里， /202401/xxxx.jpg 这样的

**Comment by Kuingsmile** [comment]
> > > 也没问题呀
> 
> 那就不知道了。。我是在子目录里， /202401/xxxx.jpg 这样的

我去子目录也试了下 也没问题。。

**Comment by toyo2333** [comment]
> > > > 也没问题呀
> > 
> > 
> > 那就不知道了。。我是在子目录里， /202401/xxxx.jpg 这样的
> 
> 我去子目录也试了下 也没问题。。

我又用了几天，我这里始终无法按时间排序。
