### ISSUE TITLE
[Bug]为什么总是“等待上传”

### ISSUE THREAD

**Issue by CrazyJasonwell** [Kuingsmile/PicList#156]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.7.3

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

监听剪切板后总是等待上传，要点击才能上传

### 相关日志 | Logs

无

**Comment by Kuingsmile** [comment]
上传到哪个图床

**Comment by Kuingsmile** [comment]
请提供更多信息，否则将关闭issue
