### ISSUE TITLE
[Bug]: 请问通过webdav上传网盘后，引用图片时不能正常显示是什么原因

### ISSUE THREAD

**Issue by yzgolden86** [Kuingsmile/PicList#157]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.7.3

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

我配置了webdav的上传方式，可以正常上传图片，但是引用图片时，却无法正常显示，显示如下：
![image](https://github.com/Kuingsmile/PicList/assets/56377040/0cc26d85-8446-4a21-91ca-168974c2d6e8)
请教一下是什么问题，另外，交流群二维码失效了，还有其他办法入群吗

### 相关日志 | Logs

无

**Comment by Kuingsmile** [comment]
teracloud的链接是webdav格式的，不支持直接外链，可以用alist或者兰空图床之类的转个直链出来
https://hostloc.com/thread-1159928-1-1.html
群已经满200人了 所以没有办法更新邀请二维码了

**Comment by yzgolden86** [comment]
> teracloud的链接是webdav格式的，不支持直接外链，可以用alist或者兰空图床之类的转个直链出来 https://hostloc.com/thread-1159928-1-1.html 群已经满200人了 所以没有办法更新邀请二维码了

好的，感谢
