### ISSUE TITLE
[Bug]: github图床相册删除，开启云端删除，删除失败

### ISSUE THREAD

**Issue by AILHC** [Kuingsmile/PicList#158]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.7.3

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

github图床，上传一张jpg图片，然后相册中开启云端删除，提示删除失败
![image](https://github.com/Kuingsmile/PicList/assets/21373809/e02b1728-64e5-4140-a622-152b85bf0c2f)

### 相关日志 | Logs

没有日志

**Comment by Kuingsmile** [comment]
打开控制台 看一下报错，打开方式主界面左下角小提示号点击后，弹出菜单点击打开控制台

**Comment by AILHC** [comment]
> 打开控制台 看一下报错，打开方式主界面左下角小提示号点击后，弹出菜单点击打开控制台

![image](https://github.com/Kuingsmile/PicList/assets/21373809/42312e39-d8ba-49c8-8c04-cfa74bcde34c)
![image](https://github.com/Kuingsmile/PicList/assets/21373809/1eb5ee94-330d-4c24-abff-4e85410fc441)

报错

**Comment by Kuingsmile** [comment]
> > 打开控制台 看一下报错，打开方式主界面左下角小提示号点击后，弹出菜单点击打开控制台
> 
> ![image](https://github.com/Kuingsmile/PicList/assets/21373809/42312e39-d8ba-49c8-8c04-cfa74bcde34c)
> ![image](https://github.com/Kuingsmile/PicList/assets/21373809/1eb5ee94-330d-4c24-abff-4e85410fc441)
> 
> 报错

应该是路径编码的问题，是否使用了高级重命名或重命名插件，另外麻烦发下github配置的上传路径部分，谢谢

**Comment by Kuingsmile** [comment]
路径里的img%2F1111应该是img/1111 ，应该是有个地方修改了文件名或路径

**Comment by Kuingsmile** [comment]
@AILHC 请提供更多的帮助复现的信息，我这里始终未能复现

**Comment by Kuingsmile** [comment]
虽然没有复现 不过我优化了下对`%2F`错误转码的处理 应该可以修复这种情况
