### ISSUE TITLE
[Bug]: mac使用typora报错

### ISSUE THREAD

**Issue by hyqf98** [Kuingsmile/PicList#160]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.7.3

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

使用typora上传图片报错

### 相关日志 | Logs

<img width="508" alt="image" src="https://github.com/Kuingsmile/PicList/assets/33802673/cbea4cb1-ec4c-4170-89c1-b14f4816c873">

**Comment by Kuingsmile** [comment]
看下软件的日志记录 这里的报错信息是常规警告信息 看不出具体问题.mac的日志路径应该是~/Library/Application Support/piclist/piclist.log
