### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by hhy5562877** [Kuingsmile/PicList#161]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.7.3

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

在安装gitee-smart插件的时候会产生闪退的现象

### 相关日志 | Logs

2024-02-08 14:15:02 [PicList INFO] [PicList Server] is listening at 36677 of 0.0.0.0 
2024-02-08 14:15:02 [PicList INFO] File server is running, http://localhost:36699 
2024-02-08 14:15:08 [PicList ERROR] 插件更新失败，请输入合法插件名 
2024-02-08 14:15:26 [PicList ERROR] 插件安装失败，失败码为4294963238，错误日志为 
 [37;40mnpm[0m [0m[30;43mWARN[0m [0m[35mtarball[0m tarball data for picgo-plugin-gitee-smart@file:picgo-plugin-gitee-smart (null) seems to be corrupted. Trying again.
[0m[37;40mnpm[0m [0m[30;43mWARN[0m [0m[35mtarball[0m tarball data for picgo-plugin-gitee-smart@file:picgo-plugin-gitee-smart (null) seems to be corrupted. Trying again.
[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35mcode[0m ENOENT
[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35msyscall[0m open
[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35mpath[0m C:\Users\17638\AppData\Roaming\piclist\picgo-plugin-gitee-smart/package.json
[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35merrno[0m -4058
[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35menoent[0m ENOENT: no such file or directory, open 'C:\Users\17638\AppData\Roaming\piclist\picgo-plugin-gitee-smart\package.json'
[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35menoent[0m This is related to npm not being able to find a file.
[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35menoent[0m 
[0m
[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m A complete log of this run can be found in: C:\Users\17638\AppData\Local\npm-cache\_logs\2024-02-08T06_15_25_311Z-debug-0.log
[0m 
2024-02-08 14:18:44 [PicList ERROR]

**Comment by Kuingsmile** [comment]
高级设置里改下npm源试下 改到淘宝源`https://registry.npmmirror.com`

https://piclist.cn/configure.html#%E9%AB%98%E7%BA%A7%E8%AE%BE%E7%BD%AE

**Comment by Kuingsmile** [comment]
我自己安装了下是可以正常安装的

**Comment by hhy5562877** [comment]
这个是安装之后会闪退不知道为什么

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/96409857/2234aed2-fc2a-4bde-80b1-9a84a117c67a)
复现不出来呐 我这安装一直是正常的。。

**Comment by Kuingsmile** [comment]
https://blog.csdn.net/sufubo/article/details/129717826

node版本是多少,我的是用nvm安装的18.16.0版本。要不试试重装node，还有上面的改到淘宝源`https://registry.npmmirror.com`
