### ISSUE TITLE
[Feature]: 请匹配arm64

### ISSUE THREAD

**Issue by woshichenghaibo** [Kuingsmile/PicList#162]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

latest

### 系统信息 | System Information

Linux

### 功能请求 | Feature request

输入以下指令
docker run -d \
  --name Piclist \
  --restart always \
  -p 36677:36677 \
  -v "./piclist:/root/.piclist" \
  kuingsmile/piclist:latest \
  node /usr/local/bin/picgo-server -k cplsit

提示出错:no matching manifest for windows/amd64  in the manifest list entries.

**Comment by woshichenghaibo** [comment]
![IMG_20240208_171821](https://github.com/Kuingsmile/PicList/assets/80568737/89912f55-c54b-4104-9979-4b24a7c0aaac)

**Comment by Kuingsmile** [comment]
我节后看下

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/96409857/93ce1fda-67fe-43eb-900d-bfe9a0b9ea94)
已添加 @woshichenghaibo

**Comment by woshichenghaibo** [comment]
是不是还没更新release？我如果不编译，docker直接用的话是不是还不行？

**Comment by Kuingsmile** [comment]
重新docker pull一下应该就行了
