### ISSUE TITLE
[Bug]: 相册无法删除云端文件了

### ISSUE THREAD

**Issue by toyo2333** [Kuingsmile/PicList#164]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

最新

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

我突发发现相册中某日期之前的图片都无法删除云端文件了（新上传的没问题）

情况是，提示删除失败，提示有的是是这样的“XXXXXXXXXXXXXXX.jpg 云端删除失败” （这里和URL的文件名是一样的），其他大部分是是这样的“XXXXXXXXXXXXX_MD5.png 云端删除失败” （这里和URL里的文件名不一样）

这里就很奇怪。我之前确实批量改过一次URL，涉及目录结构，但文件名应该没有改过。这个加了_MD5的文件名是Obsidian的插件自动生成的本地文件名，云端的都没有这个。不知道为什么你本地相册数据库里存的是这个。

现在这些变成了脏数据，我只能去图床管理里删除。有没有什么办法定位问题，并修复？

**Comment by Kuingsmile** [comment]
有可以复现的操作步骤么 单凭描述不太能定位问题

**Comment by toyo2333** [comment]
> 有可以复现的操作步骤么 单凭描述不太能定位问题

没有，就是不知道怎么就变成这样了。。。

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/96409857/8f0ec1ce-28ec-4074-956c-508b57e0768d)
应该和你改目录结构有关 相册里的记录是本地存储的 不会随着你改目录更新 所以删除不掉

**Comment by cooper1x** [comment]
我也出现了这个问题，github 提示成功，但实际还是可以访问到这个图片，cos 的完全删不掉。我的 Mac OS

**Comment by Kuingsmile** [comment]
> 我也出现了这个问题，github 提示成功，但实际还是可以访问到这个图片，cos 的完全删不掉。我的 Mac OS

![image](https://github.com/Kuingsmile/PicList/assets/96409857/4b42e242-0757-4e3b-b267-fbe565db499d)
![screenshots](https://github.com/Kuingsmile/PicList/assets/96409857/f4df2d15-722a-4509-995e-3d6ca752769c)
![240330 133135](https://github.com/Kuingsmile/PicList/assets/96409857/4b9a1a70-0d04-4ed7-8a51-b623e07679ab)
我在vmare的macos里测试都是正常的，打开开发者工具控制台查看下删除过程中是否有报错
![image](https://github.com/Kuingsmile/PicList/assets/96409857/2f37742d-e092-48d2-aba6-b6e34d556386)

**Comment by cooper1x** [comment]
确实执行了删除，文件也没有了，但还是能访问到，奇怪。
<img width="695" alt="image" src="https://github.com/Kuingsmile/PicList/assets/9080789/8991a60e-8905-42f9-8a8f-2afdb2936f72">
https://raw.githubusercontent.com/cooper1x/web-clipper-img/main/img/202403301444772.png

**Comment by cooper1x** [comment]
现在访问不到了，貌似是有缓存
