### ISSUE TITLE
[Feature]: 微信交流群满200人已经扫码进不去了

### ISSUE THREAD

**Issue by benjamin603** [Kuingsmile/PicList#165]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.7.3

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

如题！

**Comment by Kuingsmile** [comment]
可以加我微信cn_heluo,备注github,拉你进来
