### ISSUE TITLE
[Feature]: 自定义复制功能

### ISSUE THREAD

**Issue by ZefanHu** [Kuingsmile/PicList#167]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.7.3

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

相册中每张图片都有一个复制按钮，我想统一修改图片URL，现有功能可以修改，但是我想上传时自动修改链接，不是改动云端，只是本地剪切板直接返回自定义的链接，原因在于我的图床国内访问太慢了，结合typora创作时常图片不能显示。目前发现最方便的办法就是直接拿cloudflare反代。比如当我使用typora过程中粘贴了一张图片，通过piclist上传到了图床，得到图片链接：https://alist.xxx.com/image-20240228224200139.png 这时候，我希望剪切板得到的链接为下面这个样子：https://hello.xxxxxx.workers.dev/https://alist.xxx.com/image-20240228224200139.png。现有图片页面还需要进入之后修改，我希望能优化一下。这对我的写作很有帮助，希望大佬指点一二，我会使用正则和编写简单的js，如果开发好这个功能愿意上传到插件中给大家使用。
![image](https://github.com/Kuingsmile/PicList/assets/81904038/f6f4a538-8077-4a17-b9f6-b7957aac99ff)
![image](https://github.com/Kuingsmile/PicList/assets/81904038/1b71d8f6-22cf-4886-811e-fa34abeaac0d)
![image](https://github.com/Kuingsmile/PicList/assets/81904038/82e44168-5389-4629-93b9-019668ad7bd7)

**Comment by Kuingsmile** [comment]
如果是你这个需求的话，可以用自定义链接功能，如下图
![image](https://github.com/Kuingsmile/PicList/assets/96409857/67f801a4-c4b9-449e-a923-1fe3fbaea4e7)
针对你的需求，可以修改为`https://hello.xxxxxx.workers.dev/$url`,然后相册里复制链接的时候，选`Custom`,这样复制出的链接就是你需要的了
![image](https://github.com/Kuingsmile/PicList/assets/96409857/e5f91982-6df2-4487-8b1c-148e1bf57b10)

**Comment by ZefanHu** [comment]
> 如果是你这个需求的话，可以用自定义链接功能，如下图 ![image](https://private-user-images.githubusercontent.com/96409857/308806301-67f801a4-c4b9-449e-a923-1fe3fbaea4e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMjE4ODMsIm5iZiI6MTcwOTIyMTU4MywicGF0aCI6Ii85NjQwOTg1Ny8zMDg4MDYzMDEtNjdmODAxYTQtYzRiOS00NDllLWE5MjMtMWZlM2ZiYWVhNGU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDE1NDYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0NjI2NjU3MTE5YzIwN2ZhMWQ0ZGUxZTk2NzAyODcyN2I3MmJmNWE5YjAxNGI0YjlmYzZkNjcxMjYwN2VjOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gHcY5ei8KiTh5C34EXIdTdH-Fzod9BeIusS1_4_twuY) 针对你的需求，可以修改为`https://hello.xxxxxx.workers.dev/$url`,然后相册里复制链接的时候，选`Custom`,这样复制出的链接就是你需要的了 ![image](https://private-user-images.githubusercontent.com/96409857/308806706-e5f91982-6df2-4487-8b1c-148e1bf57b10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMjE4ODMsIm5iZiI6MTcwOTIyMTU4MywicGF0aCI6Ii85NjQwOTg1Ny8zMDg4MDY3MDYtZTVmOTE5ODItNmRmMi00NDg3LThiMWMtMTQ4ZTFiZjU3YjEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDE1NDYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NWUwMWQwZjlhOWRkOTllZTc4NzQ1YzRhYWNhNjgxMWUyNGMzNzE5ZTZlOWRlYmRhMTg3NzFmYmRhNGRjMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jo6hML5WqEK6zjJpQth6LAo70aNajoYzbb4rxsMmMco)

非常感谢，帮大忙了。请问我能否将typora中图像上传服务设定为自定义命令上传到piclist, 目前时选择piclist上传服务，开启插入图片时上传图片，之后typora替换图片链接为相应url，比如将!/[imgname/]/(C:\filepath\image.png)替换为!/[imgname/]/(https:\\alist.xxxxxx.com/d/GoogleDrive/202402282220245.png)       但是我想使用自定义脚本返回 
 !/[imgname/]/(https:\\hello.xxxxxx.workers.dev/https:\\alist.xxxxxx.com/d/GoogleDrive/202402282220245.png)
   这样就不用再去piclist里面复制，或者手动更改url了。
![image](https://github.com/Kuingsmile/PicList/assets/81904038/82ac1a54-2285-4783-b368-6b6fd90d406c)

![image](https://github.com/Kuingsmile/PicList/assets/81904038/8d61f139-aaa4-4d5c-8c5a-461dc399a0cc)

**Comment by ZefanHu** [comment]
> 如果是你这个需求的话，可以用自定义链接功能，如下图 ![image](https://private-user-images.githubusercontent.com/96409857/308806301-67f801a4-c4b9-449e-a923-1fe3fbaea4e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNjY4MDIsIm5iZiI6MTcwOTI2NjUwMiwicGF0aCI6Ii85NjQwOTg1Ny8zMDg4MDYzMDEtNjdmODAxYTQtYzRiOS00NDllLWE5MjMtMWZlM2ZiYWVhNGU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA0MTUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkM2QwNmRkMGEyZDA5YzZlMjUwNzY5MDE1YjI4ZjgzYjAyODkzYWE0ZTI1NmJkODFiNTczYzk5MzM3MGQ3OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yHZ0Yw2xPylqxEPpjaztmWpuQVq9As2B2_2omeNhmJE) 针对你的需求，可以修改为`https://hello.xxxxxx.workers.dev/$url`,然后相册里复制链接的时候，选`Custom`,这样复制出的链接就是你需要的了 ![image](https://private-user-images.githubusercontent.com/96409857/308806706-e5f91982-6df2-4487-8b1c-148e1bf57b10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNjY4MDIsIm5iZiI6MTcwOTI2NjUwMiwicGF0aCI6Ii85NjQwOTg1Ny8zMDg4MDY3MDYtZTVmOTE5ODItNmRmMi00NDg3LThiMWMtMTQ4ZTFiZjU3YjEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA0MTUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5MzMxMzkwM2E1MmFlNDY1ZGRkM2E0YTEzNmQyZDA5MzRjMDliZjUxNWUwN2E1ZmI2ODBkZTliZDBjNGVmZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oaIfueoOiw6yx0KtqTBtODVHJTcUMH1UXrAtWNsC71o)

我编写了一个简单的PowerShell脚本，已经实现了我上面的需求。感谢大佬开发的软件，非常喜欢。
