### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by CrazyJasonwell** [Kuingsmile/PicList#168]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.7.3

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

我架设了一个piclist作为server,另外一台客户端通过piclist接口外网连接我架设的piclist server（使用本地存储）,截屏后自动上传到我的服务器，但是我上传的图片的链接是那台服务器的本地存储地址，而不是我需要的外网链接URL。

**Comment by Kuingsmile** [comment]
https://piclist.cn/configure.html#%E6%9C%AC%E5%9C%B0%E5%9B%BE%E5%BA%8A

参考文档，设置customUrl和webPath

**Comment by CrazyJasonwell** [comment]
谢谢你的回复，但是我还是没有设置成功
customUrl=http://xx.yyy.zz:36677
webPath=images 或者不填写总是不成功
http://xx.yyy.zz:36677/images/xxxx.png  总是404!   自定义域名这样写：http://xx.yyy.zz:36677  可以吗？
预览和复制地址应该基于piclist server提供服务吗？

**Comment by Kuingsmile** [comment]
36677端口是piclist的上传用接口 不是访问接口 要根据你自己服务器上的文件访问服务来决定customUrl

**Comment by CrazyJasonwell** [comment]
就是说我的服务器自身应该有访问文件的服务比如：webdav/webserver，谢谢！
另外，新安装了2.7.4使用中还有几个问题，麻烦看一下：
1、Mac M1下piclist设置消息开后没有上传和链接拷贝成功推送提示，而intel下的mac系统消息推送正常
2、前面提到的本地存储，上传后，在相册功能中点击复制url，没有反应，也不提示任何消息，剪切板中没有内容。（我已使用webdav方式，能预览图片），如果是点击通过其他方式上传的图片还是能复制url到剪切板的。
3、设置了短链接，但是不稳定，有时候能转换成功，有时还是实际url

**Comment by Kuingsmile** [comment]
> 就是说我的服务器自身应该有访问文件的服务比如：webdav/webserver，谢谢！ 另外，新安装了2.7.4使用中还有几个问题，麻烦看一下： 1、Mac M1下piclist设置消息开后没有上传和链接拷贝成功推送提示，而intel下的mac系统消息推送正常 2、前面提到的本地存储，上传后，在相册功能中点击复制url，没有反应，也不提示任何消息，剪切板中没有内容。（我已使用webdav方式，能预览图片），如果是点击通过其他方式上传的图片还是能复制url到剪切板的。 3、设置了短链接，但是不稳定，有时候能转换成功，有时还是实际url

Mac M1这个我没有对应平台，不是很好测试，短链接默认是C1N平台的，应该是C1N接口不稳定

本地存储这个好像之前有人说过，但我一直无法复现。。

**Comment by CrazyJasonwell** [comment]
第2个问题和3个问题可能是因为本地地址不能生成短链接，点击复制也就没有反应，因为点击后我查看了剪切板没有内容。
现在主要是M1下客户端没有通知消息，不知怎么调试或者解决！

**Comment by Kuingsmile** [comment]
> 第2个问题和3个问题可能是因为本地地址不能生成短链接，点击复制也就没有反应，因为点击后我查看了剪切板没有内容。 现在主要是M1下客户端没有通知消息，不知怎么调试或者解决！

这个有点难搞 我先在下个版本给通知信息部分加个log记录吧 到时候麻烦帮我看下有什么报错么

**Comment by CrazyJasonwell** [comment]
好的 谢谢你的指点。
