### ISSUE TITLE
[Feature]: 添加图片重新获取功能

### ISSUE THREAD

**Issue by A5yncX** [Kuingsmile/PicList#169]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.7.4

### 系统信息 | System Information

Mac(arm64)

### 功能请求 | Feature request

使用图床: github + cloudflare自定义域名

遇到的问题: 在上传成功后 piclist的已上传页面会立刻出现我所上传的图片. 但是由于自定义了cf域名, 在被读取到之前会有一段时间. 这段时间若piclist没有读取到图片, 图片就会崩掉. (这在piclist和obsidian中导致了图片不可见, 我不知道是否有obsidian的原因)

功能请求: 增加刷新按钮,可以刷新已上传的图片. 或者延时后显示上传图片.
<img width="1001" alt="image" src="https://github.com/Kuingsmile/PicList/assets/54523269/b9c2814a-93ca-4410-9ae9-bcd054ce2789">

**Comment by Kuingsmile** [comment]
重启软件看下能刷到么 用了缓存来减少请求次数

**Comment by A5yncX** [comment]
重启不行.(在Obsidian中也是这样)

**Comment by A5yncX** [comment]
<img width="655" alt="image" src="https://github.com/Kuingsmile/PicList/assets/54523269/313a7d23-4b38-4145-9314-7a086cbf0821">
<img width="796" alt="image" src="https://github.com/Kuingsmile/PicList/assets/54523269/a125bf62-d7d5-4756-bf1c-a48c34579cd7">

**Comment by Kuingsmile** [comment]
> 重启不行.(在Obsidian中也是这样)

好的 那能提供下复现方法么 我来测试 比如cf和图床分别怎么设置可以复现

**Comment by A5yncX** [comment]
> > 重启不行.(在Obsidian中也是这样)
> 
> 好的 那能提供下复现方法么 我来测试 比如cf和图床分别怎么设置可以复现

只是设置了自定义前缀为cf的pages后的域名
<img width="1053" alt="image" src="https://github.com/Kuingsmile/PicList/assets/54523269/9381ac65-7134-4562-91d2-5d693ee4b7e4">

**Comment by Kuingsmile** [comment]
是github pages绑定cf自定义域名，还是cf pages功能绑定github仓库。

**Comment by A5yncX** [comment]
抱歉没有描述清楚, 是cf的pages绑定github仓库

**Comment by Kuingsmile** [comment]
已在相册页面添加硬刷新按钮 https://github.com/Kuingsmile/PicList/commit/cafb4d590aee30cb2e1315448f05ee99505cf134

**Comment by A5yncX** [comment]
v2.8.0

点击"刷新"没有成功再次获取.

![2024-03-14-17 55 37](https://github.com/Kuingsmile/PicList/assets/54523269/b67fe604-a93d-41a1-8730-8b677107e7e5)

**Comment by A5yncX** [comment]
@Kuingsmile v2.8.0点击"刷新"没有成功再次获取.
![2024-03-14-17 55 37](https://github.com/Kuingsmile/PicList/assets/54523269/af5681a5-f65c-43b4-9495-fc741304e696)

**Comment by Kuingsmile** [comment]
> @Kuingsmile v2.8.0点击"刷新"没有成功再次获取. ![2024-03-14-17 55 37](https://private-user-images.githubusercontent.com/54523269/312789105-af5681a5-f65c-43b4-9495-fc741304e696.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NjcxOTUsIm5iZiI6MTcxMDQ2Njg5NSwicGF0aCI6Ii81NDUyMzI2OS8zMTI3ODkxMDUtYWY1NjgxYTUtZjY1Yy00M2I0LTk0OTUtZmM3NDEzMDRlNjk2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDAxNDEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExZGJkYjBlMTRjYmVjMTM5OWM3YjllNjQ1ODYxMWY3N2ZkNDY1MjczYmZhYWRjOGNkNGZiYTJjYjc0ODExNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SGg84YuzNk0P43LGFHcxX7wskm_6gi18jsMUefIsEsk) [ ![2024-03-14-17 55 37](https://private-user-images.githubusercontent.com/54523269/312789105-af5681a5-f65c-43b4-9495-fc741304e696.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NjcxOTUsIm5iZiI6MTcxMDQ2Njg5NSwicGF0aCI6Ii81NDUyMzI2OS8zMTI3ODkxMDUtYWY1NjgxYTUtZjY1Yy00M2I0LTk0OTUtZmM3NDEzMDRlNjk2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDAxNDEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExZGJkYjBlMTRjYmVjMTM5OWM3YjllNjQ1ODYxMWY3N2ZkNDY1MjczYmZhYWRjOGNkNGZiYTJjYjc0ODExNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SGg84YuzNk0P43LGFHcxX7wskm_6gi18jsMUefIsEsk) ](https://private-user-images.githubusercontent.com/54523269/312789105-af5681a5-f65c-43b4-9495-fc741304e696.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NjcxOTUsIm5iZiI6MTcxMDQ2Njg5NSwicGF0aCI6Ii81NDUyMzI2OS8zMTI3ODkxMDUtYWY1NjgxYTUtZjY1Yy00M2I0LTk0OTUtZmM3NDEzMDRlNjk2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDAxNDEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExZGJkYjBlMTRjYmVjMTM5OWM3YjllNjQ1ODYxMWY3N2ZkNDY1MjczYmZhYWRjOGNkNGZiYTJjYjc0ODExNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SGg84YuzNk0P43LGFHcxX7wskm_6gi18jsMUefIsEsk) [ ](https://private-user-images.githubusercontent.com/54523269/312789105-af5681a5-f65c-43b4-9495-fc741304e696.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NjcxOTUsIm5iZiI6MTcxMDQ2Njg5NSwicGF0aCI6Ii81NDUyMzI2OS8zMTI3ODkxMDUtYWY1NjgxYTUtZjY1Yy00M2I0LTk0OTUtZmM3NDEzMDRlNjk2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDAxNDEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExZGJkYjBlMTRjYmVjMTM5OWM3YjllNjQ1ODYxMWY3N2ZkNDY1MjczYmZhYWRjOGNkNGZiYTJjYjc0ODExNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SGg84YuzNk0P43LGFHcxX7wskm_6gi18jsMUefIsEsk)

我再测试下

**Comment by Kuingsmile** [comment]
![screenshots](https://github.com/Kuingsmile/PicList/assets/96409857/01bad92f-f0c6-4edf-b9dd-85bc25425054)
我这里测试是可以成功获取的呐 你上传下新照片测试下？

**Comment by A5yncX** [comment]
稍等 我现在就测试

**Comment by Kuingsmile** [comment]
> 稍等 我现在就测试

好的 另外可能需要在浏览器确认网址可以正常显示后再刷新测试

**Comment by A5yncX** [comment]
> 好的 另外可能需要在浏览器确认网址可以正常显示后再刷新测试

还是不行, 就是在确认正常后刷新的. 包括在更新最新版本后上传的刷新的依旧不显示.

**Comment by Kuingsmile** [comment]
左下角打开开发者工具，在网络选项卡页面里看一下
![image](https://github.com/Kuingsmile/PicList/assets/96409857/a2a9326c-2a72-493b-b36f-8c486cea26da)
直接上传后打开先是会404报错，浏览器中查看也是404
![image](https://github.com/Kuingsmile/PicList/assets/96409857/5d24ee9d-e370-4b4a-97f0-83771e553587)
等待浏览器中可以访问后，相册内刷新，正常的200状态码
![image](https://github.com/Kuingsmile/PicList/assets/96409857/b2f2e41b-562a-4cd4-89da-4f4eba88540f)

我这边测试结果是这样的，所以请确定下你那边的情况？还有用一张图片试下浏览器内是否可以正常显示

**Comment by A5yncX** [comment]
<img width="735" alt="image" src="https://github.com/Kuingsmile/PicList/assets/54523269/92b1874b-6a98-4f95-8626-e101d0e8511f">

404, 并显示来自磁盘缓存

**Comment by A5yncX** [comment]
> 404, 并显示来自磁盘缓存

在开发者页面手动清理后生效

**Comment by Kuingsmile** [comment]
> > 404, 并显示来自磁盘缓存
> 
> 在开发者页面手动清理后生效

问题应该就是缓存引起的，但不太确定为什么我这边刷新后就可以显示，不需要手动清理
刷新这个功能的实现很简单，就是调用electron的强制无视缓存刷新接口
![image](https://github.com/Kuingsmile/PicList/assets/96409857/f5eb5709-4b0f-48f1-b781-f287bd0e7950)

**Comment by A5yncX** [comment]
我也不是很清楚情况, 现在我这里手动清楚缓存显示图片后在obsidian中依旧没有正常显示, 应该也有ob缓存的问题.

十分感谢老哥,真的很及时. 我先close issue了.

**Comment by Kuingsmile** [comment]
> 我也不是很清楚情况, 现在我这里手动清楚缓存显示图片后在obsidian中依旧没有正常显示, 应该也有ob缓存的问题.
> 
> 十分感谢老哥,真的很及时. 我先close issue了.

obsidian默认的开发者工具快捷键我记得是ctrl+shift+i,所以理论上你去ob打开devtools，用手动清理缓存的方式可以解决ob的问题

**Comment by A5yncX** [comment]
> obsidian默认的开发者工具快捷键我记得是ctrl+shift+i,所以理论上你去ob打开devtools，用手动清理缓存的方式可以解决ob的问题

感谢, mac端是cmd+opt+i. 清理后显示正常了. 我目前还是寻找一下解决方法.
