### ISSUE TITLE
[Feature]: adds support for self-built short link services based on Cloudflare workers

### ISSUE THREAD

**Issue by onlyistranger** [Kuingsmile/PicList#170]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.7.4

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

like [A URL Shortener created using Cloudflare worker](https://github.com/xyTom/Url-Shorten-Worker)

**Comment by Kuingsmile** [comment]
will try, looks good.

**Comment by Kuingsmile** [comment]
supported
