### ISSUE TITLE
[Feature]: 能否在每一次上传时自定义图床？

### ISSUE THREAD

**Issue by ghost** [Kuingsmile/PicList#172]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.7.4

### 系统信息 | System Information

Mac(arm64)

### 功能请求 | Feature request

如题。我在平时使用本地图床管理 Obsidian 的图片，而在整理博客文章时需要将图片上传至 AWS S3。能否添加一个自定义选项，在勾选后，每次上传会弹出一个图床选择窗口，使得每一次上传不必重新打开软件进行改动？非常感谢！

**Comment by Kuingsmile** [comment]
PicList支持通过设置picbed和configName两个URL查询参数来指定上传图床和配置文件。例如： `http://127.0.0.1:36677/upload?picbed=aws-s3&configName=piclist-test` 该配置将会使用aws-s3图床，并且使用piclist-test配置文件。

因此，你可以在obsidian插件的上传接口处通过picbed参数设置为本地图床，然后软件还是维持s3图床即可，这样走obsidian会自动走本地图床，而普通的软件上传还是走s3

进入对应配置的配置界面，有一个上传按钮可以自动复制上传接口api，粘贴到obsidian插件对应设置里就行

@yoghurtlee-thu

**Comment by ghost** [comment]
> PicList支持通过设置picbed和configName两个URL查询参数来指定上传图床和配置文件。例如： `http://127.0.0.1:36677/upload?picbed=aws-s3&configName=piclist-test` 该配置将会使用aws-s3图床，并且使用piclist-test配置文件。
> 
> 因此，你可以在obsidian插件的上传接口处通过picbed参数设置为本地图床，然后软件还是维持s3图床即可，这样走obsidian会自动走本地图床，而普通的软件上传还是走s3
> 
> 进入对应配置的配置界面，有一个上传按钮可以自动复制上传接口api，粘贴到obsidian插件对应设置里就行
> 
> @yoghurtlee-thu

已经解决，非常感谢大神的帮助。
