### ISSUE TITLE
[Bug]: Unriad下Docker版使用图形和命令安装都失败了，无法启动

### ISSUE THREAD

**Issue by OnlyChallgener** [Kuingsmile/PicList#175]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

latest

### 系统信息 | System Information

Linux

### 问题重现 | Bug reproduce

<img width="108" alt="piclist-1" src="https://github.com/Kuingsmile/PicList/assets/24870218/56548ebc-63f6-4681-b25e-7237e352564a">
<img width="1014" alt="piclist-2" src="https://github.com/Kuingsmile/PicList/assets/24870218/de84d169-9687-44fa-8c4c-328fc3a5ce9d">
<img width="572" alt="piclist-3" src="https://github.com/Kuingsmile/PicList/assets/24870218/8eed0c1c-dcaa-4567-86bf-bbd9d6591df8">
<img width="421" alt="piclist-4" src="https://github.com/Kuingsmile/PicList/assets/24870218/7ca74e50-8153-44db-aa17-e070bab69f40">
网上piclist docker版本的安装教程很少，我在Unraid里面用图形方式和命令方式安装都失败了，不知道问题出在哪。要么启动失败，要么启动了WEBUI打不开无法进入操作界面。希望作者大大帮我看一下怎么解决，感谢！

### 相关日志 | Logs

[piclist-log.txt](https://github.com/Kuingsmile/PicList/files/14618276/piclist-log.txt)
日志显示don't support [GET] method

**Comment by Kuingsmile** [comment]
我去了解下unraid是什么哈。。 

另外36677这个接口，是需要post请求，直接网页访问是无法访问的，可以通过postman之类的来调试。这也是为什么日志里显示don't support [GET] method，因为浏览器访问默认是get方法

**Comment by OnlyChallgener** [comment]
这样，那就相当于docker版没有图形界面，可以用Postman修改json参数，调试好可以实现功能吗？Postman的请求网址和请求类型怎么填？谢谢

**Comment by Kuingsmile** [comment]
可以参考文档
https://piclist.cn/advanced.html#%E5%86%85%E7%BD%AEServer%E7%9A%84%E4%BD%BF%E7%94%A8
