### ISSUE TITLE
[Bug]: 上传jpg和GIF格式，会在原有的链接加上对应的 jpg和gif,

### ISSUE THREAD

**Issue by misu198** [Kuingsmile/PicList#177]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.8.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

例如，MJ_Weird_0.jpg 上传后变成 MJ_Weird_0.jpg.jpg

**Comment by Kuingsmile** [comment]
> ### 前置阅读 | Pre-reading
> * [x]  [文档/Doc](https://piclist.cn/)
> * [x]  [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
> * [x]  [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)
> 
> ### PicList的版本 | PicList Version
> 2.8.0
> 
> ### 系统信息 | System Information
> Windows
> 
> ### 问题重现 | Bug reproduce
> 例如，MJ_Weird_0.jpg 上传后变成 MJ_Weird_0.jpg.jpg
> 
> ### 相关日志 | Logs
> _No response_

上传到什么平台 重命名选项是怎么设置的 以及有没有使用什么插件 @misu198

**Comment by misu198** [comment]
使用 Typora 平台，上传到github,具体表现为以下图片， 
![piclist问题1](https://github.com/Kuingsmile/PicList/assets/147276851/44449ccc-fad3-4651-a763-1197ba6ce6f6)
![QQ截图20240324165541](https://github.com/Kuingsmile/PicList/assets/147276851/c709a625-9c8b-4591-b58b-746d79a4d31a)

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/96409857/b5af1f51-17a0-4307-b353-e9e0c48012af)
用了自定义链接功能或者高级重命名么，我在typora里上传到github没有这个问题

**Comment by misu198** [comment]
没有开启 重命名选项，刚才我尝试开启重命名选项，出现以下情况
![](https://raw.githubusercontent.com/misu198/Midjourney/main/guge/202403241704873.png)
设置为以下
![](https://raw.githubusercontent.com/misu198/Midjourney/main/guge/202403241706722.png)

**Comment by misu198** [comment]
自定义链接的话，是默认状态，如下
![](https://raw.githubusercontent.com/misu198/Midjourney/main/guge/202403241707312.png)

**Comment by misu198** [comment]
用过一个加水印的功能，设置如下
![](https://raw.githubusercontent.com/misu198/Midjourney/main/guge/202403241709664.png)
其他的，没有进行设置。

**Comment by Kuingsmile** [comment]
用的自带的github图床？或者还有开其它插件么 只有这些设置的话 不会多出后缀名 我刚才也上传github测试了 是正常的

**Comment by misu198** [comment]
是的，
之前也有上传过，也是没有问题，但是后面的就出现了，
![](https://raw.githubusercontent.com/misu198/Midjourney/main/guge/202403241715511.png)
github设置如下
![](https://raw.githubusercontent.com/misu198/Midjourney/main/guge/202403241714375.png)

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/96409857/e564a1e2-ee58-4682-8295-21d0905a2cf6)
配置没有问题 主要是这两个点之间是否安装了什么插件

**Comment by misu198** [comment]
插件的话，没有使用，如下
![](https://raw.githubusercontent.com/misu198/Midjourney/main/guge/202403241718032.png)
Typora设置，如下
![](https://raw.githubusercontent.com/misu198/Midjourney/main/guge/202403241718537.png)

**Comment by Kuingsmile** [comment]
直接在软件内上传到github也会有这个问题么 不经过typora

**Comment by misu198** [comment]
这个不会出现这个问题，就是我认为，应该是哪里有问题，所以就提了BUG。🤣

**Comment by Kuingsmile** [comment]
> 以就提了B

所以是经过了Typora就会多加一次扩展名，直接软件上传github就没有？

**Comment by misu198** [comment]
不是，是使用着，使用着，就出现这个问题。不然我就不用Typora了。

**Comment by Kuingsmile** [comment]
> 不是，是使用着，使用着，就出现这个问题。不然我就不用Typora了。

我需要确定如果你直接在PicList的主界面里，上传图片到Github上，有没有多加扩展名的问题，好确定排查方向

在这里上传，不通过Typora来用
![image](https://github.com/Kuingsmile/PicList/assets/96409857/b9114786-d411-4f1e-936a-7cfcfd826783)

**Comment by misu198** [comment]
好的，我自己多研究研究看，多谢解答！
