### ISSUE TITLE
[Feature]: Docker 配置环境变量

### ISSUE THREAD

**Issue by muxinxy** [Kuingsmile/PicList#179]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.8.0

### 系统信息 | System Information

Linux

### 功能请求 | Feature request

请问使用Docker部署时能否用环境变量替代配置文件，比如在Render等容器平台部署不支持挂载文件/目录，只能配置环境变量。

**Comment by Kuingsmile** [comment]
> ### 前置阅读 | Pre-reading
> * [x]  [文档/Doc](https://piclist.cn/)
> * [x]  [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
> * [x]  [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)
> 
> ### PicList的版本 | PicList Version
> v2.8.0
> 
> ### 系统信息 | System Information
> Linux
> 
> ### 功能请求 | Feature request
> 请问使用Docker部署时能否用环境变量替代配置文件，比如在Render等容器平台部署不支持挂载文件/目录，只能配置环境变量。

我去render上试试

**Comment by Kuingsmile** [comment]
我在render上试了，这个平台只有收费计划可以进行文件挂载，但piclist-core的配置文件是比较复杂的，不适合通过环境变量传递，因此不考虑该方式
