### ISSUE TITLE
[Feature]: Piclist自身能否实现EasyWebSvr的功能？

### ISSUE THREAD

**Issue by FeiLZX3Km** [Kuingsmile/PicList#180]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.8.0

### 系统信息 | System Information

Windows 11

### 功能请求 | Feature request

[使用PicList和EasyWebSvr搭建本地图床 - Obsidian中文教程 - Obsidian Publish]( https://publish.obsidian.md/chinesehelp/%E4%BD%BF%E7%94%A8PicList%E5%92%8CEasyWebSvr%E6%90%AD%E5%BB%BA%E6%9C%AC%E5%9C%B0%E5%9B%BE%E5%BA%8A )

我根据教程设置了许久，却在浏览器里面打不开图片，直到我把EasyWebSvr打开，图片才正常显示。看样子Piclist目前并不能实现EasyWebSvr能实现的功能。不知未来Piclist能否支持EasyWebSvr的功能，这样系统托盘就不必多挂一个极具年代感的程序了。

**Comment by Kuingsmile** [comment]
可以 这个功能很简单 下个版本就可以加入
