### ISSUE TITLE
[Bug]: webdav在配置坚果云图床时，会自动出现webdav-...-imp格式的一个配置。如下图

### ISSUE THREAD

**Issue by XoYaPeng** [Kuingsmile/PicList#181]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.8.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

webdav在配置坚果云图床时，会自动出现webdav-...-imp格式的一个配置。如下图:
想请教下这个情况正常吗？可能不是一个bug哈，我不懂就问下大佬。最后，大佬做的二次开发很牛啊！赞赞！！
![image](https://github.com/Kuingsmile/PicList/assets/130196652/ee77dde2-ab30-4846-a661-e95a8d99174d)

**Comment by XoYaPeng** [comment]
这个页面也是显示两个配置：
![image](https://github.com/Kuingsmile/PicList/assets/130196652/dfe6956d-9b7f-43ce-b0be-c68d4f58f9db)

**Comment by Kuingsmile** [comment]
先删除多出来的imp结尾的配置，然后关掉管理页面自动导入配置功能试下
![image](https://github.com/Kuingsmile/PicList/assets/96409857/05eeb5ff-af85-4e37-b18c-78cf41a5f252)

**Comment by XoYaPeng** [comment]
@peiyuanix 
真好了啊！谢谢啦！太厉害了大佬！

**Comment by XoYaPeng** [comment]
@Kuingsmile 
我又遇到一个新的问题哈哈，就是同步到坚果云之后，删除本地文件夹图片，在obsidian里只看到灰色的图片。像这样：
![image](https://github.com/Kuingsmile/PicList/assets/130196652/1e41131f-23f1-418c-a2f9-d83b51903f2d)
这怎么解决呢？感觉不是网速的问题。

**Comment by Kuingsmile** [comment]
你直接在浏览器里访问上传后返回的图片链接看下正常么

**Comment by XoYaPeng** [comment]
@Kuingsmile 这个网址吗？是正常的，可以在浏览器打开。
http://dav.jianguoyun.com/dav/PicList-img/2403311630_SJAJ6L3K.png

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/96409857/cd6a827e-c7f3-4bc5-9d2e-29991a40e381)
你这个网址我这边打开需要授权才能看到的，所以你在obsidian里看到的图片加载不出来

**Comment by XoYaPeng** [comment]
@Kuingsmile 噢噢，那我这边授权后还是加载不出来^_^，而且还可以下载。这个有办法解决吗？

**Comment by Kuingsmile** [comment]
> @Kuingsmile 噢噢，那我这边授权后还是加载不出来^_^，而且还可以下载。这个有办法解决吗？

我没有太用过坚果云 建议问下他们客服哈

**Comment by XoYaPeng** [comment]
好的好的，谢谢你，嘿嘿

**Comment by XoYaPeng** [comment]
@Kuingsmile 咨询了坚果云的客服，他们目前也没有计划去改进他们那边的服务，还有办法解决不大佬

**Comment by Kuingsmile** [comment]
> @Kuingsmile 咨询了坚果云的客服，他们目前也没有计划去改进他们那边的服务，还有办法解决不大佬

那就不太清楚了哈

**Comment by XoYaPeng** [comment]
> > @Kuingsmile 咨询了坚果云的客服，他们目前也没有计划去改进他们那边的服务，还有办法解决不大佬
> 
> 那就不太清楚了哈
我找到一个这样的链接，说云盘没有设置公开权限，感觉坚果云也是这样的，不能公开读取。我咨询了他们的客服，说他们有分享权限的一个设置，通过一个链接去分享。这样的话，piclist把这样的一个链接设置上，会不会就能读取了。我猜测哈，不一定可以。毕竟其它的图床公开之后，就会面临数据泄露的危险。

**Comment by Kuingsmile** [comment]
https://github.com/Redns/picgo-plugin-NutStore/issues/3

按这个说法应该是不适合做图床了

**Comment by XoYaPeng** [comment]
@Kuingsmile 好像是哈，确实不适合了。感谢！
