### ISSUE TITLE
[Feature]: 建议在图片处理选项中，增加预设样式的功能

### ISSUE THREAD

**Issue by lzb446703678** [Kuingsmile/PicList#183]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.8.0

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

图片处理功能很好用！
但是有一些文件上传时我希望加水印、压缩、转格式，而有一些则希望保持原图，什么也不做，还有一些则希望只加水印不压缩，等等等等。
简单的说，就是一种样式设置，无法应对所有上传文件的需求。
希望能够提供预设样式的功能，在上传前只需要简单的选择，即可实现图片处理方式的切换。

**Comment by Kuingsmile** [comment]
后续可以考虑

**Comment by Eyion** [comment]
希望作者可以考虑添加对水印透明度设置
