### ISSUE TITLE
[Bug]: 图床链接地址中间总会多一个空格

### ISSUE THREAD

**Issue by FeiLZX3Km** [Kuingsmile/PicList#184]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.8.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

拖拽文件到小窗口后粘贴出来的地址总会偶尔多出一个空格。
![image](https://github.com/Kuingsmile/PicList/assets/21981195/8c4eb56a-afef-4c36-80e1-8d3b9e652fdd)

不知道有什么方法可以排查以确定此问题是否源于piclist自身？
当然我所用的Obsidian里还有一个easytyping的插件，但这种偶尔出现的频率令我认为导致此问题的原因不在于Easytyping而是piclist自身。

**Comment by Kuingsmile** [comment]
参看下出现空格时的上传日志，如果对应日志里没有空格那就不是piclist的问题

**Comment by FeiLZX3Km** [comment]
> 参看下出现空格时的上传日志，如果对应日志里没有空格那就不是piclist的问题

我再研究确定一下。
