### ISSUE TITLE
[Bug]: Docker 镜像内的 Server 代码跟主线不符

### ISSUE THREAD

**Issue by hzj629206** [Kuingsmile/PicList#185]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

Docker v1.8.3

### 系统信息 | System Information

Linux

### 问题重现 | Bug reproduce

1. 用 Docker 部署 PicList，最新的版本为 [v1.8.3](https://hub.docker.com/r/kuingsmile/piclist)
2. 调用 `/upload` 接口返回的结构里面不包含 `fullResult`
3. 查看主线代码是有这个字段的：https://github.com/Kuingsmile/PicList/blob/ae40a1615ecc661745a9511df2b97a298a05812f/src/main/server/routerManager.ts#L145
    <img width="557" alt="image" src="https://github.com/Kuingsmile/PicList/assets/1644620/2ca9dd57-69c0-4413-84b8-6f97305db9a3">

4. 进入容器检查代码发现没有这个字段。`/usr/local/share/.config/yarn/global/node_modules/.bin/picgo-server`
    <img width="614" alt="image" src="https://github.com/Kuingsmile/PicList/assets/1644620/831ce845-3832-41bb-8bf3-2163ddcbe5fa">

我不清楚 Docker 镜像是从哪里构建出来的，请帮忙看一下。

**Comment by Kuingsmile** [comment]
> ### 前置阅读 | Pre-reading
> * [x]  [文档/Doc](https://piclist.cn/)
> * [x]  [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
> * [x]  [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)
> 
> ### PicList的版本 | PicList Version
> Docker v1.8.3
> 
> ### 系统信息 | System Information
> Linux
> 
> ### 问题重现 | Bug reproduce
> 1. 用 Docker 部署 PicList，最新的版本为 [v1.8.3](https://hub.docker.com/r/kuingsmile/piclist)
> 2. 调用 `/upload` 接口返回的结构里面不包含 `fullResult`
> 3. 查看主线代码是有这个字段的：https://github.com/Kuingsmile/PicList/blob/ae40a1615ecc661745a9511df2b97a298a05812f/src/main/server/routerManager.ts#L145
>    
>    <img alt="image" width="557" src="https://private-user-images.githubusercontent.com/1644620/320285881-2ca9dd57-69c0-4413-84b8-6f97305db9a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0OTg5MjEsIm5iZiI6MTcxMjQ5ODYyMSwicGF0aCI6Ii8xNjQ0NjIwLzMyMDI4NTg4MS0yY2E5ZGQ1Ny02OWMwLTQ0MTMtODRiOC02Zjk3MzA1ZGI5YTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDdUMTQwMzQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWMzYWNmNzM3YzY0OTlkYjczOGUyY2YyMDZlNzBmMTU1ODc3ZDQ3ZDYwYWIzMjc2YzNlZjIxMmExZGFhMjhmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IyBTRnT4o_6UsEV2YYMVJ5KxpJ318AXB3vfeiDIB91M">
> 4. 进入容器检查代码发现没有这个字段。`/usr/local/share/.config/yarn/global/node_modules/.bin/picgo-server`
>    <img alt="image" width="614" src="https://private-user-images.githubusercontent.com/1644620/320285728-831ce845-3832-41bb-8bf3-2163ddcbe5fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0OTg5MjEsIm5iZiI6MTcxMjQ5ODYyMSwicGF0aCI6Ii8xNjQ0NjIwLzMyMDI4NTcyOC04MzFjZTg0NS0zODMyLTQxYmItOGJmMy0yMTYzZGRjYmU1ZmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDdUMTQwMzQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTg2NzdlYjNlNjYyODBjNzYzNGVlYjBmMGI4ODZjMzBlMDkyMGI2ZDMzZTNlMmFlYWRhY2FkM2IxYjMwMTBkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.g9azgxFSuAGZ-BZ7zQCv4U094QNNDaHHW62-dY968Ks">
> 
> 我不清楚 Docker 镜像是从哪里构建出来的，请帮忙看一下。
> 
> ### 相关日志 | Logs
> _No response_

fullResult是用来配合PicList的桌面端云删除功能使用的，保存了经过加密的上传时的配置信息。Docker版本的是从https://github.com/Kuingsmile/PicList-Core 构建的，core版本不支持云删除这个功能，所以不会包含fullResult
