### ISSUE TITLE
[Bug]: 配置文件中watermark的大小写问题

### ISSUE THREAD

**Issue by iuxt** [Kuingsmile/PicList#188]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.8.1

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

在系统设置中配置水印，上传的文件没有水印或者水印不对
<img width="1200" alt="image" src="https://github.com/Kuingsmile/PicList/assets/23610854/a265fdac-647a-444d-8aaf-5d3d642161b6">

经过排查， 系统设置中保存后，会在data.json中添加 waterMark 配置， 但真正生效的配置是 watermark 配置， 如图：
<img width="546" alt="image" src="https://github.com/Kuingsmile/PicList/assets/23610854/a54f407c-ccb3-4d5f-8d58-0ed8d69bcdd0">

**Comment by Kuingsmile** [comment]
ok 我知道问题在哪里了 由于问题比较严重 今天会做紧急修复发布新版本
