### ISSUE TITLE
[Feature]: mini窗口贴边隐藏特性&优化问题反馈入口

### ISSUE THREAD

**Issue by FeiLZX3Km** [Kuingsmile/PicList#190]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.8.3

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

一、
![image](https://github.com/Kuingsmile/PicList/assets/21981195/26a002b5-8234-4b3c-84fe-f6528ba2700f)

希望mini窗口增加一个贴边隐藏的特性，在一些场景中，需要全窗口操作，mini窗口需要暂时隐藏。但手动隐藏都是永久性的，之后还要再手动设置显示窗口，太不灵活了。

二、优化问题反馈渠道。
![image](https://github.com/Kuingsmile/PicList/assets/21981195/48e2127f-79c9-4c37-b5d9-85a8e1891b48)

虽然“关于”对话框内有本项目的链接，但不能点击打开。要么手动输入网址到浏览器，要么就自己从另处点击寻找，想在github上反馈问题要费力找半天，要先到打开手册，再在手册页面找到gihub入口，再点issue页面，这种太麻烦了。建议把本项目的issue页面直接放到“关于”对话框上。

**Comment by Kuingsmile** [comment]
第二个问题我直接在左下角那里加个菜单打开Github issue页面，第一个我需要研究下electron的手册，看是否可以实现

**Comment by Kuingsmile** [comment]
第二项已添加至左下角菜单，第一项暂不考虑实现
