### ISSUE TITLE
[Bug]: 在管理里面本地图片为自定义域名开启强制 HTTPS 无效，自定义域名为 http://127.0.0.1:9090/，复制的路径为绝对路径

### ISSUE THREAD

**Issue by jianwu003** [Kuingsmile/PicList#191]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.8.3

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

![image](https://github.com/Kuingsmile/PicList/assets/159551078/e0976241-d799-438b-97a4-b403996105bf)
![image](https://github.com/Kuingsmile/PicList/assets/159551078/1c27c786-5bbf-4d06-8e51-b9bc6eeca2d3)
![PixPin_2024-04-19_23-46-34](https://github.com/Kuingsmile/PicList/assets/159551078/1f543801-1115-437b-b064-f7d449fc83a6)

**Comment by Kuingsmile** [comment]
fixed
