### ISSUE TITLE
[Bug]: AWS S3上传文件后 获取的url有问题

### ISSUE THREAD

**Issue by JinyuZhang** [Kuingsmile/PicList#192]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.8.3

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

使用AWS S3,连接自己搭建的minio服务,设置自定义域名为:https://xx.xx.xx:1443,注意,带自定义端口(家庭宽带443 80 不通), 上传图片后获取的文件连接在每次上传后,都会在自定义域名后面加一个bucket,例如:https://file.xxx.xx:1443/pic/pic/2024/04/838ac89f72cbe59115bf6a6a9cd23401.png, 正确的应该是域名后只有一个/pic(pic是bucket)

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/96409857/83b39dd8-5ac7-4909-b350-11bcc54d6031)
这里怎么设置的

**Comment by Kuingsmile** [comment]
复现出来了 我查下问题在哪

**Comment by Kuingsmile** [comment]
已修复

**Comment by XqhYuyan** [comment]
您好我这里s3 minio URL连接有差异  存在于图床配置(地址正确)和管理配置(地址不正确) 能帮我看一下吗？
![1717250580026](https://github.com/Kuingsmile/PicList/assets/87319224/47ecd388-a75b-4b08-b9c2-0db80332f355)
![1717250200756](https://github.com/Kuingsmile/PicList/assets/87319224/7e240d5e-4909-4b85-8fc3-2032abcbf484)
![1717251361911](https://github.com/Kuingsmile/PicList/assets/87319224/93e8f9dc-36ca-4ac9-9c79-2c100244d143)
![1717250397358](https://github.com/Kuingsmile/PicList/assets/87319224/34d5e7ec-4724-44ee-bddc-fd7e495070db)

这是我的管理s3配置
![1717250200756](https://github.com/Kuingsmile/PicList/assets/87319224/225cc43e-e2d0-4815-b3a4-2ed193dbdf02)

**Comment by XqhYuyan** [comment]
> 已修复
您好，请问这个minio 自定义域名不设置，复制的URL地址是强制上传到他人亚马逊服务器上，还是后台备选的拼接地址不做上传操作？
![1717253177874](https://github.com/Kuingsmile/PicList/assets/87319224/fea1ee0d-7a52-42ed-a866-963753fe4877)

**Comment by Kuingsmile** [comment]
> > 已修复
> > 您好，请问这个minio 自定义域名不设置，复制的URL地址是强制上传到他人亚马逊服务器上，还是后台备选的拼接地址不做上传操作？
> > ![1717253177874](https://private-user-images.githubusercontent.com/87319224/335808805-fea1ee0d-7a52-42ed-a866-963753fe4877.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyOTA3MzksIm5iZiI6MTcxNzI5MDQzOSwicGF0aCI6Ii84NzMxOTIyNC8zMzU4MDg4MDUtZmVhMWVlMGQtN2E1Mi00MmVkLWE4NjYtOTYzNzUzZmU0ODc3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDAxMDcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhZDJjNmViZTA5YTAwNDYyMjhlYzkwNzc2YWIxMjIzNTFiZDY5YmIyMmU0MDAxZWRhMzE1MTQwYjk3YjE0ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wmb_oD3GOBuD5UN8mdoKKBv2VKC6SXxHfBVT9cErIvM)

你不设置自定义域名 就是拼接默认的亚马逊s3 endpoint地址 没有强制上传的说法

**Comment by XqhYuyan** [comment]
理解了，谢谢😊



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年06月02日 09:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Kuingsmile/PicList] [Bug]: AWS S3上传文件后 获取的url有问题 (Issue #192) |

已修复
您好，请问这个minio 自定义域名不设置，复制的URL地址是强制上传到他人亚马逊服务器上，还是后台备选的拼接地址不做上传操作？


你不设置自定义域名 就是拼接默认的亚马逊s3 endpoint地址 没有强制上传的说法
