### ISSUE TITLE
[Bug]: 自定义链接格式貌似是失效的

### ISSUE THREAD

**Issue by rkdawn** [Kuingsmile/PicList#193]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.8.3

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

图床：阿里云图床
复现：我在设置自定义链接的时候发现，无论我怎么更改他就是没有丝毫变动，链接格式都没有变化，于是怀疑是阿里云设置有问题，便去图床管理那单独设置，发现阿里云设置那基本感觉也是不生效的，可能是优先级不够？又或许是摆设，很奇怪的是这些功能貌似和设置是重复的。
![阿里云默认设置](https://github.com/Kuingsmile/PicList/assets/42829652/f5f8e568-10bc-43e8-b8b7-07d372c5af8f)
可以看到右下角的链接内，名字并没有被复制到名字那里
![自定义链接失效](https://github.com/Kuingsmile/PicList/assets/42829652/cd905185-c5d4-483c-80b3-76f184ee08c3)

**Comment by Kuingsmile** [comment]
自定义链接格式是修改复制出来的链接的格式 不是修改链接

**Comment by Kuingsmile** [comment]
左边 下拉修改为自定义链接 custom 默认格式是预设的markdown 

![Screenshot_2024_0422_183600.png](https://github.com/Kuingsmile/PicList/assets/96409857/0eb3fe69-eca2-4af2-a7dd-9658fd9f9d93)

**Comment by rkdawn** [comment]
感谢，已经解决，之前看议题你给别人回复过，我当时试了一下发现右下角显示的是一个单纯的链接，我还以为没有生效，单独复制出来的链接是显示对的 




| |
rkemail
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年4月22日 18:37 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [Kuingsmile/PicList] [Bug]: 自定义链接格式貌似是失效的 (Issue #193) |

Closed #193 as completed.

**Comment by rkdawn** [comment]
感谢，已经解决，之前看议题你给别人回复过，我当时试了一下发现显示的是一个单纯的链接，我还以为没有生效
![QQ截图20240422184556](https://github.com/Kuingsmile/PicList/assets/42829652/02500949-f559-4ff2-8ea1-8dbbb54ee591)
