### ISSUE TITLE
[Bug]: 批量上传图片只会上传其中一张

### ISSUE THREAD

**Issue by rkdawn** [Kuingsmile/PicList#194]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.8.3

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

复现：为了规范统一化，采用的是同一个命名方式
设置好了以后，发现命名规则不一样，于是又碰到了上次遇到的一个问题，批量上传照片，由于时间间隔极短，会导致被命名为同一个照片，就会出现如图所示的问题，如图所示，我同时上传了三张照片，只上传了最后一个照片三次
![20240422_164045](https://github.com/Kuingsmile/PicList/assets/42829652/f03d4b16-af10-4f9b-91f7-1e17eec8ad2e)
我看了下您设置的是下边这种`年月日时分秒`这种应该是不太准确的
![原始时间戳](https://github.com/Kuingsmile/PicList/assets/42829652/166dadeb-daa3-4a66-a733-bd543a364ac1)
我目前正常使用的的是，即`年月日_13位Unix时间戳(豪秒级)`
![13位时间戳](https://github.com/Kuingsmile/PicList/assets/42829652/527d3657-cd00-4da3-a17b-06bf624713e1)

**Comment by Kuingsmile** [comment]
我把时间戳改下毫秒级

**Comment by rkdawn** [comment]
老哥，我刚刚提交的那个关于自定义链还有一个问题，在原问题有回复
内容，改成custom上传图片以后，win10通知栏那只显示纯链接，应该是显示错了

**Comment by Kuingsmile** [comment]
> 老哥，我刚刚提交的那个关于自定义链还有一个问题，在原问题有回复 内容，改成custom上传图片以后，win10通知栏那只显示纯链接，应该是显示错了

设计上通知栏就是只显示纯链接，因为自定义的格式是不可控的，显示出来可能会过长

**Comment by rkdawn** [comment]
> > 老哥，我刚刚提交的那个关于自定义链还有一个问题，在原问题有回复 内容，改成custom上传图片以后，win10通知栏那只显示纯链接，应该是显示错了
> 
> 设计上通知栏就是只显示纯链接，因为自定义的格式是不可控的，显示出来可能会过长

原来如此，明白了
