### ISSUE TITLE
[Feature]: 在docker版本中如何安装插件

### ISSUE THREAD

**Issue by transcendence-x** [Kuingsmile/PicList#195]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

latest

### 系统信息 | System Information

Linux

### 功能请求 | Feature request

在docker版本中 我需要安装 minio插件

**Comment by Kuingsmile** [comment]
docker -it进入命令行 然后picgo install 命令安装插件

**Comment by transcendence-x** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/44899524/91cd8260-fbb1-414d-bfb8-6891fcbe64b1)


报错如下  
/usr/local/bin # picgo install picgo-plugin-minio
': No such file or directory

**Comment by Kuingsmile** [comment]
node /usr/local/bin/picgo install picgo-plugin-minio
