### ISSUE TITLE
[Bug]: 自带S3图床，Minio S3无法上传

### ISSUE THREAD

**Issue by Csrayz** [Kuingsmile/PicList#197]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.8.4

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

当通过https上传图片时，会卡在上传阶段，具体可见日志，后续等待一段时间后超时。
S3服务器为Minio，通过反向代理方式提供https。
已测试api上传、piclist自带管理界面上传，piclist自带S3图床的局域网http方式上传，三种上传方式均成功。
使用https://github.com/Herbertzz/picgo-plugin-minio 插件，v2.3.6成功上传。
已测试https://github.com/wayjam/picgo-plugin-s3 插件，v1.3.6同样无法成功上传。
没有debug日志，无法进一步排差问题。

### 相关日志 | Logs

2024-05-06 15:02:43 [PicList INFO] Before transform 
2024-05-06 15:02:43 [PicList INFO] Transforming... Current transformer is [path] 
2024-05-06 15:02:43 [PicList INFO] Before upload 
2024-05-06 15:02:43 [PicList INFO] beforeUploadPlugins: renameFn running 
2024-05-06 15:02:43 [PicList INFO] Uploading... Current uploader is [aws-s3-plist]

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/96409857/9f1bca99-abb9-45db-a636-423f10076885)
起用这两个选项试下

**Comment by Csrayz** [comment]
> ![image](https://private-user-images.githubusercontent.com/96409857/328105008-9f1bca99-abb9-45db-a636-423f10076885.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5ODE3NjMsIm5iZiI6MTcxNDk4MTQ2MywicGF0aCI6Ii85NjQwOTg1Ny8zMjgxMDUwMDgtOWYxYmNhOTktYWJiOS00NWRiLWE2MzYtNDIzZjEwMDc2ODg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDA3NDQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNmYwYmNhNzE2Njk4YWE5ZTU4MjFhNDM1NmE5MWYxNDQyNjM4MTk3MjJhNDQ2OWQ4YWI3NjgwZjlhYWYxNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w6QJOES9z4xcqO0K_oDA4ucfzon9Fd6xZhYcQWEBj6s) 起用这两个选项试下

目前的配置与图中一致，也尝试过把「拒绝无效TLS证书连接」给关了，也一样超时。

**Comment by Kuingsmile** [comment]
使用minio的那个插件吧 本身内置的aws-s3没有特别针对minio适配 可能是会有问题

**Comment by Csrayz** [comment]
的确，先这样用着吧，算是一个解决方案。

**Comment by ench2** [comment]
怎么配置minio  ?

 InvalidEndpointError: {
  "picBed": {
    "uploader": "minio",
    "current": "minio",
    "minio": {
      "accessKeyId": "KLk0pCEZNn5MWjBuQdcr",
      "accessKeySecret": "**************",
      "bucket": "jutx",
      "path": "",
      "customUrl": "http://192.168.10.80:19000",
      "options": ""
    }
  },
  "picgoPlugins": {
    "picgo-plugin-minio": true
  }
}
我的config这样配置提示少endpoint
Invalid endPoint : undefined
    at new TypedClient (/root/.piclist/node_modules/minio/dist/main/internal/client.js:47:13)
    at new Client (/root/.piclist/node_modules/minio/dist/main/minio.js:67:1)
    at Object.initMinioClient (/root/.piclist/node_modules/picgo-plugin-minio/src/helper.js:71:19)
    at Object.handle (/root/.piclist/node_modules/picgo-plugin-minio/src/index.js:36:20)
    at Gt.doUpload (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:46995)
    at Gt.start (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:45825)
    at async Zr.upload (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:152511)
    at async /usr/local/share/.config/yarn/global/node_modules/piclist/bin/picgo-server:250:22

**Comment by Kuingsmile** [comment]
> 怎么配置minio ?
> 
> InvalidEndpointError: { "picBed": { "uploader": "minio", "current": "minio", "minio": { "accessKeyId": "KLk0pCEZNn5MWjBuQdcr", "accessKeySecret": "**************", "bucket": "jutx", "path": "", "customUrl": "http://192.168.10.80:19000", "options": "" } }, "picgoPlugins": { "picgo-plugin-minio": true } } 我的config这样配置提示少endpoint Invalid endPoint : undefined at new TypedClient (/root/.piclist/node_modules/minio/dist/main/internal/client.js:47:13) at new Client (/root/.piclist/node_modules/minio/dist/main/minio.js:67:1) at Object.initMinioClient (/root/.piclist/node_modules/picgo-plugin-minio/src/helper.js:71:19) at Object.handle (/root/.piclist/node_modules/picgo-plugin-minio/src/index.js:36:20) at Gt.doUpload (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:46995) at Gt.start (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:45825) at async Zr.upload (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:152511) at async /usr/local/share/.config/yarn/global/node_modules/piclist/bin/picgo-server:250:22

你配置里没有写endpoint字段 当然缺少endpoint
