### ISSUE TITLE
[Bug]: 强制https对本地图床生效，但是会重复https

### ISSUE THREAD

**Issue by jianwu003** [Kuingsmile/PicList#198]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.8.4

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

复制连接之后为（本地域名重复）：
`![20240314235237.png](https://127.0.0.1:9090/http:/127.0.0.1:9090/20240314235237.png)`

配置如下：
![image](https://github.com/Kuingsmile/PicList/assets/159551078/89a4b51a-eb3f-4245-a769-7edd576eec3f)
![image](https://github.com/Kuingsmile/PicList/assets/159551078/a0cc5de8-6a41-4491-8fe5-642e33d672e0)

尝试解决：
关闭图二中的强制 https（无效）
去除图一中的自定义域名（无效，显示绝对路径）

**Comment by Kuingsmile** [comment]
无法复现 请提供更多信息

**Comment by jianwu003** [comment]
原因找到了，当时 V2.8.3 强制https对本地图床不生效，测试时在可能的地方都加上了http，删掉这个拼接路径就好了
![image](https://github.com/Kuingsmile/PicList/assets/159551078/6b576c7b-4101-49e3-8b99-0aace98abd2d)
