### ISSUE TITLE
[Bug]: 无法配置 GitHub

### ISSUE THREAD

**Issue by liblaf** [Kuingsmile/PicList#2]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v1.0.0

### 系统信息 | System Information

Linux

### 问题重现 | Bug reproduce

在管理页面, 只有 `配置别名`, `token`, `用户名`, `代理`, `CDN 加速域名` 可以修改, 没有配置 `repo`, `branch`, `path` 的输入框. 我尝试直接修改 `manage.json` 配置文件, 但并没有效果.

**Comment by Kuingsmile** [comment]
> ### 前置阅读 | Pre-reading
> * [x]  [文档/Doc](https://picgo.github.io/PicGo-Doc/)
> * [x]  [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
> * [x]  [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)
> 
> ### PicList的版本 | PicList Version
> v1.0.0
> 
> ### 系统信息 | System Information
> Linux
> 
> ### 问题重现 | Bug reproduce
> 在管理页面, 只有 `配置别名`, `token`, `用户名`, `代理`, `CDN 加速域名` 可以修改, 没有配置 `repo`, `branch`, `path` 的输入框. 我尝试直接修改 `manage.json` 配置文件, 但并没有效果.
> 
> ### 相关日志 | Logs
> _No response_

您的问题我已复现，在没有配置可选参数`代理`的时候，会因为对应参数是undefined导致无法获取仓库列表，已经进行了修正，请参考最新的commit `22bee0b`。

我会在今天上午发布一个V1.01小版本进行修复，感谢反馈。

本身设计时管理页面就是不需要配置repo、branch、path的，使用token可以主动获取到仓库列表和对应的分支列表。
![image](https://user-images.githubusercontent.com/96409857/219519951-742b8e03-e4c6-48db-a76d-2d1c98cf046e.png)


另外，如果是准备单独向github特定位置上传图片的功能，请在`图床设置-Github`里配置，和原PicGo的使用方式一样。
![image](https://user-images.githubusercontent.com/96409857/219518217-dcc1a60f-07ec-42f9-be1a-30ea23f40254.png)

**Comment by Kuingsmile** [comment]
新版本V1.01发布，对应问题修复带出

@liblaf
