### ISSUE TITLE
[Bug]: 自动复制的链接$fileName为空

### ISSUE THREAD

**Issue by akitten-cn** [Kuingsmile/PicList#200]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.8.5

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

![image](https://github.com/Kuingsmile/PicList/assets/43705954/24442e30-344d-4914-86ed-51ae6e536a7c)
上传图片后自动复制的markdown格式中的filename为空
![image](https://github.com/Kuingsmile/PicList/assets/43705954/10fa7a0b-320f-4ee1-858a-82801d7f0207)

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/96409857/240266d5-20fb-4fb1-a9ef-0f126e72db14)
你需要修改链接格式为自定义
