### ISSUE TITLE
[Bug]: 配置文件中的uploader和current,_configName分别代表什么？？

### ISSUE THREAD

**Issue by kyeo-hub** [Kuingsmile/PicList#201]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

piclist-core 1.8.8

### 系统信息 | System Information

Linux

## 第一次配置：
```
{
  "picBed": {
    "uploader": "webdav",
    "current": "webdav",
    "webdav":{
        "_configName": "img_bed",
        "host": "https://XXXXXX/webdav",
        "username": "XXXX",
         "password": "XXXXXXXX",
        "path": "imgbed",
        "webpath": "i",
        "customUrl": "",
        "sslEnabled": true,
        "authType": "basic",
        "options": "",
        },
  },
  "picgoPlugins": {}
}
```
报错：
```
2024-05-23 11:47:12 [PicList WARN] Can't find uploader - webdav, switch to default uploader - smms 
2024-05-23 11:47:12 [PicList INFO] Uploading... Current uploader is [smms]
```
我以为是找不到配置文件，后来下了WIN版的，用WIN版的API才发现WebDav的uploader是‘webdavplist’。
---
## 第二次配置：
```
{
  "picBed": {
    "uploader": "webdavplist",
    "current": "webdavplist",
    "webdavplist":{
        "_configName": "img_bed",
        "host": "https://XXXXXX/webdav",
        "username": "XXXX",
         "password": "XXXXXXXX",
        "path": "imgbed",
        "webpath": "i",
        "customUrl": "",
        "sslEnabled": true,
        "authType": "basic",
        "options": "",
        },
  },
  "picgoPlugins": {}
}
```
报错：
```Error: Can't find webdavplist config```
---
## 第三次配置：
```
{
  "picBed": {
    "uploader": "webdavplist",
    "current": "webdavplist",
    "webdavplist":{
        "_configName": "webdavplist",
        "host": "https://XXXXXX/webdav",
        "username": "XXXX",
         "password": "XXXXXXXX",
        "path": "imgbed",
        "webpath": "i",
        "customUrl": "",
        "sslEnabled": true,
        "authType": "basic",
        "options": "",
        },
  },
  "picgoPlugins": {}
}
```
**这一次成功了！！！**
---
#疑问：
`uploader`和`current`,`_configName`分别代表什么？？我第四行的`webdavplist`能改成自定义的名字吗？

**Comment by Kuingsmile** [comment]
uploader和current 当前图床类型名
_configName在core版本实际并没有作用，删了这个字段都可以，应该是修改图床类型名后没有重启导致的

**Comment by kyeo-hub** [comment]
> uploader和current 当前图床类型名 _configName在core版本实际并没有作用，删了这个字段都可以，应该是修改图床类型名后没有重启导致的
有点明白了，我主要是想在云服务器上部署一个docker版本的piclist链接服务器上的webdav，避免本地部署占用本地计算机资源。为什么webdav的uploader要用‘webdavplist’呢？而且官方文档里面没有写，找了两天才找出来，还特地读了一下源码，虽然不是太懂。

**Comment by Kuingsmile** [comment]
> > uploader和current 当前图床类型名 _configName在core版本实际并没有作用，删了这个字段都可以，应该是修改图床类型名后没有重启导致的
> > 有点明白了，我主要是想在云服务器上部署一个docker版本的piclist链接服务器上的webdav，避免本地部署占用本地计算机资源。为什么webdav的uploader要用‘webdavplist’呢？而且官方文档里面没有写，找了两天才找出来，还特地读了一下源码，虽然不是太懂。

因为有个webdav插件已经把webdav的名字占了

**Comment by kyeo-hub** [comment]
哦，原来是这样。建议官方文档中可以写一下个各个uploader，要不然有的还是真要靠猜。😄

**Comment by Kuingsmile** [comment]
可以，后续会添加说明

**Comment by kyeo-hub** [comment]
感谢，那我关闭了。

**Comment by Kuingsmile** [comment]
> 哦，原来是这样。建议官方文档中可以写一下个各个uploader，要不然有的还是真要靠猜。😄

https://piclist.cn/configformat.html
@kyeo-hub  添加了配置文件结构说明
