### ISSUE TITLE
[Bug]: 无法同步删除云端

### ISSUE THREAD

**Issue by Eyion** [Kuingsmile/PicList#203]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.8.6

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

在软件-图床AWS S3中设置CF的R2作为图床，在软件相册成功删除图片（已开启云端删除功能），但是在R2存储桶中的图片依然存在，看过#88，没找到解决方法
![image](https://github.com/Kuingsmile/PicList/assets/26318038/4e64343d-25dd-44a6-a138-881b6b362212)

### 相关日志 | Logs

![1717133784353](https://github.com/Kuingsmile/PicList/assets/26318038/3f0d6fab-7610-4889-8d62-d9469fbac2c3)

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/96409857/2f989916-c806-419b-a631-5c0642a2df8c)
删除.com后面的部分

**Comment by Eyion** [comment]
> ![image](https://private-user-images.githubusercontent.com/96409857/335473089-2f989916-c806-419b-a631-5c0642a2df8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzg2OTQsIm5iZiI6MTcxNzEzODM5NCwicGF0aCI6Ii85NjQwOTg1Ny8zMzU0NzMwODktMmY5ODk5MTYtYzgwNi00MTliLWE2MzEtNWMwNjQyYTJkZjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA2NTMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNDliOTc2MzAzOWQzNjY1YjMwNWNhODUxY2VjMWYzMzZiMTVhYmYwZmViYWM0ZTAxYmFhMTQzZDM0NjFjMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PGxWU1f05fOc9onrPnO2FGNzjN8sINWIB3vysFs3B8w) 删除.com后面的部分

谢谢，现在可以了。
想把R2的图片按照网站上的“类别/文章标题”分开存放，我试了设置上传路径可以达到效果（ 如a-b/cd/{fullName} ），但每篇文章都要设置1次，请问有无快捷设置和切换的方法

**Comment by Kuingsmile** [comment]
针对这个场景目前没有哦

**Comment by Eyion** [comment]
好吧，万分期待作者考虑一二。
可以实现提前预设，然后有快速切换的方法（比如右下角图标的右键菜单增加入口，类似于V2rayN切换线路，或者快捷键）

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/96409857/4bdf4a4f-e10d-4711-8177-5a7aa863f35d)
现在就有快速切换同一图床不同配置的呀

**Comment by Eyion** [comment]
大意了..没发现😅好像不支持设置快捷键
还有个疑惑（看完手册不太明白），图床和管理，前者是只能添加现有图床（先要在云端建好）并且只能管理1个存储桶，后者能直接新建并管理多个存储桶？后者在哪儿进行自定义域名的设定呢

**Comment by Kuingsmile** [comment]
> 大意了..没发现😅好像不支持设置快捷键 还有个疑惑（看完手册不太明白），图床和管理，前者是只能添加现有图床（先要在云端建好）并且只能管理1个存储桶，后者能直接新建并管理多个存储桶？后者在哪儿进行自定义域名的设定呢

快捷键还不支持 后面会重构下快捷键这个模块

图床的意思是 单一图床 上传和删除功能
管理的功能简单理解就是个云存储浏览和管理器，类似腾讯的cos browser啥的，自定义域名有设置哦 进去管理页面后，左上角的输入框就可以设置
![image](https://github.com/Kuingsmile/PicList/assets/96409857/923ecb6c-4523-40d1-b982-0b79a16e5dd2)

**Comment by Eyion** [comment]
意思理解了，但设置不成功。我将管理的参数设置成图床的一致，进入一片空白
![image](https://github.com/Kuingsmile/PicList/assets/26318038/4a243816-87ab-47dd-887f-dd12d4738a48)
![image](https://github.com/Kuingsmile/PicList/assets/26318038/3c09953e-6679-40b6-b05f-06e9e25f56ba)
![image](https://github.com/Kuingsmile/PicList/assets/26318038/d6fcc94a-4e65-4fbb-8975-447664c853f4)
R2的根API是什么

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/96409857/adff2746-9ca9-4d26-9e07-d3e1a44164ea)

**Comment by Eyion** [comment]
accessKeyld和secretAccesskey需要设置成全部存储桶吗？如图
![image](https://github.com/Kuingsmile/PicList/assets/26318038/6b43d7d1-96fa-4381-bad5-5cc9327d62c1)
管理的endpoint和图床的是同一个？这endpoint是否所有桶都是一样的
从你的截图看，代理要设置成http://127.0.0.1:10080
![image](https://github.com/Kuingsmile/PicList/assets/26318038/a49ab50d-ce95-467b-8cb4-4bb7eb7f3508)

还是空白
![image](https://github.com/Kuingsmile/PicList/assets/26318038/8c2f3f7e-e919-4c74-b2ba-5a3b02152c56)

设置是默认的
![image](https://github.com/Kuingsmile/PicList/assets/26318038/be236239-52bd-4f0e-8289-97c97f93ffdb)

**Comment by Kuingsmile** [comment]
> accessKeyld和secretAccesskey需要设置成全部存储桶吗？如图
> ![image](https://github.com/Kuingsmile/PicList/assets/26318038/6b43d7d1-96fa-4381-bad5-5cc9327d62c1)
> 管理的endpoint和图床的是同一个？这endpoint是否所有桶都是一样的
> 从你的截图看，代理要设置成http://127.0.0.1:10080
> ![image](https://github.com/Kuingsmile/PicList/assets/26318038/a49ab50d-ce95-467b-8cb4-4bb7eb7f3508)
> 
> 还是空白
> ![image](https://github.com/Kuingsmile/PicList/assets/26318038/8c2f3f7e-e919-4c74-b2ba-5a3b02152c56)
> 
> 设置是默认的
> ![image](https://github.com/Kuingsmile/PicList/assets/26318038/be236239-52bd-4f0e-8289-97c97f93ffdb)
> 

代理是我自己电脑开的，你没有开代理的话留空

**Comment by Eyion** [comment]
除了代理这项，其他都配置正确了？
为何打开还是空白的😅
有没有微信群或者Q群？

**Comment by Kuingsmile** [comment]
> 除了代理这项，其他都配置正确了？ 为何打开还是空白的😅 有没有微信群或者Q群？

![image](https://github.com/Kuingsmile/PicList/assets/96409857/5a84ddb0-6187-47af-87eb-84eaecc82a29)
看日志
另外权限需要最高权限
![image](https://github.com/Kuingsmile/PicList/assets/96409857/b05f020c-f24e-4767-8458-d2ff43571c05)

**Comment by Eyion** [comment]
谢谢，解决了，就是权限问题
