### ISSUE TITLE
[Bug]: 管理的若干问题

### ISSUE THREAD

**Issue by Eyion** [Kuingsmile/PicList#204]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.8.6

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

（1）存储桶名和起始目录填与不填有何区别（自测当存储名为M，对应起始目录设为/A-a，上传文件时会在M下新建A-a文件夹，但A-a下还有个/的根目录文件夹）
![image](https://github.com/Kuingsmile/PicList/assets/26318038/fbbb55e4-f5cf-48c6-a9d5-c97db742a55d)
（2）手册介绍管理中可新建存储桶，但未找到方法。有了新建，能删除吗？
（3）管理中上传文件，如何像图床中那样对图片预处理？
（4）搜索文件只能在该文件所在文件夹下进行？

**Comment by Kuingsmile** [comment]
1. 不填就默认进入每个存储桶的根目录，填了根据顺序对应关系进入相应的起始目录
2. 只有腾讯云、阿里云和七牛云支持新建存储桶，s3的后续会增加，删除不会支持，高风险操作
3. 暂时不支持
4. 是的 不然逻辑会乱

**Comment by Kuingsmile** [comment]
https://github.com/Kuingsmile/PicList/commit/226f1704c3bce31d63d9e3c07560edddcfd36499
已添加s3新建存储桶支持，但需要注意的是兼容s3协议的平台很多，各家的实现也有区别，目前测试通过的有亚马逊s3,r2,b2,minio，其它未测试的不保证可用

**Comment by Eyion** [comment]
谢谢。
对于（1），我也是如你所说一样去理解的，但自测发现跟理解的有出入。例如桶名为M，对应起始目录为/A-a，那么图片保存路径是在M/A-a/图片，但实际是M/A-a//图片，在A-a和图片之间多了1层目录/（如1楼图中所示），难道是设置存在问题？

另：处理图片可否加上水印透明度设置? 后面会考虑在管理中加入吗？

**Comment by Kuingsmile** [comment]
无法复现
