### ISSUE TITLE
[Feature]: 没人关心这个文档统计图是咋搞的么？

### ISSUE THREAD

**Issue by Asunfly** [Kuingsmile/PicList#206]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v0.0.1

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

没人关心这个文档统计图是咋搞的么？
![image](https://github.com/Kuingsmile/PicList/assets/34542913/e59def22-0179-4880-a616-e4c1ccb38268)

**Comment by Kuingsmile** [comment]
https://repobeats.axiom.co/
