### ISSUE TITLE
[Bug]: 点击扩展坞图标无法弹出主界面，必须右键选择打开主界面才行

### ISSUE THREAD

**Issue by dqzboy** [Kuingsmile/PicList#207]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.8.6

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

点击扩展坞图标无法弹出主界面，必须右键选择打开主界面才行。看了设置里面也没有找到相关的设置
![Image_2024-06-07_13-18-38](https://github.com/Kuingsmile/PicList/assets/42825450/bc0c12d9-1719-47d7-8ac6-45046fbf8b52)

**Comment by Kuingsmile** [comment]
预设就是这样 mac上默认是静默运行 在桌面右上角有图标显示 打开主窗口通过右键
![image](https://github.com/Kuingsmile/PicList/assets/96409857/305a854a-2218-4780-af9b-d67f46680f67)

**Comment by dqzboy** [comment]
> 预设就是这样 mac上默认是静默运行 在桌面右上角有图标显示 打开主窗口通过右键

好的明白了，这块跟PicGo有点差别哈；感觉必须通过右键去打开，多了一步😄
