### ISSUE TITLE
[Bug]: 已通过brew安装node，软件内仍要求安装nodejs

### ISSUE THREAD

**Issue by wakewon** [Kuingsmile/PicList#21]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.4.208（商店）

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

在插件设置中尝试安装插件，提示要求安装nodejs：
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/40191996/226521927-88295a94-7d1a-4425-b879-d6ce2b48dbc4.png">

> 这里还有一个问题是左边栏和顶部有错位

然而之前已通过homebrew安装过node，在picgo里可以正常安装插件。版本信息：
<img width="585" alt="image" src="https://user-images.githubusercontent.com/40191996/226522408-5602c907-1d5d-4036-8937-d7e3d301f7f1.png">

### 相关日志 | Logs

2023-03-21 12:30:38 [PicList INFO] [PicList Server] is listening at 36677 
2023-03-21 12:32:45 [PicList ERROR] 
------Error Stack Begin------
Error: spawn npm ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
-------Error Stack End------- 
2023-03-21 12:32:45 [PicList ERROR] NPM is not installed 
2023-03-21 12:32:45 [PicList ERROR] 插件安装失败，失败码为-2，错误日志为 
  
2023-03-21 12:33:14 [PicList ERROR] 
------Error Stack Begin------
Error: spawn npm ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
-------Error Stack End------- 
2023-03-21 12:33:14 [PicList ERROR] NPM is not installed 
2023-03-21 12:33:14 [PicList ERROR] 插件安装失败，失败码为-2，错误日志为 
  
2023-03-21 12:33:17 [PicList INFO] [PicList Server] shutdown 
2023-03-21 12:33:22 [PicList INFO] [PicList Server] is listening at 36677 
2023-03-21 12:34:12 [PicList ERROR] 
------Error Stack Begin------
Error: spawn npm ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
-------Error Stack End-------

**Comment by Kuingsmile** [comment]
dev模式下运行可以安装插件，mas打包后不行。初步判断是由于Macos的沙盒机制导致的，正在尝试修复

**Comment by Kuingsmile** [comment]
> ### 前置阅读 | Pre-reading
> * [x]  [文档/Doc](https://picgo.github.io/PicGo-Doc/)
> * [x]  [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
> * [x]  [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)
> 
> ### PicList的版本 | PicList Version
> 1.4.208（商店）
> 
> ### 系统信息 | System Information
> Mac
> 
> ### 问题重现 | Bug reproduce
> 在插件设置中尝试安装插件，提示要求安装nodejs： <img alt="image" width="1016" src="https://user-images.githubusercontent.com/40191996/226521927-88295a94-7d1a-4425-b879-d6ce2b48dbc4.png">
> 
> > 这里还有一个问题是左边栏和顶部有错位
> 
> 然而之前已通过homebrew安装过node，在picgo里可以正常安装插件。版本信息： <img alt="image" width="585" src="https://user-images.githubusercontent.com/40191996/226522408-5602c907-1d5d-4036-8937-d7e3d301f7f1.png">
> 
> ### 相关日志 | Logs
> 2023-03-21 12:30:38 [PicList INFO] [PicList Server] is listening at 36677 2023-03-21 12:32:45 [PicList ERROR] ------Error Stack Begin------ Error: spawn npm ENOENT at ChildProcess._handle.onexit (node:internal/child_process:283:19) at onErrorNT (node:internal/child_process:478:16) at process.processTicksAndRejections (node:internal/process/task_queues:83:21) -------Error Stack End------- 2023-03-21 12:32:45 [PicList ERROR] NPM is not installed 2023-03-21 12:32:45 [PicList ERROR] 插件安装失败，失败码为-2，错误日志为
> 
> 2023-03-21 12:33:14 [PicList ERROR] ------Error Stack Begin------ Error: spawn npm ENOENT at ChildProcess._handle.onexit (node:internal/child_process:283:19) at onErrorNT (node:internal/child_process:478:16) at process.processTicksAndRejections (node:internal/process/task_queues:83:21) -------Error Stack End------- 2023-03-21 12:33:14 [PicList ERROR] NPM is not installed 2023-03-21 12:33:14 [PicList ERROR] 插件安装失败，失败码为-2，错误日志为
> 
> 2023-03-21 12:33:17 [PicList INFO] [PicList Server] shutdown 2023-03-21 12:33:22 [PicList INFO] [PicList Server] is listening at 36677 2023-03-21 12:34:12 [PicList ERROR] ------Error Stack Begin------ Error: spawn npm ENOENT at ChildProcess._handle.onexit (node:internal/child_process:283:19) at onErrorNT (node:internal/child_process:478:16) at process.processTicksAndRejections (node:internal/process/task_queues:83:21) -------Error Stack End-------

我尝试了很多方法 ，但仍然没找到可以在沙盒内执行命令行的方法。。不过我找到了一个曲线救国的办法，安装插件的时候，现在会提示用户手动执行npm命令，我会给出具体的命令，执行完成后，点击已添加软件会自动在设置文件内更新插件信息。

这样起码是可以用的了，就是略繁琐了点。。
@wakewon

**Comment by wakewon** [comment]
> 安装插件的时候，现在会提示用户手动执行npm命令，我会给出具体的命令，执行完成后，点击已添加软件会自动在设置文件内更新插件信息。

确实是一种可行的方法，看起来还是远离MAS保平安了
（不过从release里下载的包也还是有一样的界面问题）

**Comment by Kuingsmile** [comment]
> > 安装插件的时候，现在会提示用户手动执行npm命令，我会给出具体的命令，执行完成后，点击已添加软件会自动在设置文件内更新插件信息。
> 
> 确实是一种可行的方法，看起来还是远离MAS保平安了 （不过从release里下载的包也还是有一样的界面问题）

MAS的sandbox导致很多限制= _ = 
界面问题应该是渲染上的问题，这个后面我修一修

**Comment by Kuingsmile** [comment]
新版本已修复，正在进行app store审核。

**Comment by Kuingsmile** [comment]
>这里还有一个问题是左边栏和顶部有错位

@wakewon  commit [f0daf97](https://github.com/Kuingsmile/PicList/commit/f0daf970287ac31b656fda54d83343163a2e0d86)已修复该问题
