### ISSUE TITLE
[Bug]: Typoa无法上传截图

### ISSUE THREAD

**Issue by LucasDogLiu** [Kuingsmile/PicList#210]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.8.6

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

在Typroa中用电脑截图粘贴或者用打开剪切板粘贴都无法上传，但是在Obsidian中可以
![image](https://github.com/Kuingsmile/PicList/assets/71585474/a2a9d32c-1af7-43ad-a6d3-951fc2f54656)

### 相关日志 | Logs

2024-06-11 10:57:43 [PicList ERROR] read file D:\笔记\XXXX\C:\Users\30413\AppData\Roaming\Typora\typora-user-images\image-20240611105743511.png error

**Comment by Kuingsmile** [comment]
read file D:\笔记\XXXX\C:\Users\30413\AppData\Roaming\Typora\typora-user-images\image-20240611105743511.png error

你这个路径有问题的吧 中间插了个盘符 C:\

![image](https://github.com/Kuingsmile/PicList/assets/96409857/1433375b-407d-451b-af32-d62db6e98227)
不要勾选这个试下

**Comment by LucasDogLiu** [comment]
> read file D:\笔记\XXXX\C:\Users\30413\AppData\Roaming\Typora\typora-user-images\image-20240611105743511.png error
> 
> 你这个路径有问题的吧 中间插了个盘符 C:\
> 
> ![image](https://private-user-images.githubusercontent.com/96409857/338420484-1433375b-407d-451b-af32-d62db6e98227.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNzU4MDIsIm5iZiI6MTcxODA3NTUwMiwicGF0aCI6Ii85NjQwOTg1Ny8zMzg0MjA0ODQtMTQzMzM3NWItNDA3ZC00NTFiLWFmMzItZDYyZGI2ZTk4MjI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDAzMTE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhYTYwZmQyZDgwYjllNWIyMDA0YTA2NzhiYzBkMGIwNmMzMzlhMjk4MWJmMWNjZDBiYTRhMDc5MDRiMmU5YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1QD927l5UHuzI__PloqSEj-rY67Vqlu3m4joN37pJT8) 不要勾选这个试下

好了，可以了，谢谢
