### ISSUE TITLE
[Bug]: 相册里无法删除包含中文名称的历史上传图片

### ISSUE THREAD

**Issue by Tenkodo** [Kuingsmile/PicList#212]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.9.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

相册里面历史上传的图片，只要图片名称包含**中文**，就不能正常删除。
但在管理里面，是可以正常删除的。
>我使用的oss为自建的minio，但是应该跟这个没太大关系。
![c1d5625b-6ff6-47f2-94f7-90fc675d4014](https://github.com/Kuingsmile/PicList/assets/62917736/043421c9-e4aa-402c-8e98-89a75bcf0b9a)

**Comment by Kuingsmile** [comment]
我先测试下

**Comment by Kuingsmile** [comment]
文件名编码的问题 已修复 感谢反馈
