### ISSUE TITLE
[Bug]: 图床设置页面按钮样式问题

### ISSUE THREAD

**Issue by Ray-D-Song** [Kuingsmile/PicList#213]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.9.0

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

<img width="1736" alt="image" src="https://github.com/Kuingsmile/PicList/assets/71577024/95bead10-3450-4142-9481-a9106a8ce209">
最下面的三个按钮样式

**Comment by Kuingsmile** [comment]
会修改下看看

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/96409857/464f8ead-145b-4ca5-a916-0d6eeccf43d8)
我这里打开看起来是正常的

**Comment by Ray-D-Song** [comment]
> ![image](https://private-user-images.githubusercontent.com/96409857/342065708-464f8ead-145b-4ca5-a916-0d6eeccf43d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNDgwMDcsIm5iZiI6MTcxOTE0NzcwNywicGF0aCI6Ii85NjQwOTg1Ny8zNDIwNjU3MDgtNDY0ZjhlYWQtMTQ1Yi00Y2E1LWE5MTYtMGQ2ZWVjY2Y0M2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDEzMDE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmY2Q1ZDc0NWRiN2UzOTkzYTA5NGRjODRiYTVmY2ZjZWE2YzkzOWE4ZWI1Y2FkYjRkZjc2MjFkZDIwNmYwNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NIj9oWvLTmEROVmrLoek9R2uqgomNuc4AaVI277sUXI) 我这里打开看起来是正常的

我也运行了一下开发，是正常的，只有安装release版不正常。
我觉得可以先把这个issue关掉。
