### ISSUE TITLE
[Feature]: 希望能够在图片旁边添加一个快捷打开所在文件夹并且定位所在位置的按钮

### ISSUE THREAD

**Issue by FeiLZX3Km** [Kuingsmile/PicList#214]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.8.5

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

如题。

**Comment by Kuingsmile** [comment]
图片一般都是上传到云平台的 不存在本地路径，如果是源文件的话，打开对应源文件路径好像没有什么作用
