### ISSUE TITLE
[Bug]: Docker上传接口参数指定图床配置?

### ISSUE THREAD

**Issue by alechy** [Kuingsmile/PicList#215]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

Docker

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

1.windows下创建2个webdav上传路径,设置为A,B
2.通过obsidian的image update 设置参数,发现正常运行.
3.拷贝 data.json 到 docker配置文件(config.json)
4.修改obsidian,并上传,发现只能上传到默认的路径.

**Comment by Kuingsmile** [comment]
docker对应的core版本目前不支持设置参数指定图床 后续会尝试重构增加对应功能

**Comment by Kuingsmile** [comment]
https://github.com/Kuingsmile/PicList-Core/releases/tag/v1.8.11

@alechy  试下新版本，需要使用桌面版data.json的配置文件内容，上传接口应该已经支持设置configName参数来指定对应配置了 还有问题欢迎反馈
