### ISSUE TITLE
[Feature]: 上传前手动重命名，文本选择增加对下划线"_"的分词支持

### ISSUE THREAD

**Issue by chenbihao** [Kuingsmile/PicList#216]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

最新

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

目前双击选中的分词规则，对于`-` 、`=`、`+`、`/`、`\` 等均有分词隔断能力

但缺少对下划线 `_` 分词，希望能添加这个分词能力，方便在贴截图时手动重命名文件

![image](https://github.com/Kuingsmile/PicList/assets/21167262/6b94a44b-fe37-4e95-a8e3-0dd937c7a525)

**Comment by Kuingsmile** [comment]
这里的行为不太方便修改 而且应用场景不广，暂时不做修改
