### ISSUE TITLE
[Feature]: 上传图片同时生成小尺寸缩略图

### ISSUE THREAD

**Issue by w1zd** [Kuingsmile/PicList#219]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.9.0

### 系统信息 | System Information

Mac

### 功能请求 | Feature request

Hello, 可不可以考虑下上传图片的同时生成小尺寸缩略图上传？

**Comment by Kuingsmile** [comment]
暂时不考虑哈

**Comment by w1zd** [comment]
好的，谢谢回复

记录下我目前的解决方案，如果有人有需要可以参考。

使用 Github 做图床，可以用 [subic/ghaction-thumbnails](https://github.com/marketplace/actions/thumbnails-generator)，这个 action 会在上传图片之后，自动生成缩略图。
