### ISSUE TITLE
[Bug]: Typora自定义命令行上传验证失败

### ISSUE THREAD

**Issue by WeiViming** [Kuingsmile/PicList#22]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v1.4.3

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

偏好设置 --> 图像 --> 上传服务设定 --> 自定义命令 --> 输入如下命令:
```bash
/Applications/PicList.app/Contents/MacOS/PicList upload
```
点击 验证图片上传选项

提示验证失败(实际上成功了)
<img width="720" alt="image" src="https://user-images.githubusercontent.com/35755899/226631457-b8917dab-0373-49cd-adf9-4f74f268504e.png">

**Comment by Kuingsmile** [comment]
测试了下PicList和PicGo，使用自定义命令都会报错，应该是因为启动的时候有一些默认输出，格式不一致导致的。

如果是为了和Typora配合使用的话，不需要用custom命令，上传服务选`PicGo(app)`，然后PicGo路径填写PicList的安装路径就可以了，完全兼容的。

参考下图，验证也是成功的。
![image](https://user-images.githubusercontent.com/96409857/226635012-a23088ac-a4e2-4f7c-968e-b57befb3876e.png)
![image](https://user-images.githubusercontent.com/96409857/226635278-5e8ea05c-55cf-4078-99f4-9949bf2a5c7f.png)

@WeiViming

**Comment by WeiViming** [comment]
感谢回复! Mac上选PicGo.app是不会显示PicGo路径的, 所以此方法无效. 只能用自定义命令. 如图.
<img width="720" alt="image" src="https://user-images.githubusercontent.com/35755899/226636287-5531311b-0d77-4afd-83c6-04cc10715f4c.png">

**Comment by WeiViming** [comment]
实测虽然设置报错, 但是通过自定义命令设置后点击上传图片是可以正常使用的.

**Comment by Kuingsmile** [comment]
> 点击上传图片是可以正常使用的



> 感谢回复! Mac上选PicGo.app是不会显示PicGo路径的, 所以此方法无效. 只能用自定义命令. 如图. <img alt="image" width="720" src="https://user-images.githubusercontent.com/35755899/226636287-5531311b-0d77-4afd-83c6-04cc10715f4c.png">

soga  我去typora那里留个言看看能给我加进去不 doge~
