### ISSUE TITLE
[Feature]: 请问有支持 CloudFlare 的那个OSS服务的计划吗？ 谢谢

### ISSUE THREAD

**Issue by xiao-nz** [Kuingsmile/PicList#221]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.9.1

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

请问有支持 CloudFlare 的那个OSS服务的计划吗？ 谢谢

**Comment by Kuingsmile** [comment]
R2么 使用Aws s3就可以 兼容的
