### ISSUE TITLE
[Feature]: 支援im.ge

### ISSUE THREAD

**Issue by 2ipm1nd** [Kuingsmile/PicList#224]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.91

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

https://im.ge/

我嘗試使用[picgo-plugin-web-uploader](https://github.com/yuki-xin/picgo-plugin-web-uploader)這個插件設定，但貌似不能用，請問能支援這個免費圖床嗎？感謝

**Comment by Kuingsmile** [comment]
![image](https://github.com/user-attachments/assets/f33d219e-fa42-4d4c-b999-ee588f3ed86b)

@2ipm1nd 参考我这么配置，api key换成你自己的，是可以的

**Comment by 2ipm1nd** [comment]
太感謝了，原來是我設定不對
