### ISSUE TITLE
[Feature]: 一张图片同时上传不同图床

### ISSUE THREAD

**Issue by FeiLZX3Km** [Kuingsmile/PicList#226]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.8.5

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

请问有没有办法一张图片既上传本地图床，又上传第三方图床？
这个出现在本地笔记发布于微信公众号的场景。本地图床的图片微信公众号都拉取失败了。因为在本地图床链接失效的时候，希望微信公众号平台尝试拉取第二个图床的图片。

**Comment by Kuingsmile** [comment]
理论上可以 但需要改底层 我考虑下怎么实现

**Comment by ghost** [comment]
支持。之前曾经试着做过分区域存储的图床。很需要这个功能。

**Comment by Kuingsmile** [comment]
已添加 如下图 完成更多兼容性测试后下个版本发布
![image](https://github.com/user-attachments/assets/29dc27e5-7622-4bc9-9af9-bec6a0977fc4)
