### ISSUE TITLE
[Bug]: Typora + Piclist设置

### ISSUE THREAD

**Issue by wanwe** [Kuingsmile/PicList#229]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.9.1

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

Typora Version 1.9.4 (7260) + 英文版
1）Typora 语言设置成中文的话piclist使用没有问题
2） Typora换成英文之后，piclist选项消失，只能用命令行upload，这个时候Typora里直接paste截图的话，图片可以上传成功但是URL没有更新成图床的URL。不知道是不是和这个validation failed有关系？不确定这是typora的问题还是piclist的问题
validation failed
<img width="502" alt="image" src="https://github.com/user-attachments/assets/cbb58659-e70f-48fd-96fb-6962b819b2b2">

URL没有被替换
<img width="973" alt="image" src="https://github.com/user-attachments/assets/33d4eae2-1a78-4c06-aa1f-faa807e3af39">

7-28 09:44:08 [PicList INFO] detect second instance 
2024-07-28 09:44:08 [PicList INFO] cli -> uploading files from cli /Users/wei/Library/Application Support/typora-user-images/image-20240728094407448.png 
2024-07-28 09:44:08 [PicList INFO] Before transform 
2024-07-28 09:44:08 [PicList INFO] Remove exif info. 
2024-07-28 09:44:08 [PicList INFO] Transforming... Current transformer is [path] 
2024-07-28 09:44:08 [PicList INFO] Before upload 
2024-07-28 09:44:08 [PicList INFO] beforeUploadPlugins: renameFn running 
2024-07-28 09:44:08 [PicList INFO] Uploading... Current uploader is [aws-s3-plist] 
2024-07-28 09:44:08 [PicList SUCCESS] 
https://static.thatwei.com/img/2024/07/image-20240728094407448.png 
·

**Comment by Kuingsmile** [comment]
![image](https://github.com/user-attachments/assets/73c72e88-f608-4cb6-af9a-17ea5ec0ee1f)
根据Typora的说明，使用自定义命令的时候，对返回格式是要求最后几行必须是图片链接，但实际上piclist返回的是json格式，所以上传成功，但是验证错误。

而且切换英文就不显示PicList是有问题的，因为PicList实际上支持英文，但Typora错误标记了PicList为Chinease only，我回去给typora提个Issue。

**Comment by wanwe** [comment]
> 根据Typora的说明，使用自定义命令的时候，对返回格式是要求最后几行必须是图片链接，但实际上piclist返回的是json格式，所以上传成功，但是验证错误。
可以考虑一下加个参数制定是返回json还是一行行的text，可能兼容性更好些？

**Comment by Kuingsmile** [comment]
> > 根据Typora的说明，使用自定义命令的时候，对返回格式是要求最后几行必须是图片链接，但实际上piclist返回的是json格式，所以上传成功，但是验证错误。
> > 可以考虑一下加个参数制定是返回json还是一行行的text，可能兼容性更好些？

我又去看了下 使用cli命令的时候，还有个问题是因为PicList为了避免多个实例共存，所以会自动终止多余的进程，这就导致Typora如果在PicList已经启动的情况下调用cli命令上传，确实可以上传成功，但Typora实际获取不到对应进程的stdout的输出，所以不能正常替换链接。

这个兼容性问题不太好解决的，建议切换Typora切换到中文使用，或者用core版本，或者就软件上传然后粘贴。。

我已经和Typora反馈了英文语言下没有PicList选项的问题，后续看什么时候有fix

**Comment by wanwe** [comment]
@Kuingsmile 好的，多谢！
