### ISSUE TITLE
app启动的时候 访问 talkingdata.net

### ISSUE THREAD

**Issue by toyo2333** [Kuingsmile/PicList#230]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

latest

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

这是集成了统计代码还是什么?

### 相关日志 | Logs

N/A

**Comment by Kuingsmile** [comment]
这个是用来统计的，统计的是上传的耗时，图床的使用频率等，主要用来观察软件性能和相关优化
