### ISSUE TITLE
[Feature]: vs code右键删除后picList相册同步删除

### ISSUE THREAD

**Issue by EastonVoyager** [Kuingsmile/PicList#232]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.9.2

### 系统信息 | System Information

Mac

### 功能请求 | Feature request

vscode插件版本：v1.3.1
macOS：14.4.1
vscode: June 2024 (version 1.91)

目前在vscode右键delete image by piclist后，picList收到通知删除成功（去图床确认确实删除了），但是picList程序里相册图片依然存在。

**Comment by Kuingsmile** [comment]
没有复现哦 我这边测试相册里是同步删除掉的

**Comment by EastonVoyager** [comment]
okay，谢谢回复。
可能是本地环境出现问题了。
下回出现问题后我观察一下日志，不影响使用。
