### ISSUE TITLE
[Bug]: 配置兼容性问题

### ISSUE THREAD

**Issue by toyo2333** [Kuingsmile/PicList#233]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

最新

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

我重装系统之前把data.json 备份出来了，然后重装后，粘贴回去发现不行。

找了下原因 是不是图床名称  aws-s3（旧）aws-s3-plist（新）不兼容 配置文件里是旧名称 我新建的 保存下去是新的名称

**Comment by Kuingsmile** [comment]
aws-s3是插件的图床名 aws-s3-plist是piclist自带的s3上传图床，你需要重新装s3插件

**Comment by toyo2333** [comment]
> aws-s3是插件的图床名 aws-s3-plist是piclist自带的s3上传图床，你需要重新装s3插件

明白了。这次我没装s3。用信息重新填了一次。下次 我还是备份json文件就可以了吧。

相册呢？

我想知道备份到正确姿势是啥？过一段时间可能还会重装系统 

谢谢

**Comment by Kuingsmile** [comment]
相册备份piclist.db和piclist.db.bak文件，配置文件可以直接用同步功能
