### ISSUE TITLE
[Bug]: 更新到2.9.2配置数据全部重置了 怎么找回？

### ISSUE THREAD

**Issue by CrazyJasonwell** [Kuingsmile/PicList#234]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

mac 2.9.2

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

更新到2.9.2配置数据全部重置了 怎么找回？

**Comment by Kuingsmile** [comment]
如果是软件内更新应该不会重置配置数据的，丢失了那就找不回了。。
