### ISSUE TITLE
[Feature]: 添加允许自定义相册获取图片的请求中referer部分的功能（就是让人能获取设置了防盗链的图片）

### ISSUE THREAD

**Issue by lingzs13** [Kuingsmile/PicList#235]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.9.2

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

希望的理由，如果我的图床在cdn部分设置了防盗链就不能在相册中获取那些图片，希望添加自定义referer的功能方便获取那部分图片。

**Comment by Kuingsmile** [comment]
相册里加个设置？

**Comment by lingzs13** [comment]
> 相册里加个设置？

感觉可以，就是到时候那个页面会不会太臃肿了😂？主要看作者您么，毕竟您是作者您觉得这功能不重要不想做这功能都不要紧。

我还去翻了下`picgo`的issues里也有人提过这个东西那边的原作者说是因为相册是通过`<img>`标签实现的加不了我对前端不是很了解是不是真挺难实现的👀？

**Comment by Kuingsmile** [comment]
> > 相册里加个设置？
> 
> 感觉可以，就是到时候那个页面会不会太臃肿了😂？主要看作者您么，毕竟您是作者您觉得这功能不重要不想做这功能都不要紧。
> 
> 我还去翻了下`picgo`的issues里也有人提过这个东西那边的原作者说是因为相册是通过`<img>`标签实现的加不了我对前端不是很了解是不是真挺难实现的👀？

我先看下

**Comment by Kuingsmile** [comment]
测试了一下 修改这个确实很难加进去 暂时先不考虑了
