### ISSUE TITLE
[Bug]: 第二网盘同步上传图片大小异常

### ISSUE THREAD

**Issue by lingzs13** [Kuingsmile/PicList#238]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.9.3

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

两个图片的大小不一致，且第二个图床的图片比第一个图床的图片小（第二个比原图都大了）交换过两个图床的次序也可以复现，排除图床端的压缩导致的问题。使用的图床为杜老师的`兰空图床`和cf的`r2存储桶`

**Comment by Kuingsmile** [comment]
我看下
