### ISSUE TITLE
[Bug]: 开启同步云端删除功能后，无法删除第三方插件上传的图片

### ISSUE THREAD

**Issue by jianwu111** [Kuingsmile/PicList#239]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.9.3

### 系统信息 | System Information

Windows

## 问题描述
复现步骤
1. 开启同步删除云端按钮
2. 相册界面多选选中删除

无法删除第三方插件的图片，哪怕第三方插件已经具有同步删除云端功能

但是以下操作可以成功：
1. 开启同步删除云端按钮
2. 点击图片下的单个删除
<img width="127" alt="1724397320360" src="https://github.com/user-attachments/assets/80c73051-5cc5-49c3-8242-afcc6c97502f">

1. 关闭同步删除云端按钮
2. 相册界面多选选中删除

https://github.com/user-attachments/assets/7f5d9235-f391-4e87-b442-1f085ffe40a9

## 可能的解决方案
- [ ] 通过选中方式（类似“请选择显示的图床”），让支持删除的第三方插件在多选时纳入 PicList 的筛选列表
- [ ] 通过 PicList 的 API

**Comment by Kuingsmile** [comment]
我查一下

**Comment by jianwu111** [comment]
好的，辛苦作者了

**Comment by Kuingsmile** [comment]
@jianwu111 fixed

**Comment by jianwu111** [comment]
> @jianwu111 fixed

收到，非常感谢开发者

**Comment by proteincontent** [comment]
> @jianwu111 fixed

@Kuingsmile 请问，为什么我用bilibili的插件，好像还是无法删除



https://github.com/user-attachments/assets/7409fc60-5b02-47cc-88a0-7ce3563fdacb




https://github.com/user-attachments/assets/66a4e430-ed15-4470-bf83-09b75564ecd2

**Comment by jianwu111** [comment]
> > @jianwu111 fixed
> 
> @Kuingsmile 请问，为什么我用bilibili的插件，好像还是无法删除
> 
> 
> 
> https://github.com/user-attachments/assets/7409fc60-5b02-47cc-88a0-7ce3563fdacb
> 
> 
> 
> 
> https://github.com/user-attachments/assets/66a4e430-ed15-4470-bf83-09b75564ecd2
> 
> 

作者还没发布新版本，再等等

**Comment by proteincontent** [comment]
> > > @jianwu111 fixed
> > 
> > 
> > @Kuingsmile 请问，为什么我用bilibili的插件，好像还是无法删除
> > 
> >   
> >     
> >     
> > 
> >     2024-10-06-15-41-26.mp4
> >     
> >   
> > 
> >   
> > 
> >   
> > 
> > 
> > 
> >   
> >     
> >     
> > 
> >     2024-10-06-16-22-55.mp4
> 
> 作者还没发布新版本，再等等

okok,好的，谢谢
