### ISSUE TITLE
[Bug]: 内置 SFTP 插件，日期占位符没有被转义 

### ISSUE THREAD

**Issue by victorwoo** [Kuingsmile/PicList#240]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.9.3

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

如图设置后，上传时日期占位符没有被转义：
![WX20240827-225958@2x](https://github.com/user-attachments/assets/34614f57-e890-4943-9adf-1d514e7fff5e)
![WX20240827-230101@2x](https://github.com/user-attachments/assets/ab1a5d81-b5d4-45a3-afeb-1dd872f1591f)

在服务器上看到的目录结构是这样：
![WX20240827-225536@2x](https://github.com/user-attachments/assets/f24bd56c-b32f-47dc-aae5-0b7375f4bfe7)

相关的配置片段如下：

```json
  "settings": {
    "shortKey": {
      "picgo:upload": {
        "enable": true,
        "key": "CommandOrControl+Shift+P",
        "name": "upload",
        "label": "QUICK_UPLOAD"
      }
    },
    "server": {
      "port": 36677,
      "host": "0.0.0.0",
      "enable": true
    },
    "isListeningClipboard": false,
    "showUpdateTip": true,
    "manualPageOpen": "browser",
    "deleteCloudFile": true,
    "autoRename": true,
    "uploadNotification": true,
    "rename": true
  },
```

```json
    "sftpplist": {
      "_configName": "Default",
      "_id": "b43d5e7c-e182-4fcd-aa70-5819bc2a6f7a",
      "_createdAt": 1724768800434,
      "_updatedAt": 1724769363235,
      "host": "home.vichamp.com",
      "port": 22,
      "username": "victorwoo",
      "password": "************",
      "privateKey": "",
      "passphrase": "",
      "uploadPath": "/web/fss/{year}/{month}/{fullName}",
      "customUrl": "https://home.vichamp.com:2443",
      "webPath": "/fss/{year}/{month}/{fullName}",
      "fileUser": "",
      "fileMode": "",
      "dirMode": ""
    },
```

配置文件请见附件：
[data.json](https://github.com/user-attachments/files/16764109/data.json)

### 相关日志 | Logs

[piclist.log](https://github.com/user-attachments/files/16764146/piclist.log)

**Comment by Kuingsmile** [comment]
使用高级重命名 不是在sftp的配置里设置

**Comment by victorwoo** [comment]
> 使用高级重命名 不是在sftp的配置里设置

抱歉，找了一遍，没有找到高级重命名在哪儿。能否指点一下？我希望上传时自动传到 `/fss/年/月/` 目录，并且自动将图片文件名改为不重复的文件名。要怎么做？

**Comment by Kuingsmile** [comment]
![image](https://github.com/user-attachments/assets/a4dd758b-7e4b-477a-be39-db1701b68a42)
下面
