### ISSUE TITLE
[Bug]: 同一张图片上传第二图床时随机文件名变化

### ISSUE THREAD

**Issue by Zxis233** [Kuingsmile/PicList#241]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)

### PicList的版本 | PicList Version

v2.9.3

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

在上传设置-高级重命名内配置文件的重命名规则为`{filename}_{Y}{m}{d}_{h}{i}_{random-10}`，并开启“上传到第二图床”。

 - 预期：重命名先于上传发生，因此上传到第一图床和第二图床时`{random-10}`的内容不变
 - 实际情况：上传第二图床时`{random-10}`的内容会被重新生成。

请问这是Bug还是有意为之呢？

**Comment by Kuingsmile** [comment]
两次上传实际上就相当于独立上传了两次，并没有关联性，random命名这个想了下应该是bug？因为这种场景下应该还是保持一致更好，我后续修改下逻辑吧

**Comment by Zxis233** [comment]
> 两次上传实际上就相当于独立上传了两次，并没有关联性，random命名这个想了下应该是bug？因为这种场景下应该还是保持一致更好，我后续修改下逻辑吧

是的是的，我也觉得 :P 期待大佬的修复

**Comment by raymao9** [comment]
请问此问题解决了吗？我这边有个类似的问题。

第一图床设置为 Github，这个没问题
第二图床设置为 R2，我发现要将路径写为 `PicList/{timestamp}.{extName}` 这样才能上传成功，不写占位符不行

其他设置：图片自动重命名为时间戳，没有打开高级重命名，打开第二图床同步上传

然后测试了一个截图。

首先它正常上传到了 Github；
同时也上传到了 R2，但只是 PicList 相册里显示了这是一个相同文件名的图片（被上传了 2 次），但实际上登陆 R2 查看，该图片变成一个没有命名的文件。
