### ISSUE TITLE
[Bug]: 部分图片上传后自动旋转方向了

### ISSUE THREAD

**Issue by tshenjoy** [Kuingsmile/PicList#242]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.9.2

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

![image](https://github.com/user-attachments/assets/411bdf3a-c3c5-418d-883d-9d4df2d267ff)
在图片处理中这些选项都没有打开，但上传的图片在本地是这样
![image](https://github.com/user-attachments/assets/5bc771db-64cd-4d5a-b911-092a1f996a07)
在aliyun是这样
![image](https://github.com/user-attachments/assets/18f7ea85-ceb9-4d8f-8c0f-60b100dcd395)
不是所有的图片都有这种情况，看起来发生的比较随机
不是很清楚原因，望解答

**Comment by jianwu111** [comment]
图片是否有 iOS 的图片，iOS 的图片的 Orientation 默认为 6，放阿里云会被旋转，可以通过 tinypng 压缩去掉原数据就行了
