### ISSUE TITLE
[Bug]: webdav上传链接多一个“/”

### ISSUE THREAD

**Issue by wangweitung** [Kuingsmile/PicList#243]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.9.3

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

![IMG_20240903_145117](https://github.com/user-attachments/assets/79ceb002-cb9f-4bcd-88de-ec024331b864)

上传后，链接如下，会在路径和文件名之间多一个/
```
![](/images//IMG_20240902_145902.jpg)
```

### 相关日志 | Logs

```
2024-09-03 14:26:47 [PicList INFO] Before transform 
2024-09-03 14:26:47 [PicList INFO] Transforming... Current transformer is [path] 
2024-09-03 14:26:47 [PicList INFO] Before upload 
2024-09-03 14:26:47 [PicList INFO] beforeUploadPlugins: renameFn running 
2024-09-03 14:26:47 [PicList INFO] Uploading... Current uploader is [webdavplist] 
2024-09-03 14:26:47 [PicList SUCCESS] 
/images//IMG_20240902_145902.jpg 
```

**Comment by Kuingsmile** [comment]
看下重命名选项相关的设置 应该是与webdav无关

**Comment by wangweitung** [comment]
> 看下重命名选项相关的设置 应该是与webdav无关

![image](https://github.com/user-attachments/assets/f9c66359-52e7-4dab-8c08-69e8f650d341)

如上图，未开启重命名选项。

**Comment by wangweitung** [comment]
感觉应该和【设定网址路径】这个选项有关，貌似是【自定义域名】+/+【设定网址路径】+/+【文件名】
如果【设定网址路径】为空值，它还会加上。所以是2个//
这里可以考虑优化下

**Comment by Kuingsmile** [comment]
我知道问题在哪里了 对'/'或者空字符串的处理问题 我修复下

**Comment by Kuingsmile** [comment]
fixed
