### ISSUE TITLE
[Bug]: 安装了minio插件但是不显示

### ISSUE THREAD

**Issue by lugoing** [Kuingsmile/PicList#244]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.9.3

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

我安通过插件功能尝试安装minio插件，在线安装和手动安装离线包都尝试过。在线安装是失败的，我手动导入插件2.4版本的,提示导入成功。但是在图床列表中，没有minio的选项。请问我是应该如何操作，日志里面看着是各种报错

### 相关日志 | Logs

[piclist.log](https://github.com/user-attachments/files/16845849/piclist.log)

**Comment by Kuingsmile** [comment]
![image](https://github.com/user-attachments/assets/a3fa8747-387b-4095-a2f5-1e53049ceae4)
看着是连不上npm源 软件里修改源地址到淘宝源试下，或者设置插件安装代理也试试
![image](https://github.com/user-attachments/assets/688fa6a2-39b4-46c1-9793-aef60babfb68)

**Comment by lugoing** [comment]
不是的。那个是刚开始运行的时候没有配置代理，在最新的日志里面才是报错的信息。  我配置过代理后，可以下载的，但是都会报错，我尝试去跑了picgo，发现是一样的报错，是不是因为picgo有问题？
![image](https://github.com/user-attachments/assets/2e48d4db-2931-4a1c-a63a-eb80f25bdba2)

**Comment by lugoing** [comment]
已解决，换用了官方镜像地址 https://registry.npmjs.org/  成功下载
