### ISSUE TITLE
[Bug]: 腾讯COS开启极致压缩生成url后缀连接符异常

### ISSUE THREAD

**Issue by PearsSauce** [Kuingsmile/PicList#245]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.9.3

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

如题开启极致压缩上传后的url 会带有专属后缀`imageSlim` Piclist开启后默认生成的url是这样的：https://xx.xx.com/xxx.png&imageSlim， 问题在于`&imageSlim` 官方示例是这样的：API使用示例：
https://test-1250000000.cos.ap-beijing.myqcloud.com/sample.jpg?imageSlim  经过测试也确实是 将连接符`&`改为`?`图片url正常。
![image](https://github.com/user-attachments/assets/9f4db4ee-58c9-4d69-8d5a-6b0d75460e43)

### 相关日志 | Logs

https://xx.xx.com/cc.jpg&imageSlim

**Comment by Kuingsmile** [comment]
好的 我试一下

**Comment by Kuingsmile** [comment]
![image](https://github.com/user-attachments/assets/99f88e46-2e4d-4079-a02b-345b133b7535)
我这里测试是没有问题的 
![image](https://github.com/user-attachments/assets/4f28041b-59c7-4692-9962-2a38802122ff)
源码里会判断是否设置了网址后缀，只有当设置了的时候才会用&连接符

**Comment by PearsSauce** [comment]
自定义网址链接格式这个吗？如果不是请告知我那个地方调整，谢谢。
![image](https://github.com/user-attachments/assets/082159a9-9739-494e-90fa-467f32246252)
![image](https://github.com/user-attachments/assets/745e297c-fe2c-4b8f-8fdf-41d3b84aced3)

**Comment by Kuingsmile** [comment]
![image](https://github.com/user-attachments/assets/90dc1469-8c6e-47f3-b78e-672f55a504f4)
这个

**Comment by PearsSauce** [comment]
是设置了后缀，但https://xxx.xxx.xxx/202409092214845.png/cr&imageSlim 是无法访问的 相反 https://xxx.xxx.xxx/202409092214845.png/cr?imageSlim是可以访问的。有图有真相

![image](https://github.com/user-attachments/assets/f5a09c0f-43dc-4aac-8a8b-71ad7c796300)

![image](https://github.com/user-attachments/assets/41c69ddc-d54c-4222-972c-754107746603)

**Comment by Kuingsmile** [comment]
有后缀的情况一般是自己加 ?xxx这种后缀 ，所以再加后缀要用&连接，这个自己后面加的/cr是什么作用

**Comment by PearsSauce** [comment]
/cr是图片处理的规则，这个后缀是加了水印的

<img width="1200" alt="image" src="https://github.com/user-attachments/assets/ac10c310-8cdf-47b3-ab16-0916876c3410">

**Comment by Kuingsmile** [comment]
那关掉极智压缩，然后后缀设成`/cr?imageslim`就行了,效果一样的
