### ISSUE TITLE
[Bug]: 图片缩略图无法显示

### ISSUE THREAD

**Issue by caolib** [Kuingsmile/PicList#246]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.8.4

### 系统信息 | System Information

Windows

### 管理功能下的相册图片不能正常显示缩略图，但是单击查看大图又能正常显示

![recording](https://github.com/user-attachments/assets/1184dea4-39b8-4c5b-8d65-09d7fd839007)

### 相关日志 | Logs

无错误日志

**Comment by Kuingsmile** [comment]
![image](https://github.com/user-attachments/assets/d2d235e8-b5a5-40da-a692-785756610f28)
打开这个选项

**Comment by caolib** [comment]
可以正常显示了，**感谢！！**
