### ISSUE TITLE
[Bug]: Github云存储管理API上传文件的时候，现在最多只能上传40MB了，以前可以最多100MB

### ISSUE THREAD

**Issue by Timmytimi** [Kuingsmile/PicList#247]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.9.3

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

Github 云存储管理API上传文件的时候，现在经过测试最多只能上传40MB了，以前可以最多100MB
![image](https://github.com/user-attachments/assets/38653f9c-5754-4406-bc3d-c9298f936791)

**Comment by Kuingsmile** [comment]
有日志不 
![image](https://github.com/user-attachments/assets/b30e9eb9-eb17-49c3-8580-a1db5b2df431)
