### ISSUE TITLE
[Bug]: 开启了时间戳自动重命名，但是没生效，用的是docker部署，PicList-Core=1.9.3

### ISSUE THREAD

**Issue by fonto86** [Kuingsmile/PicList#248]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.9.3

### 系统信息 | System Information

Linux

### 问题重现 | Bug reproduce

config.json的关键配置如下：

```json
{
  "settings": {
    "shortKey": {
      "picgo:upload": {
        "enable": true,
        "key": "CommandOrControl+Shift+P",
        "name": "upload",
        "label": "QUICK_UPLOAD"
      }
    },
    "showUpdateTip": false,
    "server": {
      "port": 36677,
      "host": "127.0.0.1",
      "enable": true
    },
    "autoRename": true,
    "autoStart": true
  }
}
```

### 相关日志 | Logs

[PicList Server] is listening at 36677
[PicList Server] get the request from IP: 172.17.0.1
[PicList Server] upload files in list
[PicList INFO]: Before transform
[PicList INFO]: Transforming... Current transformer is [path]
[PicList INFO]: Before upload
[PicList INFO]: Uploading... Current uploader is [tcyun]
[PicList SUCCESS]:
https://xxx.cos.ap-xxx.myqcloud.com/picgo/image.png
[PicList Server] upload result

**Comment by Kuingsmile** [comment]
时间戳重命名是桌面版的功能，实现在桌面程序里，docker版的可以使用高级重命名，然后参考下面的占位符
https://piclist.cn/configure.html#%E4%B8%8A%E4%BC%A0%E8%AE%BE%E7%BD%AE

![image](https://github.com/user-attachments/assets/e235c6bb-a415-48f4-8d94-4ea6e859e510)
