### ISSUE TITLE
[Feature]: 上传文件夹功能

### ISSUE THREAD

**Issue by bilibiliworld** [Kuingsmile/PicList#249]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.9.3

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

我希望能够上传文件夹，效果是在对应存储位置（比如git仓库）创建一个同名文件夹，然后将图片上传到文件夹里，并且生成对应图床链接。这样有助于分类管理，不知道是否已经有这样的功能，我暂时还没有找到。

**Comment by Kuingsmile** [comment]
管理界面里可以上传文件夹
