### ISSUE TITLE
[Feature]: 可以支持视频文件的管理吗？

### ISSUE THREAD

**Issue by Canan666** [Kuingsmile/PicList#25]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.5.1

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

可以支持视频文件的管理吗？

**Comment by Kuingsmile** [comment]
可以详细描述一下具体需求么，目前在管理页面里的话，可以上传下载视频文件，同时也是支持预览播放视频的

**Comment by Kuingsmile** [comment]
由于无后续功能详细描述，暂时关闭该issue
