### ISSUE TITLE
[Feature]: 请求新增Sink短链功能

### ISSUE THREAD

**Issue by onlyistranger** [Kuingsmile/PicList#254]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.9.3

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

希望添加Sink短链功能，和yourls类似。
API文档连接：https://github.com/ccbikai/Sink/blob/master/docs/api.md
请求
```
  POST {domain}/api/link/create
  HEADER authorization: Bearer {TOKEN}
  HEADER content-type: application/json
  BODY  {
          "url": "https://github.com/Kuingsmile/PicList"
        }
```
返回
```
  RESPONSE 201
  BODY  {
          "link": {
            "id": "xpqhaurv5q",
            "url": "https://github.com/Kuingsmile/PicList",
            "slug": "issue14",
            "createdAt": 1718119809,
            "updatedAt": 1718119809
          }
        }
```
短连接为{domain}/{res.data.link.slug}

**Comment by Kuingsmile** [comment]
可以

**Comment by onlyistranger** [comment]
多谢👍👍👍

**Comment by Kuingsmile** [comment]
added
