### ISSUE TITLE
[Bug]: Typora 使用命令上传图片验证失败

### ISSUE THREAD

**Issue by wallleap** [Kuingsmile/PicList#255]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.9.3

### 系统信息 | System Information

Mac(arm64)

## 使用命令

```
/Applications/PicList.app/Contents/MacOS/PicList -upload
```

## 验证

![image](https://github.com/user-attachments/assets/3edeeb6d-32b6-43eb-94bf-e203e9536bcc)

```
错误：
(node:92452) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. (Use `PicList --trace-deprecation ...` to show where the warning was created)
```
是不是需要把 `new Buffer()` 改成 `Buffer.alloc()` 或 `Buffer.allocUnsafe()` 或 `Buffer.from()` 啊

**Comment by Kuingsmile** [comment]
上传到哪个图床

**Comment by wallleap** [comment]
> 上传到哪个图床

上传到的 COS

**Comment by Kuingsmile** [comment]
是在Mac下使用Typora 然后选择的自定义命令？

**Comment by Kuingsmile** [comment]
https://github.com/Kuingsmile/PicList/issues/229 参考下这个

**Comment by wallleap** [comment]
> https://github.com/Kuingsmile/PicList/issues/229 参考下这个

好的 谢谢
