### ISSUE TITLE
[Bug]: 不能转换 HEIC 图片至其他格式

### ISSUE THREAD

**Issue by UnspokenSpell** [Kuingsmile/PicList#259]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.9.4

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

1. 用小米相机拍照（格式选`HEIC`）
2. 用PicList上传到图床
3. 比较哈希，对原文件和图床中的文件
---

如果输入的图片是`HEIC`，那么输出文件的哈希和原文件一致。
而且文件名的后缀发生了变更，导致浏览器无法解析图片。

![image](https://github.com/user-attachments/assets/394c77d4-f7c9-49b0-9c6b-4029c39b1e02)

**Comment by Kuingsmile** [comment]
我看一下

**Comment by Kuingsmile** [comment]
你是不是设置了高级重命名？ 转换后的文件我看没有后缀名呀

**Comment by Kuingsmile** [comment]
fixed in https://github.com/Kuingsmile/PicList-Core/commit/9362aad6f3290bd8db8cbb2a22b40e4c099fb8d7
