### ISSUE TITLE
[Bug]: 关于图片预处理之图片压缩率

### ISSUE THREAD

**Issue by chine0411** [Kuingsmile/PicList#261]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.94

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

当我测试一张大小为11.1Mb的jpg图片，在压缩质量分别为0，50，100进行上穿图片格式转变为webp，发现在0和100时压缩率为60%，50时压缩质量为96%，随后进行下方14组数据测试
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/bey/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/bey/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

压缩质量 | 0 | 0.01 | 0.5 | 0.9 | 1 | 5 | 10 | 15 | 25 | 50 | 75 | 100 | 1
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
原始图片大小 | 11.1 | 11.1 | 11.1 | 11.1 | 11.1 | 11.1 | 11.1 | 11.1 | 11.1 | 11.1 | 11.1 | 11.1 | 14
压缩后图片大小 | 4.4 | 11.18 | 11.18 | 11.18 | 0.161133 | 0.186973 | 0.204287 | 0.219707 | 0.252119 | 0.345117 | 0.477285 | 4.4 | 0.294404
压缩率 | 0.603604 | -0.00721 | -0.00721 | -0.00721 | 0.985484 | 0.983156 | 0.981596 | 0.980207 | 0.977287 | 0.968908 | 0.957001 | 0.603604 | 0.978971

</body>

</html>
有点迷惑了，你会发现当压缩质量为0或者100时，他的压缩率都是60%，甚至可以说当压缩质量从100-1是逐渐压缩，但是0.9999....-0,基本相当于原图。
我不太明白这是怎么一回事，是bug还是？
查询文档，图片压缩方面内容只不过是提了一句，再也找不到其他内容了

**Comment by Kuingsmile** [comment]
这个是调用的sharp包，里面有个压缩率参数，我测试下为什么会有这个情况

**Comment by Kuingsmile** [comment]
@chine0411 
参考sharp包源码，quality这个参数的取值范围是1-100内的正整数，所以0-1不在合理取值内，导致一些奇怪的现象。
![image](https://github.com/user-attachments/assets/90f8f217-e8f2-4bd3-97d4-cb5aa32c6fdc)

然后在这个测试中，其实涉及到两步操作，一个是根据quality进行压缩，一个是格式转化为webp，由于编码算法的不同，单纯的将格式转为webp就会导致图片体积变小。

对一个12.5M的jpg图片，只修改quality进行压缩，结果如下

![image](https://github.com/user-attachments/assets/7dfeda29-08a1-4137-a2a6-a19f49da6270)

![image](https://github.com/user-attachments/assets/6d8f7b5e-b365-403f-8914-9aae11ba95b6)

可以看到修改quality值时，压缩率的变化不是线性的

**Comment by Kuingsmile** [comment]
这里会修改下设置界面 要求quality必须为1-100之间的正整数 避免误用
