### ISSUE TITLE
[Bug]: fnm 安装的node,软件无法识别，日志输出乱码 

### ISSUE THREAD

**Issue by zihanla** [Kuingsmile/PicList#262]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.94

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

win11,使用fnm(类似nvm) 安装的nodejs，cmd、powershell均可用，软件无法检测到nodejs，输出日志乱码，离线安装导入不能安装

**Comment by Kuingsmile** [comment]
我测试下 我用nvm安装的是可以的

**Comment by Kuingsmile** [comment]
![image](https://github.com/user-attachments/assets/48f79916-8367-40ae-b314-e6f0ec2bec7f)
有按这个添加么
