### ISSUE TITLE
[Bug]: 图床管理-S3（cloudflare R2），点击下载没反应

### ISSUE THREAD

**Issue by fishhh666** [Kuingsmile/PicList#264]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

最新2.9.4

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

在图床管理中通过「S3兼容」添加R2后，已经能成功看到所有层级，包括桶、文件夹和图片。复制链接也是正常的。但是无法下载。（API是最高的管理员读写权限。）

- 全选文件夹后点击上方的下载按钮，没反应。
- 点击单个文件夹下方的下载，并跳提示「确定要下载该文件夹吗?」选择确定，则会自动打开下载页面并秒跳提示「获取下载列表成功」，但实际并未建立任何下载任务。
- 全程没有错误提示。

PS：文档中可以说下需要管理员读写权限才能正常显示桶和图床中的内容。还好issue中有人提了才知道。

**Comment by Kuingsmile** [comment]
设定下载目录有个bug 前两天的提交里刚处理掉 下个版本会修复
