### ISSUE TITLE
[Feature]: 图片管理预览使用preSinURL

### ISSUE THREAD

**Issue by markbang** [Kuingsmile/PicList#265]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.9.4

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

管理功能设置如果是不允许公共访问的S3云，例如r2就无法预览链接，需要改为预签名链接才可以访问。希望增加一个功能可以使用预签名链接来预览。

**Comment by Kuingsmile** [comment]
added
