### ISSUE TITLE
[Bug]: 插件搜索不到

### ISSUE THREAD

**Issue by coderluojz** [Kuingsmile/PicList#269]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.9.5

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

![image](https://github.com/user-attachments/assets/59651435-03e1-4da3-9bbb-355845a0f344)

插件列表的所有插件都搜索不到

### 相关日志 | Logs

无

**Comment by Kuingsmile** [comment]
npm的仓库查询接口改了 而且目前返回的查询结果也有问题

**Comment by coderluojz** [comment]
> npm的仓库查询接口改了 而且目前返回的查询结果也有问题

怎么解决呢

**Comment by Kuingsmile** [comment]
> > npm的仓库查询接口改了 而且目前返回的查询结果也有问题
> 
> 怎么解决呢

接口返回参数的问题好解决，但目前返回的数据会出现很多不相关的结果 这个我还要看下什么情况

**Comment by coderluojz** [comment]
> > > npm的仓库查询接口改了 而且目前返回的查询结果也有问题
> > 
> > 
> > 怎么解决呢
> 
> 接口返回参数的问题好解决，但目前返回的数据会出现很多不相关的结果 这个我还要看下什么情况

好的

**Comment by Kuingsmile** [comment]
先修复了下查不到的问题 返回结果偏多的可能还要跟踪看一下 但不太影响使用
