### ISSUE TITLE
[Feature]: 针对Obsidian，添加图片预处理功能

### ISSUE THREAD

**Issue by 2019YKL** [Kuingsmile/PicList#27]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.5.2

### 系统信息 | System Information

Windows 11 专业版

### 功能请求 | Feature request

obsidian默认语法支持对图片的预览大小进行调整，具体格式如下

```md
![image|px]()
```

其中Px为尺寸大小。这在图片默认填充全屏的特定主题下非常实用。

目前的Picgo重命名功能无法实现自动添加并无弹窗提醒。

希望在重命名这方面添加默认尺寸后缀。

效果预览：

![image](https://user-images.githubusercontent.com/51532948/228403605-7b62b84b-a25a-42ee-bb39-7a3bff2a0765.png)

**Comment by Kuingsmile** [comment]
你好，这个功能实现的话，需要修改image auto upload plugin这个插件才可以，该插件只从piclist的上传接口获取了上传后的图片url链接的值，文件名是插件内自行添加的。

如果是使用粘贴板上传的话，该插件内由下方图片内的这一行函数获取文件名，然后拼接出markdown的图片链接，可以看到，默认文件名就是image.png。

所以如果想实现，请去[https://github.com/renmu123/obsidian-image-auto-upload-plugin](https://github.com/renmu123/obsidian-image-auto-upload-plugin)提交issue哈

我也会尝试修改一下给该插件提交个Pull Request~，不过可能不会很快，我接下来要去旅个游啦
@2019YKL 

![image](https://user-images.githubusercontent.com/96409857/228413988-f15c8842-1673-470e-a681-bb61dd2ea403.png)
![image](https://user-images.githubusercontent.com/96409857/228414073-20ce4ee7-3d54-4d8e-81f2-020d5f2b7970.png)

**Comment by 2019YKL** [comment]
> 

非常感谢您的耐心解答~ 期待PicList越做越好！

**Comment by Kuingsmile** [comment]
> > 
> 
> 非常感谢您的耐心解答~ 期待PicList越做越好！

[main.zip](https://github.com/Kuingsmile/PicList/files/11096123/main.zip)
![image](https://user-images.githubusercontent.com/96409857/228416392-e7bd071e-2feb-4610-9ca8-55492ecaec82.png)

我已完成了插件的修改，请下载`main.zip`文件，解压后得到`main.js`，然后复制到`你的Obsidian仓库路径/.obsidian/plugins/obsidian-image-auto-upload-plugin`目录下，替换原来的main.js就可以了
@2019YKL

**Comment by Kuingsmile** [comment]
此外，该功能也已PR到原插件仓库，但需要等待审核和合并
