### ISSUE TITLE
[Bug]: Alist的设置上传路径不能用变量例如images/{fullName}

### ISSUE THREAD

**Issue by muzhi1991** [Kuingsmile/PicList#270]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.9.5

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

<img width="1014" alt="image" src="https://github.com/user-attachments/assets/fc8ebecc-4486-4846-8a3d-2bb85603fa99">

**Comment by Kuingsmile** [comment]
使用高级重命名设置
![image](https://github.com/user-attachments/assets/37dd527d-06c9-49d9-943d-ae37ef5ccd28)

**Comment by muzhi1991** [comment]
赞！补充一个问题，就是，就是我看用 alist 上传之后的 url 都是 `https://host.com/d/custom_path/xxx.jpg?sign=xxxx`，即使我设置了"设置自定义域名" “设定网站路径“ 这些也不能改变这个结构，目测是 这些是通过alist 访问需要的信息。我想要的链接格式其实就是简单自定义的域名+文件名，例如 `https://host.com/custom_path/xxx.jpg`，（我有个简单的 静态服务器提供图片的get 服务了）这有办法实现吗？感谢！

**Comment by Kuingsmile** [comment]
> 赞！补充一个问题，就是，就是我看用 alist 上传之后的 url 都是 `https://host.com/d/custom_path/xxx.jpg?sign=xxxx`，即使我设置了"设置自定义域名" “设定网站路径“ 这些也不能改变这个结构，目测是 这些是通过alist 访问需要的信息。我想要的链接格式其实就是简单自定义的域名+文件名，例如 `https://host.com/custom_path/xxx.jpg`，（我有个简单的 静态服务器提供图片的get 服务了）这有办法实现吗？感谢！

这个要去你的alist网站的存储设置里把签名这个选项关掉，关掉之后接口返回的sign是空的话链接里就不会去拼接了
