### ISSUE TITLE
[Bug]: 2.9.6启动报错

### ISSUE THREAD

**Issue by ZiGmaX809** [Kuingsmile/PicList#271]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.9.6

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

升级后启动报错，回滚2.9.5正常

### 相关日志 | Logs

**A JavaScript error occurred in the main process**

Uncaught Exception:
Error: 
Something went wrong installing the "sharp" module

dlopen(/Applications/PicList.app/Contents/Resources/app.asar.unpacked/node_modules/sharp/build/Release/sharp-darwin-x64.node, 0x0001): Library not loaded: @rpath/libvips-cpp.42.dylib
Referenced from: <8D033380-CA2C-3909-BB25-D901E6321665> /Applications/PicList.app/Contents/Resources/app.asar.unpacked/node_modules/sharp/build/Release/sharp-darwin-x64.node
Reason: tried: '/Applications/PicList.app/Contents/Resources/app.asar.unpacked/node_modules/sharp/build/Release/../.././vendor/8.14.2/darwin-x64/lib/libvips-cpp.42.dylib' (no such file), '/Applications/PicList.app/Contents/Resources/app.asar.unpacked/node_modules/sharp/build/Release/../.././vendor/8.14.2/darwin-x64/lib/libvips-cpp.42.dylib' (no such file), '/Applications/PicList.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libvips-cpp.42.dylib' (no such file), '/Applications/PicList.app/Contents/Frameworks/libvips-cpp.42.dylib' (no such file), '/usr/local/lib/libvips-cpp.42.dylib' (no such file), '/usr/lib/libvips-cpp.42.dylib' (no such file, not in dyld cache)

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current darwin-x64 runtime: "npm install --platform=darwin --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
at Object.<anonymous> (/Applications/PicList.app/Contents/Resources/app.asar/node_modules/sharp/lib/sharp.js:37:9)
at Module._compile (node:internal/modules/cjs/loader:1141:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
at Module.load (node:internal/modules/cjs/loader:1011:32)
at Module._load (node:internal/modules/cjs/loader:846:12)
at f._load (node:electron/js2c/asar_bundle:2:13377)
at Module.require (node:internal/modules/cjs/loader:1035:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous> (/Applications/PicList.app/Contents/Resources/app.asar/node_modules/sharp/lib/constructor.js:11:1)
at Module._compile (node:internal/modules/cjs/loader:1141:14)

**Comment by Kuingsmile** [comment]
@ZiGmaX809 

之前action打包用的macos-12镜像废弃了，换了macos-14，但macos-14默认是arm64架构导致的问题

我换macos-13重新打包了，麻烦大概半小时到一个小时后重新更新到2.9.6试下

https://github.com/actions/runner-images?tab=readme-ov-file#available-images

**Comment by ZiGmaX809** [comment]
> @ZiGmaX809 
> 
> 
> 
> 之前action打包用的macos-12镜像废弃了，换了macos-14，但macos-14默认是arm64架构导致的问题
> 
> 
> 
> 我换macos-13重新打包了，麻烦大概半小时到一个小时后重新更新到2.9.6试下
> 
> 
> 
> https://github.com/actions/runner-images?tab=readme-ov-file#available-images

辛苦啦，下班回家了，测试新版要明天啦

**Comment by Kuingsmile** [comment]
打包好了

**Comment by Kuingsmile** [comment]
> > @ZiGmaX809
> > 之前action打包用的macos-12镜像废弃了，换了macos-14，但macos-14默认是arm64架构导致的问题
> > 我换macos-13重新打包了，麻烦大概半小时到一个小时后重新更新到2.9.6试下
> > https://github.com/actions/runner-images?tab=readme-ov-file#available-images
> 
> 辛苦啦，下班回家了，测试新版要明天啦

@ZiGmaX809 麻烦兄弟测试下哈 我没有mac的电脑

**Comment by Kuingsmile** [comment]
我虚拟机上试了下没问题

**Comment by ZiGmaX809** [comment]
> 我虚拟机上试了下没问题

没有问题
