### ISSUE TITLE
[Feature]: 管理界面复制时自动填写custom url并拼接url

### ISSUE THREAD

**Issue by ArthurGXY** [Kuingsmile/PicList#272]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.9.6

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

现状：使用自定义AWS S3源的时候需要在管理界面左上角 手动填写 custom url，且必须填写带bucket，否则将复制默认的官方s3 url。这使得使用本软件有些多余（毕竟就差个文件名我就自己写完了整个url）
期望：能直接调用定义储存源时填写的custom url来填写这个字段，并拼接当前选择的图片的bucket名称，使得复制时除非特殊需求不需要修改此字段。

**Comment by Kuingsmile** [comment]
我看下

**Comment by Kuingsmile** [comment]
![image](https://github.com/user-attachments/assets/341d4c2b-262e-47a6-b145-80b4a210f7df)
目前左上角的自定义url是填写一次后自动保存的，即使在定义存储设置时填写这个字段也是需要写完整个url，其实没有区别。
