### ISSUE TITLE
[Feature]: 软件重装后，相册界面是否可以恢复之前上传过的图片及是否可以增加相册数据备份功能

### ISSUE THREAD

**Issue by snoweer** [Kuingsmile/PicList#273]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.9.6

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

如题，软件重装后，在相册界面中是否可以之前上传的图片？虽然在管理界面中可以进入历史上传的图床目录进行管理和外链的复制，但是无法实现短链和cdn加速的自定义链接等功能。是否可以做个一键导入相册的功能？

**Comment by Kuingsmile** [comment]
重装之前拷贝配置文件目录下的`piclist.db`和`piclist.bak.db`文件，然后重新安装后覆盖对应文件就会恢复相册

**Comment by snoweer** [comment]
谢谢，刚又去查看了closed issue，发现有人问过了，您也回复过了。给您添麻烦了。
我去这个目录看了一下，这2个文件可以在软件的 【设置-同步与配置】 中增加在【上传下载配置文件】中吗？

**Comment by Kuingsmile** [comment]
最好不放里面 因为相册合并不像配置合并 会出问题 而且使用频率很低

**Comment by snoweer** [comment]
好的，谢谢了。
