### ISSUE TITLE
[Feature]: server上传图片时能否增加自定义文件名的功能，这样在不同应用中直接调用本地erve即可。

### ISSUE THREAD

**Issue by iiwenwen** [Kuingsmile/PicList#274]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.9.5

### 系统信息 | System Information

Mac

### 功能请求 | Feature request

比如我使用eagle管理图片，我希望获使用eagle的文件id作为文件名，编写一个eagle插件，调用本地的piclist-server上传图片并且重命名文件，在文档里面我发先只有上传时只有配置文件和图床名的参数，没有上传文件名的参数。

**Comment by Kuingsmile** [comment]
默认是使用传递进来的文件的文件名，建议插件可以上传前用文件id保存个对应名字的临时文件用于上传
