### ISSUE TITLE
[Bug]: 使用高级自定义图床功能的自定义前缀未成功增加

### ISSUE THREAD

**Issue by EVAyo** [Kuingsmile/PicList#280]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.9.6

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

使用了 https://github.com/MarSeventh/CloudFlare-ImgBed 的api功能部分，由于其返回url只是路径并不能返回host，需要额外增加，在配置内进行了设置自定义前缀，上传图片后的返回依然是原始信息
![api返回体](https://github.com/user-attachments/assets/6f5f84cc-f32e-4528-b2bd-ac5345a5cae5)
![配置截图](https://github.com/user-attachments/assets/831d291f-55ea-4927-abec-38d170ff94ed)
![实际url](https://github.com/user-attachments/assets/f11e64c6-ab56-489f-a959-ec98074ffe2c)

**Comment by Kuingsmile** [comment]
我测试下

**Comment by Kuingsmile** [comment]
@EVAyo 
fixed in https://github.com/Kuingsmile/PicList-Core/commit/4a58a8936c099dadc397f63e80e82663ee102b33
