### ISSUE TITLE
[Bug]: 在obisidian 删除图片 和 相册删除图片后，云端图片没有删除，提示：云端删除成功

### ISSUE THREAD

**Issue by domytest** [Kuingsmile/PicList#283]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.9.6

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

1. 首先发现问题：在obisidian 删除图片 ，云端图片没有删除，提示：云端删除成功
2.  单独使用piclist上传图片，使用相册删除图片后，提示：云端删除成功，但是查云端图片没有删除
3. 

### 相关日志 | Logs

![image](https://github.com/user-attachments/assets/f28e7033-f868-4ffa-8b5d-0918d97ffbfa)
查log 只有3个请求？

**Comment by domytest** [comment]
补充：使用的cloudflare r2, aws s3 接口

**Comment by Kuingsmile** [comment]
使用的api key有对应权限么

**Comment by Kuingsmile** [comment]
我测试了R2+aws s3 删除是没有问题的，另外删除是在后台主进程完成的，控制台里是看不到请求的

**Comment by Kuingsmile** [comment]
obsidian+R2+awss3我也试了下，可以正常在云端删除
