### ISSUE TITLE
[Bug]: AppImage包启动失败

### ISSUE THREAD

**Issue by mengzyou** [Kuingsmile/PicList#29]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.5.3

### 系统信息 | System Information

Linux

### 问题重现 | Bug reproduce

```shell
mengz@linux-dev💻~/Downloads 
❯ chmod +x PicList-1.5.3.AppImage 

mengz@linux-dev💻~/Downloads 
❯ ./PicList-1.5.3.AppImage
```

操作系统信息：  

```
❯ cat /etc/os-release 
NAME="openSUSE Leap"
VERSION="15.4"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.4"
PRETTY_NAME="openSUSE Leap 15.4"
```

### 相关日志 | Logs

```
2023-03-30 14:49:28 [PicList ERROR] 
------Error Stack Begin------
Error: 
Something went wrong installing the "sharp" module

libvips-cpp.so.42: æ æ³æå¼å±äº«å¯¹è±¡æä»¶: æ²¡æé£ä¸ªæä»¶æçå½

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current linux-x64 runtime: "npm install --platform=linux --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/tmp/.mount_PicLislhDdKs/resources/app.asar/node_modules/sharp/lib/sharp.js:34:9)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/tmp/.mount_PicLislhDdKs/resources/app.asar/node_modules/sharp/lib/constructor.js:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
-------Error Stack End-------
```

**Comment by Kuingsmile** [comment]
看着是依赖的sharp安装出错导致的

请先试一下执行这两行命令后再安装
```
npm config set sharp_binary_host "https://npmmirror.com/mirrors/sharp"
npm config set sharp_libvips_binary_host "https://npmmirror.com/mirrors/sharp-libvips"
```
我最近外出旅游 反馈可能不会很快 见谅哈

**Comment by Kuingsmile** [comment]
![Screenshot_2023_0330_222021.png](https://user-images.githubusercontent.com/96409857/228866684-6ad1b454-d010-40e7-b7e0-697e2a28a7a0.png)

这是sharp需要的环境，可以看下符合么，现在的打包流程linux安装包应该是只内置了x64版本的sharp，如果是arm64的可能会有问题

还一个是您提供的报错日志里，libvips-cpp.so.42后面那串乱码具体是什么…

**Comment by Kuingsmile** [comment]
@mengzyou 你好，您反馈的问题我已经在centos系统上进行了复现，同时您贴出的log里
`libvips-cpp.so.42: æ æ³æå¼å±äº«å¯¹è±¡æä»¶: æ²¡æé£ä¸ªæä»¶æçå½`
这行乱码应该是
`libvips-cpp.so.42: cannot open shared object file: No such file or directory`

定位问题来自于依赖的`sharp`这个包打包设置有问题，问题的具体情况和解决方案可以参考
https://github.com/electron-userland/electron-builder/issues/6200

简单来说，是由于linux无法从asar压缩包中获取到sharp的依赖库，通过修改打包设置为：
```json
 "linux": {
         "asarUnpack": [
             "**/node_modules/sharp/**"
         ]
     },
```
该问题已解决，在我自己的linux上测试已经可以正常安装了。
目前，我已经将V1.5.3版本的github release中的下载文件，和加速链接中的下载文件都更新为了重新打包后的安装包，请重新下载安装。
https://github.com/Kuingsmile/PicList/releases/download/v1.5.3/PicList-1.5.3.AppImage

如果还有其它任何问题，欢迎及时反馈。

**Comment by mengzyou** [comment]
@Kuingsmile 棒！提醒以下，snap的包有一样的问题，估计也需要重新打包。

**Comment by Kuingsmile** [comment]
> @Kuingsmile 棒！提醒以下，snap的包有一样的问题，估计也需要重新打包。

感谢提醒哈
