### ISSUE TITLE
增加对chevereto图床的支持

### ISSUE THREAD

**Issue by bingood** [Kuingsmile/PicList#30]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.5.3

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

chevereto图床无法删除云端图片，希望增加对chevereto图床的支持。

**Comment by Kuingsmile** [comment]
下个版本我看下哈

**Comment by Kuingsmile** [comment]
@bingood  chevereto目前没有提供删除接口，因此无法实现云删除功能
![image](https://user-images.githubusercontent.com/96409857/230385690-c044cd74-d05d-4324-904a-13287f4f635d.png)
