### ISSUE TITLE
[Bug]: Menubar中的小窗，点击图片，弹出系统提醒说是已经复制了地址，实际上没有复制

### ISSUE THREAD

**Issue by mobilestack** [Kuingsmile/PicList#32]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.6.0

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

。。。

### 相关日志 | Logs

没有报错

**Comment by mobilestack** [comment]
但是粘贴图片到obsidian，则会成功复制到网址

**Comment by mobilestack** [comment]
还有，在本地相册中的复制文件名地址，也没有生效。但是在云端相册管理里面的复制，是生效的

**Comment by Kuingsmile** [comment]
> 还有，在本地相册中的复制文件名地址，也没有生效。但是在云端相册管理里面的复制，是生效的

本地相册的复制我测试是生效的，顶部栏窗口的复制确实没有生效，我排查一下

**Comment by Kuingsmile** [comment]
> ### 前置阅读 | Pre-reading
> * [x]  [文档/Doc](https://picgo.github.io/PicGo-Doc/)
> * [x]  [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
> * [x]  [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)
> 
> ### PicList的版本 | PicList Version
> 1.6.0
> 
> ### 系统信息 | System Information
> Mac(arm64)
> 
> ### 问题重现 | Bug reproduce
> 。。。
> 
> ### 相关日志 | Logs
> 没有报错

已解决，会在下个小版本中带出修复，感谢您的反馈~~

**Comment by mobilestack** [comment]
> > 还有，在本地相册中的复制文件名地址，也没有生效。但是在云端相册管理里面的复制，是生效的
> 
> 本地相册的复制我测试是生效的，顶部栏窗口的复制确实没有生效，我排查一下

我又试了下，的确是本地相册可以复制到了。不过这里复制出来的markdown格式，方框号中是空的。在云端管理里面复制的话，是带文件名的。

**Comment by Kuingsmile** [comment]
> > > 还有，在本地相册中的复制文件名地址，也没有生效。但是在云端相册管理里面的复制，是生效的
> > 
> > 本地相册的复制我测试是生效的，顶部栏窗口的复制确实没有生效，我排查一下
> 
> 我又试了下，的确是本地相册可以复制到了。不过这里复制出来的markdown格式，方框号中是空的。在云端管理里面复制的话，是带文件名的。

这里需要在方括号里添加文件名的话，可以用自定义链接格式，去设置界面里，自定义链接格式设置为`![$fileName]($url)`，然后复制格式选custom

默认的markdown格式为了和picgo兼容没有做改动
