### ISSUE TITLE
[Feature]: Dock栏图标隐藏的问题

### ISSUE THREAD

**Issue by mobilestack** [Kuingsmile/PicList#33]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.6.0

### 系统信息 | System Information

Mac(arm64)

### 功能请求 | Feature request

<img width="650" alt="image" src="https://user-images.githubusercontent.com/5794691/230586334-17ca0367-5a3a-4263-b68d-2334db02689c.png">

FAQ中说没有Dock图标，实际上是有的

<img width="219" alt="image" src="https://user-images.githubusercontent.com/5794691/230586464-14b26f76-430e-4471-bef9-761b77dc1d41.png">

建议保持隐藏掉

**Comment by Kuingsmile** [comment]
> ### 前置阅读 | Pre-reading
> * [x]  [文档/Doc](https://picgo.github.io/PicGo-Doc/)
> * [x]  [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
> * [x]  [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)
> 
> ### PicList的版本 | PicList Version
> 1.6.0
> 
> ### 系统信息 | System Information
> Mac(arm64)
> 
> ### 功能请求 | Feature request
> <img alt="image" width="650" src="https://user-images.githubusercontent.com/5794691/230586334-17ca0367-5a3a-4263-b68d-2334db02689c.png">
> 
> FAQ中说没有Dock图标，实际上是有的
> 
> <img alt="image" width="219" src="https://user-images.githubusercontent.com/5794691/230586464-14b26f76-430e-4471-bef9-761b77dc1d41.png">
> 
> 建议保持隐藏掉

这个版本新增的dock图标，只有顶部栏的问题是有时候会被盖掉，就导致没法打开主窗口了，也没法关闭软件，参考https://github.com/Molunerfinn/PicGo/issues/1049
这里暂时先保持了，不打算改回去

**Comment by mobilestack** [comment]
> > ### 前置阅读 | Pre-reading
> > 
> > * [x]   [文档/Doc](https://picgo.github.io/PicGo-Doc/)
> > * [x]   [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
> > * [x]   [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)
> > 
> > ### PicList的版本 | PicList Version
> > 1.6.0
> > ### 系统信息 | System Information
> > Mac(arm64)
> > ### 功能请求 | Feature request
> > <img alt="image" width="650" src="https://user-images.githubusercontent.com/5794691/230586334-17ca0367-5a3a-4263-b68d-2334db02689c.png">
> > FAQ中说没有Dock图标，实际上是有的
> > <img alt="image" width="219" src="https://user-images.githubusercontent.com/5794691/230586464-14b26f76-430e-4471-bef9-761b77dc1d41.png">
> > 建议保持隐藏掉
> 
> 这个版本新增的dock图标，只有顶部栏的问题是有时候会被盖掉，就导致没法打开主窗口了，也没法关闭软件，参考[Molunerfinn/PicGo#1049](https://github.com/Molunerfinn/PicGo/issues/1049) 这里暂时先保持了，不打算改回去

学习到了，刘海屏...真的是够够的

**Comment by mobilestack** [comment]
貌似可以加个设置项，如果能隐藏Dock的话，也是照顾到更大一部分的群体了

**Comment by Kuingsmile** [comment]
> 貌似可以加个设置项，如果能隐藏Dock的话，也是照顾到更大一部分的群体了

可以试试，因为这里是否显示dock图标是在打包参数里设置的，所以可能不是特别好修改

我先查查有木有其它的方式可以控制dock图标

**Comment by Kuingsmile** [comment]
> 貌似可以加个设置项，如果能隐藏Dock的话，也是照顾到更大一部分的群体了

[#0466fa78a42135cf76d0fd0b17b848796c6088bd](https://github.com/Kuingsmile/PicList/commit/0466fa78a42135cf76d0fd0b17b848796c6088bd)

@mobilestack  最新提交中新增了隐藏dock图标选项，可以手动控制是否在软件启动后隐藏dock，预计于下版本带出修改。
