### ISSUE TITLE
[Bug]: 粘贴到Obsidian后，文件名全部显示为image.png，而不是上传前修改的名字

### ISSUE THREAD

**Issue by mobilestack** [Kuingsmile/PicList#34]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.6.0

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

去看了下plugin那边的issue，好像没有人提这个问题，所以可能会不会是PicList在上传后的返回结果这里需要看一下

<img width="290" alt="image" src="https://user-images.githubusercontent.com/5794691/230591434-a735aff7-28c5-47b5-8339-986a0489d769.png">

全部显示为image.png，实际是改过名字的，云端也是改过名字的

### 相关日志 | Logs

无报错

**Comment by Kuingsmile** [comment]
这个是插件的问题哈，文件名是插件那边添加的

![image](https://user-images.githubusercontent.com/96409857/230591766-8b1b2b27-0601-443b-b093-a858ac6187c8.png)

**Comment by mobilestack** [comment]
感谢，刚刚去看了下插件那边的代码，果然是
