### ISSUE TITLE
[Feature]: 为什么电脑开机启动会自动打开piclist的github，启动项又找到相应的

### ISSUE THREAD

**Issue by lb8023lyy** [Kuingsmile/PicList#37]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.60

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

是哪里设置错了么，可以关掉么

**Comment by Kuingsmile** [comment]
针对1.6.0版本的更新推送哈，因为windows的1.6.0版本的自动更新有bug不能正常工作，所以选择了启动时打开最新版本的下载页面进行提示，更新1.6.1或以上版本就没了哈

之后的版本应该就可以自动更新了不会再弹出网页，这个属于特殊情况，抱歉带来困扰

**Comment by Kuingsmile** [comment]
我一会设置下只打开一次网页，之后即使重启也不会再打开网页

**Comment by Kuingsmile** [comment]
@lb8023lyy  已经修改了更新推送设置，现在您再启动应该不会启动网页了，但仍推荐升级到1.6.1以上版本

如果还有问题欢迎继续反馈哈
