### ISSUE TITLE
[Feature]: 希望可以提供Windows-arm64版本

### ISSUE THREAD

**Issue by Grosser-Kurfuerst** [Kuingsmile/PicList#42]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v1.7.0

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

目前在使用win on arm设备，虽然x64版本可以转译运行，但还是希望可以原生支持arm64，十分感谢

**Comment by Kuingsmile** [comment]
> ### 前置阅读 | Pre-reading
> 
> - [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
> - [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
> - [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)
> 
> ### PicList的版本 | PicList Version
> 
> v1.7.0
> 
> ### 系统信息 | System Information
> 
> Windows
> 
> ### 功能请求 | Feature request
> 
> 目前在使用win on arm设备，虽然x64版本可以转译运行，但还是希望可以原生支持arm64，十分感谢

我先打包一下试试看，可能会涉及到sharp包的问题，需要您一起测试下，方便的话可以加我微信pku_sq_ma，好进行安装包的测试沟通

**Comment by FEI352** [comment]
> > ### 前置阅读 | Pre-reading
> > 
> > * [x]  [文档/Doc](https://picgo.github.io/PicGo-Doc/)
> > * [x]  [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
> > * [x]  [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)
> > 
> > ### PicList的版本 | PicList Version
> > v1.7.0
> > ### 系统信息 | System Information
> > Windows
> > ### 功能请求 | Feature request
> > 目前在使用win on arm设备，虽然x64版本可以转译运行，但还是希望可以原生支持arm64，十分感谢
> 
> 我先打包一下试试看，可能会涉及到sharp包的问题，需要您一起测试下，方便的话可以加我微信pku_sq_ma，好进行安装包的测试沟通

虽然挺冒昧的，但是我想问下载那个版本比较好，和他一样用的WOA设备。

**Comment by Grosser-Kurfuerst** [comment]
> > > ### 前置阅读 | Pre-reading
> > > 
> > > * [x]   [文档/Doc](https://picgo.github.io/PicGo-Doc/)
> > > * [x]   [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
> > > * [x]   [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)
> > > 
> > > ### PicList的版本 | PicList Version
> > > v1.7.0
> > > ### 系统信息 | System Information
> > > Windows
> > > ### 功能请求 | Feature request
> > > 目前在使用win on arm设备，虽然x64版本可以转译运行，但还是希望可以原生支持arm64，十分感谢
> > 
> > 
> > 我先打包一下试试看，可能会涉及到sharp包的问题，需要您一起测试下，方便的话可以加我微信pku_sq_ma，好进行安装包的测试沟通
> 
> 虽然挺冒昧的，但是我想问下载那个版本比较好，和他一样用的WOA设备。

x64就行，目前稳定使用一年了，资源占用也很小
