### ISSUE TITLE
更新问题

### ISSUE THREAD

**Issue by xushier** [Kuingsmile/PicList#50]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.9.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

更新的时候，双击更新包安装，安装位置和之前一样，但安装结束后每次都是原来的安装位置所有文件都不见了。

重新再次安装才行。但是这样所有的配置就都没有了，要重新配置，上传记录也没了。。。

每次更新都要从头开始配置。。。。。

**Comment by Kuingsmile** [comment]
用自动更新 每次启动软件的时候会检测最新版本并提示自动更新的，我自己这边自动更新没出现过丢配置文件的问题

**Comment by xushier** [comment]
1.5版本没有自动更新吧？我好像是从1.5升级过来的，升级提示点一下就跳到github下载了

**Comment by Kuingsmile** [comment]
> 1.5版本没有自动更新吧？我好像是从1.5升级过来的，升级提示点一下就跳到github下载了

这个版本有点旧了， 1.6.1的时候才加的自动更新

**Comment by xushier** [comment]
嗯嗯，明白了。谢谢
