### ISSUE TITLE
[Bug]: 上传图片处理转换格式为webp查看不了

### ISSUE THREAD

**Issue by m430** [Kuingsmile/PicList#53]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.9.2

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

RT

**Comment by Kuingsmile** [comment]
指相册里查看不了还是在对应平台查看不了

**Comment by m430** [comment]
@Kuingsmile  传到Github仓库查看不了，PicList本地相册也查看不了

**Comment by Kuingsmile** [comment]
github查看是平台自己支持的问题
本地相册我这边可以
![image](https://github.com/Kuingsmile/PicList/assets/96409857/39ea7434-e9b6-4545-9d44-221b47b83932)

**Comment by m430** [comment]
本问题我找到原因。链接是可以正常查看
