### ISSUE TITLE
[Bug]: 开启删除云端删除，批量删除会失败，云端并没有被删除成功

### ISSUE THREAD

**Issue by m430** [Kuingsmile/PicList#54]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.9.2

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

RT

**Comment by Kuingsmile** [comment]
哪个图床平台，可以开控制台看下报错是什么

**Comment by m430** [comment]
Github。第一个会删除成功，后面的都删除失败：

![image](https://github.com/Kuingsmile/PicList/assets/4023173/01e04ae4-24ec-49f3-b0c9-1f4afeeddc73)

**Comment by Kuingsmile** [comment]
这个可以复现，后续进行修复

**Comment by Kuingsmile** [comment]
@m430  问题已定位，下个版本带出修复，感谢您的反馈

**Comment by Kuingsmile** [comment]
在最新提交 https://github.com/Kuingsmile/PicList/commit/86505c19e2d0bdf0490051f7d30d2a02ca54b1cb 中已修复，1.9.3版本带出

**Comment by m430** [comment]
@Kuingsmile Nice
