### ISSUE TITLE
[Bug]: 上传成功后，没有通知提示

### ISSUE THREAD

**Issue by m430** [Kuingsmile/PicList#55]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.9.2

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

RT

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/96409857/bccf89e0-1adc-445f-81d8-1a3c79f6f130)
未复现 另外mac上需要开启权限才有通知

**Comment by m430** [comment]
开启权限后，有通知了。关闭此问题
