### ISSUE TITLE
[Feature]: 增加支持预览文件的类型

### ISSUE THREAD

**Issue by kaesahao** [Kuingsmile/PicList#57]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.9.3

### 系统信息 | System Information

Mac

### 功能请求 | Feature request

你好，未来是否会考虑像kkFileView，增加doc、xls、ppt、pdf、epub等文件类型的预览支持呢

**Comment by Kuingsmile** [comment]
> ### 前置阅读 | Pre-reading
> * [x]  [文档/Doc](https://picgo.github.io/PicGo-Doc/)
> * [x]  [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
> * [x]  [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)
> 
> ### PicList的版本 | PicList Version
> 1.9.3
> 
> ### 系统信息 | System Information
> Mac
> 
> ### 功能请求 | Feature request
> 你好，未来是否会考虑像kkFileView，增加doc、xls、ppt、pdf、epub等文件类型的预览支持呢

可以考虑，我需要研究下怎么实现，如果可行的话应该会在2.0大版本更新的时候加入
感谢建议
