### ISSUE TITLE
[Bug]: 上传打开图片格式转换功能，但上传GIF动图也被转换成了静态图片。

### ISSUE THREAD

**Issue by zyighb** [Kuingsmile/PicList#60]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.94

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

上传打开图片格式转换功能，但上传GIF动图也被转换成了静态图片。
![image](https://github.com/Kuingsmile/PicList/assets/22572153/c49111b2-9144-42f3-9269-51186138cbe9)

**Comment by Kuingsmile** [comment]
> ### 前置阅读 | Pre-reading
> * [x]  [文档/Doc](https://picgo.github.io/PicGo-Doc/)
> * [x]  [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
> * [x]  [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)
> 
> ### PicList的版本 | PicList Version
> 1.94
> 
> ### 系统信息 | System Information
> Windows
> 
> ### 问题重现 | Bug reproduce
> 上传打开图片格式转换功能，但上传GIF动图也被转换成了静态图片。 ![image](https://user-images.githubusercontent.com/22572153/245656103-c49111b2-9144-42f3-9269-51186138cbe9.png)
> 
> ### 相关日志 | Logs
> _No response_

get 我优化下，转换时排除gif图片
