### ISSUE TITLE
[Bug]: 上传图片转换成webp格式后，在相册中不显示

### ISSUE THREAD

**Issue by xuconnery** [Kuingsmile/PicList#61]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.9.4

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

上传图片到GitHub，图片处理选择转换成webp格式，压缩质量选75。

图片上传成功后，在菜单栏点击图标、以及相册中，图片均不能正常显示

**Comment by xuconnery** [comment]
咦，又自动好了，难道是网络抽风。。。

**Comment by Kuingsmile** [comment]
> 咦，又自动好了，难道是网络抽风。。。

github用的时候最好挂个代理，国内经常抽风
