### ISSUE TITLE
视频上传自动生成缩略图并缓存在指定文件夹

### ISSUE THREAD

**Issue by yeyudoc** [Kuingsmile/PicList#63]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

latest

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

可以在视频上传自动生成缩略图并缓存在指定文件夹里吗，要不然云盘预览生成太慢

**Comment by Kuingsmile** [comment]
我看下好实现不
