### ISSUE TITLE
[Bug]: webdev上传图片时。相册显示图片失败，麻烦修复一下

### ISSUE THREAD

**Issue by Mr-LaoKang** [Kuingsmile/PicList#64]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.9.4

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

![image](https://github.com/Kuingsmile/PicList/assets/111170907/febfe0f7-8c64-43e5-b66e-84dc3826402a)

**Comment by Kuingsmile** [comment]
感谢反馈，会尝试优化，预计于未来1-2个小版本内解决
