### ISSUE TITLE
[Bug]: 布局问题

### ISSUE THREAD

**Issue by fu-jw** [Kuingsmile/PicList#68]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.9.6

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

1. 最下面一排,功能按键不显示
![Snipaste_2023-07-01_10-40-11](https://github.com/Kuingsmile/PicList/assets/40262591/9c4afe26-9c14-4c40-8a68-24293d9f473b)
2. 页面缩放时,图片与下面信息不跟随,会显得排版杂乱(不影响使用)
![Snipaste_2023-07-01_10-50-15](https://github.com/Kuingsmile/PicList/assets/40262591/1d00d2b6-1842-4b5e-816f-71d554b23eed)

**Comment by Kuingsmile** [comment]
> ### 前置阅读 | Pre-reading
> * [x]  [文档/Doc](https://picgo.github.io/PicGo-Doc/)
> * [x]  [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
> * [x]  [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)
> 
> ### PicList的版本 | PicList Version
> 1.9.6
> 
> ### 系统信息 | System Information
> Windows
> 
> ### 问题重现 | Bug reproduce
> 1. 最下面一排,功能按键不显示
>    ![Snipaste_2023-07-01_10-40-11](https://user-images.githubusercontent.com/40262591/250222261-9c4afe26-9c14-4c40-8a68-24293d9f473b.png)
> 2. 页面缩放时,图片与下面信息不跟随,会显得排版杂乱(不影响使用)
>    ![Snipaste_2023-07-01_10-50-15](https://user-images.githubusercontent.com/40262591/250222764-1d00d2b6-1842-4b5e-816f-71d554b23eed.png)
> 
> ### 相关日志 | Logs
> _No response_

get 最近会优化下UI

**Comment by Kuingsmile** [comment]
https://github.com/Kuingsmile/PicList/commit/b6f5d9fd0944050623a6331f691fe75e8c245ea7
