### ISSUE TITLE
[Feature]: 希望可以增加自定义短链服务

### ISSUE THREAD

**Issue by Mrered** [Kuingsmile/PicList#69]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.9.6

### 系统信息 | System Information

All

### 功能请求 | Feature request

希望增加对第三方短链服务的支持

[YOURLS](https://yourls.org/) 是一个从 2009 年创立的开源**自建短链接**系统。

只需要 `POST` 请求 `https:$domain/yourls-api.php?signature=$signature&action=shorturl&url=$url`

|项目|值|
|:-:|:-:|
|`$domain`|自建 YOURLS 的域名|
|`$signature`|在 `https:$domain/admin/tools.php` 上可以找到|
|`$url`|目标URL|

返回 XML 示例：

> This XML file does not appear to have any style information associated with it. The document tree is shown below.

```xml
<root>
  <status>success</status>
  <code/>
  <message>github.com has been saved</message>
  <errorCode/>
  <statusCode>200</statusCode>
  <url>
    <keyword>ynuwq</keyword>
    <url>github.com</url>
    <title>github.com</title>
    <date>2023-07-07 12:32:12</date>
    <ip>***.***.***.***</ip>
  </url>
  <title>github.com</title>
  <shorturl>https://$domain/ynuwq</shorturl>
</root>
```

其中 IP 为发起请求者的 IP 。

**Comment by Mrered** [comment]
这是官方帮助文档：

You need to send parameters to `http://your-own-domain-here.com/yourls-api.php` either via `GET` or `POST` (remember to **URL-encode parameters** if via GET). These parameters are:

*   A valid `username` / `password` pair, or your `signature` (see [Passwordless API requests](https://yourls.org/passwordlessapi))
*   The requested `action`: "shorturl" (get short URL for a link), "expand" (get long URL of a shorturl), "url-stats" (get stats about one short URL), "stats" (get stats about your links) or "db-stats" (get global link and click count)
*   With action = "shorturl" :
    *   the `url` to shorten
    *   optional `keyword` and `title` for custom short URLs
    *   output `format`: either "jsonp", "json", "xml" or "simple"
*   With action = "expand" :
    *   the `shorturl` to expand (can be either 'abc' or 'http://site/abc')
    *   output `format`: either "jsonp", "json", "xml" or "simple"
*   With action = "url-stats" :
    *   the `shorturl` for which to get stats (can be either 'abc' or 'http://site/abc')
    *   output `format`: either "jsonp", "json" or "xml"
*   With action = "stats" :
    *   the `filter`: either "top", "bottom" , "rand" or "last"
    *   the `limit` (maximum number of links to return)
    *   output `format`: either "jsonp", "json" or "xml"
*   With action = "db-stats" :
    *   output `format`: either "jsonp", "json" or "xml"
*   With action = "version" :
    *   output `format`: either "jsonp", "json", "xml" or "simple"

### Sample requests

Example of a GET request with Javascript (using jQuery) to shorten a URL

```javascript
var api\_url  = 'http://sho.rt/yourls-api.php';
var response = $.get( api\_url, {
    username: "your\_username",
    password: "your\_password",
    action:   "shorturl",
    format:   "json",
    url:      "http://ozh.org/"
    },
    // callback function that will deal with the server response
    function( data) {
        // now do something with the data, for instance show new short URL:
        alert(data.shorturl);
    }
);
```

Example of a POST request with PHP to expand a short URL

```php
<?php
$username = 'your\_username';
$password = 'your\_password';
$api\_url =  'http://sho.rt/yourls-api.php';

// Init the CURL session
$ch = curl\_init();
curl\_setopt($ch, CURLOPT\_URL, $api\_url);
curl\_setopt($ch, CURLOPT\_HEADER, 0);            // No header in the result
curl\_setopt($ch, CURLOPT\_RETURNTRANSFER, true); // Return, do not echo result
curl\_setopt($ch, CURLOPT\_POST, 1);              // This is a POST request
curl\_setopt($ch, CURLOPT\_POSTFIELDS, array(     // Data to POST
        'shorturl' =\> 'ozh',
        'format'   =\> 'json',
        'action'   =\> 'expand',
        'username' =\> $username,
        'password' =\> $password
    ));

// Fetch and return content
$data = curl\_exec($ch);
curl\_close($ch);

// Do something with the result. Here, we echo the long URL
$data = json\_decode( $data );
echo $data-\>longurl;
```

### Sample returns

Sample return in JSON format for the `shorturl` action

```json
{
  "url": {
    "keyword": "ozh",
    "url": "http:\\/\\/ozh.org",
    "title": "Ozh RICHARD \\u00ab ozh.org",
    "date": "2014-10-24 16:01:39",
    "ip": "127.0.0.1"
  },
  "status": "success",
  "message": "http:\\/\\/ozh.org added to database",
  "title": "Ozh RICHARD \\u00ab ozh.org",
  "shorturl": "http:\\/\\/sho.rt\\/1f",
  "statusCode": 200
}
```

Sample return in XML format for the `expand` action

```xml
<result\>
    <keyword\>ozh</keyword\>
    <shorturl\>http://sho.rt/ozh</shorturl\>
    <longurl\>http://ozh.org/</longurl\>
    <message\>success</message\>
    <statusCode\>200</statusCode\>
</result\>
```

**Comment by Mrered** [comment]
更简单的用法：

```url
https://$domain/yourls-api.php?signature=$signature&action=shorturl&format=simple&url=$url
```

使用了 `format=simple` ，会直接返回一个短链。

**Comment by Kuingsmile** [comment]
感谢建议 会尝试进行添加

**Comment by Kuingsmile** [comment]
已在1.9.7版本中加入，欢迎测试反馈
