### ISSUE TITLE
可以增加多吉云的远程管理支持吗

### ISSUE THREAD

**Issue by btrencai** [Kuingsmile/PicList#73]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.9.7

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

可以增加多吉云的远程管理支持吗

**Comment by Kuingsmile** [comment]
@btrencai 试下用S3平台，我看了下多吉云的文档，他是兼容S3 API的

**Comment by btrencai** [comment]
对的，已经尝试了，但是没有效果

**Comment by Kuingsmile** [comment]
> 对的，已经尝试了，但是没有效果

好的 那我去具体看看~

**Comment by btrencai** [comment]
难道是我填的有问题？
https://djy.btrencai.top/02e404622b33a0c3e921873a989f39ed.png

**Comment by btrencai** [comment]
难道是我填的有问题？
https://img01.anheyu.com/useruploads/122/2023/07/13/64af8a7338ea7.png

**Comment by Kuingsmile** [comment]
> 难道是我填的有问题？ https://img01.anheyu.com/useruploads/122/2023/07/13/64af8a7338ea7.png

不清楚 我注册个账号试试

**Comment by btrencai** [comment]
![3f2e212852c8083520e3f3afb35f29f.png](https://img01.anheyu.com/useruploads/122/2023/07/13/64af8a7338ea7.png)

**Comment by btrencai** [comment]
麻烦啦

**Comment by Kuingsmile** [comment]
> ![3f2e212852c8083520e3f3afb35f29f.png](https://camo.githubusercontent.com/85e865aab3e56fd6fe7988397d3fe7e9becaf773a84fbc31c5ed2b161bb1857c/68747470733a2f2f696d6730312e616e686579752e636f6d2f7573657275706c6f6164732f3132322f323032332f30372f31332f363461663861373333386561372e706e67)

https://docs.dogecloud.com/oss/api-tmp-token
多吉云这个比较奇葩，需要先用控制台里的accessKey和secretKey获取S3的临时密钥，然后才能用S3 SDK，而且拿到的临时密钥还有有效期，和常规的永久密钥用法不一样
需要特殊处理，我后面适配下看看

**Comment by btrencai** [comment]
好滴

**Comment by Kuingsmile** [comment]
进度比预期慢一些，预计和2.0.0版本同步带出

**Comment by btrencai** [comment]
没事滴

**Comment by Kuingsmile** [comment]
@btrencai 最新提交已在S3的基础上添加了对dogeCloud模式的支持
