### ISSUE TITLE
[Bug]: “开启上传提示”为“关”的情况下依然弹出通知

### ISSUE THREAD

**Issue by Evilmass** [Kuingsmile/PicList#74]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.9.7

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

![设置不起作用](https://github.com/Kuingsmile/PicList/assets/21218296/a8a5f956-90e8-4a6d-8b32-390c3baf010e)

![上传依旧通知](https://github.com/Kuingsmile/PicList/assets/21218296/35a0e2fe-f785-44dc-9069-d7c853c0c5ef)

### 相关日志 | Logs

from piclist.log
```bash
2023-07-18 00:45:10 [PicList INFO] Before transform 
2023-07-18 00:45:10 [PicList INFO] Transforming... Current transformer is [path] 
2023-07-18 00:45:10 [PicList INFO] Before upload 
2023-07-18 00:45:10 [PicList INFO] beforeUploadPlugins: renameFn running 
2023-07-18 00:45:10 [PicList INFO] Uploading... Current uploader is [smms] 
2023-07-18 00:45:13 [PicList SUCCESS] 
https://s2.loli.net/2023/07/18/<image>.png 
```

**Comment by Kuingsmile** [comment]
好的 我看下

**Comment by Kuingsmile** [comment]
@Evilmass 该设置项为上传进度通知开关，而非上传结果通知开关，已在最新修改中新增了控制开关上传结果通知的设置项，将于后续的1.9.8版本发布

**Comment by Evilmass** [comment]
OK

**Comment by Evilmass** [comment]
1.9.8 还是有点问题

排查了下，应该是第二个选项的问题
打开 mini 窗口会隐藏主窗口 √
重新打开主窗口却不会隐藏 mini 窗口 ×

![动画](https://github.com/Kuingsmile/PicList/assets/21218296/eda01dbb-43d2-4e2b-8dad-c463aefb89aa)

**Comment by Kuingsmile** [comment]
> 1.9.8 还是有点问题
> 
> 排查了下，应该是第二个选项的问题 打开 mini 窗口会隐藏主窗口 √ 重新打开主窗口却不会隐藏 mini 窗口 ×
> 
> ![动画](https://user-images.githubusercontent.com/21218296/254859690-eda01dbb-43d2-4e2b-8dad-c463aefb89aa.gif)


看着没啥问题？ 你最后一个操作是关闭了“打开主窗口时关闭mini窗口”，这时候从mini窗口启动主窗口，mini窗口不关闭是符合预期的呀。另外主窗口右上角的缩小按钮，是不受到“打开mini窗口时关闭主窗口”这个选项影响的，因为这个按钮就是为了快速缩小化而设置的。

**Comment by Evilmass** [comment]
> > 1.9.8 还是有点问题
> > 排查了下，应该是第二个选项的问题 打开 mini 窗口会隐藏主窗口 √ 重新打开主窗口却不会隐藏 mini 窗口 ×
> > ![动画](https://user-images.githubusercontent.com/21218296/254859690-eda01dbb-43d2-4e2b-8dad-c463aefb89aa.gif)
> >       
> >         [
> >           
> >         
> >             ![动画](https://user-images.githubusercontent.com/21218296/254859690-eda01dbb-43d2-4e2b-8dad-c463aefb89aa.gif)
> >           ](https://user-images.githubusercontent.com/21218296/254859690-eda01dbb-43d2-4e2b-8dad-c463aefb89aa.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/21218296/254859690-eda01dbb-43d2-4e2b-8dad-c463aefb89aa.gif)
> 
> 看着没啥问题？ 你最后一个操作是关闭了“打开主窗口时关闭mini窗口”，这时候从mini窗口启动主窗口，mini窗口不关闭是符合预期的呀。另外主窗口右上角的缩小按钮，是不受到“打开mini窗口时关闭主窗口”这个选项影响的，因为这个按钮就是为了快速缩小化而设置的。

原来是这个意思，理解了
