### ISSUE TITLE
[Bug]: 上传动图无法播放的问题

### ISSUE THREAD

**Issue by Evilmass** [Kuingsmile/PicList#76]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.9.8

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

这是一张示例动图：
![login](https://github.com/Kuingsmile/PicList/assets/21218296/a48828dd-b43e-44e1-817f-4ceb510deca9)

如果手动上传到 SMMS 图床，得到的图片链接是能正常播放的。
!\[login.gif](https://s2.loli.net/2023/07/23/jMiRLtrVAqW4SDY.gif)

但通过 PicList 上传后的到的链接如下且不能正常播放
![\](https://s2.loli.net/2023/07/23/rcNGxiasFB8m3hg.gif)

复现过程：
![2动画](https://github.com/Kuingsmile/PicList/assets/21218296/591d4966-2b37-4886-8594-a1d0d937ac3c)

**Comment by Kuingsmile** [comment]
get 应该是和图片处理流程相关，我测试下
