### ISSUE TITLE
[Bug]: 相册页下拉筛选框后，最后一行图片的操作按钮显示不完整

### ISSUE THREAD

**Issue by Evilmass** [Kuingsmile/PicList#77]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.9.8

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

右侧滚动条不显示，也无法向下滚动

![snipaste_20230724_234814](https://github.com/Kuingsmile/PicList/assets/21218296/1c429d65-d68e-4c3c-a6a5-ff42bf380b11)

**Comment by Kuingsmile** [comment]
get 后续再改下UI
