### ISSUE TITLE
[Feature]:  存储路径增加占位符支持

### ISSUE THREAD

**Issue by andsky** [Kuingsmile/PicList#79]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.9.8

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

"path": "", // 存储路径 希望 增加占位符支持，  上传可以按 2002/08 年月分目录

**Comment by Kuingsmile** [comment]
阿里云，腾讯云等对象存储的话，可以用高级重命名修改文件名带路径，高级重命名支持占位符

**Comment by andsky** [comment]
webdav 用高级重命名会报上传错误，但实现图版已经上传成功了

**Comment by Kuingsmile** [comment]
> webdav 用高级重命名会报上传错误，但实现图版已经上传成功了

感谢反馈 经过测试确实会有这个问题，目前已经定位问题并进行了修复 @andsky

**Comment by Kuingsmile** [comment]
https://github.com/Kuingsmile/PicList/commit/3e76ba18655ddc3038de2cdc802fa104784e22b9 中修复了高级重命名时报错的问题，同时修复了设置webdav时sslenabled会报必须填写的问题
