### ISSUE TITLE
[Feature]: 图片处理方式：只填入宽或者高，另一边自适应

### ISSUE THREAD

**Issue by eallion** [Kuingsmile/PicList#81]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v1.9.8

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

图片上传前的处理方式：
根据 EXIF 信息，或其他方式，先确定图片是横版还是竖版，然后只填入宽或者高，另一边自适应。
比如：
1920x1080.jpg
1440x1200.jpg
300x400.jpg
当限制宽度为 800 时，这些图片的高度就自动计算，不足设定值时，保持原来大小，结果：
1422x800.jpg
960x800.jpg
300x400.jpg
限制高度同理。

（非常优秀的项目，已赞 🎉）

**Comment by Kuingsmile** [comment]
目前piclist是支持按百分比缩放，我的理解是新增类似于百分比缩放保持高宽比，但是可以指定高宽中的其中一项? @eallion 
如果是我理解的这样子可以实现，我测试下

**Comment by eallion** [comment]
嗯，差不多是这样的，指定一项，另一项等比例缩放。

**Comment by Kuingsmile** [comment]
@eallion added in https://github.com/Kuingsmile/PicList/commit/3cc118e8fa4a825c201251d2956576a49439d50c

**Comment by eallion** [comment]
太有效率了！赞！

**Comment by eallion** [comment]
@Kuingsmile 我终于记起来原型了，是腾讯云的图片处理。（打扰了）

![QQ截图20230809170946](https://github.com/Kuingsmile/PicList/assets/1698841/b6bb0485-8958-4b73-8b85-2baa59aed4c9)
