### ISSUE TITLE
[Bug]: 为什么每次更新都是卸载而不是覆盖呢？

### ISSUE THREAD

**Issue by xushier** [Kuingsmile/PicList#83]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.9.6

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

每次检查到新版本，先手动到github下载，下载完毕点击安装，安装时程序会自己检测到之前老版本的安装目录。然后正常情况下应该直接安装就会覆盖掉之前的目录，但实际情况是按照安装步骤走，走完之后系统会提示安装了新软件，但实际上安装目录被清空了，软件并不存在，看起来像是卸载的效果。必须再手动安装一遍，但是之前的配置数据也就不复存在了。

### 相关日志 | Logs

数据被清空，没有日志了

**Comment by Kuingsmile** [comment]
请使用自动更新功能，另外我测试了下重复安装，并没有丢失配置数据的情况，安装的时候请选择anyone who use this computer

**Comment by Kuingsmile** [comment]
如果是手动下载安装包，window推荐每次都下载最后一个，保持一致

![image](https://github.com/Kuingsmile/PicList/assets/96409857/84e054fa-e214-40d5-b363-2ecd064cda09)

**Comment by xushier** [comment]
> 请使用自动更新功能，另外我测试了下重复安装，并没有丢失配置数据的情况，安装的时候请选择anyone who use this computer

每次安装的都是 x64 版本，接连好几个版本都是会这样。。自动更新没有找到，更新助手是打开的，手动点击检查更新之后都是跳转下载，也不是自动。

**Comment by Kuingsmile** [comment]
> > 请使用自动更新功能，另外我测试了下重复安装，并没有丢失配置数据的情况，安装的时候请选择anyone who use this computer
> 
> 每次安装的都是 x64 版本，接连好几个版本都是会这样。。自动更新没有找到，更新助手是打开的，手动点击检查更新之后都是跳转下载，也不是自动。

自动更新是默认开启的，工作机制是在每次启动或者重启软件的时候检查一次新版本。 通过设置界面里的检查更新是手动下载安装包，后面我这里会改一下逻辑，改成手动检测的这个界面确定后也启动自动更新的流程。  目前版本的话可以先在看到新版本后重启下软件，触发一下自动更新检测。

**Comment by xushier** [comment]
好的，谢谢
