### ISSUE TITLE
[Feature]: 微信群二维码过期了，进不了群

### ISSUE THREAD

**Issue by xs-alpha** [Kuingsmile/PicList#84]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

master

### 系统信息 | System Information

Linux

### 功能请求 | Feature request

[Bug]: 微信群二维码过期了，进不了群

**Comment by Kuingsmile** [comment]
@xs-alpha 最近好多打广告的入群，我把进群给关了，你可以添加我的微信`pku_sq_ma`，我拉你进群
