### ISSUE TITLE
[Feature]: 七牛云增加自定义域名

### ISSUE THREAD

**Issue by shuojie819** [Kuingsmile/PicList#85]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.9.9

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

大佬，可以为七牛云增加一个自定义域名吗。
![image](https://github.com/Kuingsmile/PicList/assets/72399630/f7be0bcc-20ed-4f6d-b54a-909b3a964199)

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/96409857/baf5ac8a-4940-48cf-aec6-89bbfa3cbafc)
这个就是自定义域名

**Comment by shuojie819** [comment]
> ![image](https://user-images.githubusercontent.com/96409857/262534919-baf5ac8a-4940-48cf-aec6-89bbfa3cbafc.png) 这个就是自定义域名

额……好吧
![0926BC99](https://github.com/Kuingsmile/PicList/assets/72399630/f6d7a4e4-4639-42c1-a3ff-3e2b8a91270e)
我的问题
