### ISSUE TITLE
[Feature]: 存储路径接口开放

### ISSUE THREAD

**Issue by cath-gh** [Kuingsmile/PicList#93]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.5.1

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

希望把github配置中存储路径这个接口开放出去，这样在Obsidian不同仓库可以配置不同的存储路径

**Comment by Kuingsmile** [comment]
> ### 前置阅读 | Pre-reading
> * [x]  [文档/Doc](https://picgo.github.io/PicGo-Doc/)
> * [x]  [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
> * [x]  [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)
> 
> ### PicList的版本 | PicList Version
> 2.5.1
> 
> ### 系统信息 | System Information
> Windows
> 
> ### 功能请求 | Feature request
> 希望把github配置中存储路径这个接口开放出去，这样在Obsidian不同仓库可以配置不同的存储路径

可以设置多份配置来对应不同的Obsidian仓库，如果是不修改配置实现的话，需要同步修改piclist的上传接口和Obsidian的上传插件对应部分的代码，而且可能更好的方案是不止开放存储路径，而是开放整个设置，在发送请求的时候带着配置一起发送，这样适应性更强

**Comment by cath-gh** [comment]
确实也需要Obsidian插件修改代码，现在只能指定server和端口，从源头就区分不开。或许可以考虑在piclist的图床配置里面加上server设置，缺省使用全局server，有自定义的就用配置的。这样就可以在每个不同仓库设置不同的server了。

**Comment by Kuingsmile** [comment]
> 确实也需要Obsidian插件修改代码，现在只能指定server和端口，从源头就区分不开。或许可以考虑在piclist的图床配置里面加上server设置，缺省使用全局server，有自定义的就用配置的。这样就可以在每个不同仓库设置不同的server了。

这个想法可以 我考虑下怎么实现最好

**Comment by Kuingsmile** [comment]
> 确实也需要Obsidian插件修改代码，现在只能指定server和端口，从源头就区分不开。或许可以考虑在piclist的图床配置里面加上server设置，缺省使用全局server，有自定义的就用配置的。这样就可以在每个不同仓库设置不同的server了。

@cath-gh 

已实现，通过在接口添加URL查询参数的方式，例如`http://127.0.0.1:36677/upload?picbed=upyun&configName=configA`对应上传至又拍云图床的configA配置中，这样在obsidian不同仓库里只要填入对应的上传api地址即可上传至不同的图床

不带url参数的话接口行为和之前一致，上传至当前piclist的默认图床

同时在图床配置界面可以快捷复制对应的特定上传接口地址，防止出现不确定两个参数的值怎么填的问题
![image](https://github.com/Kuingsmile/PicList/assets/96409857/b38214bd-9bed-4e69-8e61-1b3324bed260)
![image](https://github.com/Kuingsmile/PicList/assets/96409857/42f0658e-4c2f-4c72-90b9-8c71453086e6)

**Comment by Kuingsmile** [comment]
明天再测试下没啥bug的话会发布2.5.3版本将此改动进行release
