### ISSUE TITLE
[Bug]: 文档里说支持多吉云 云存储管理，但是管理列表没有多吉云，只能看相册

### ISSUE THREAD

**Issue by hongyuyi** [Kuingsmile/PicList#97]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.6.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

看了文档里相册云删除和云存储管理都打上勾了，但是管理列表没有多吉云，多吉云需要下载插件，只能查看相册。

**Comment by Kuingsmile** [comment]
> ### 前置阅读 | Pre-reading
> * [x]  [文档/Doc](https://picgo.github.io/PicGo-Doc/)
> * [x]  [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
> * [x]  [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)
> 
> ### PicList的版本 | PicList Version
> 2.6.1
> 
> ### 系统信息 | System Information
> Windows
> 
> ### 问题重现 | Bug reproduce
> 看了文档里相册云删除和云存储管理都打上勾了，但是管理列表没有多吉云，多吉云需要下载插件，只能查看相册。
> 
> ### 相关日志 | Logs
> _No response_

![image](https://github.com/Kuingsmile/PicList/assets/96409857/bf7f6a38-39ef-4b30-a2d8-129abaada849)

**Comment by Kuingsmile** [comment]
多吉云支持S3协议，通过S3使用，然后打开上面的选项就可以
