### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by wukong999** [Kuingsmile/PicList#98]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.5.3

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

可不可用插件调用多个图床上传图片那？现在用两个笔记，一个图床容易混

**Comment by Kuingsmile** [comment]
@wukong999  Obsidian?  参考https://github.com/Kuingsmile/PicList/issues/93
![image](https://github.com/Kuingsmile/PicList/assets/96409857/64ba08f2-3136-48f9-93c2-f8476a378463)
