### ISSUE TITLE
[Feature]: 希望能加个百度云BOS存储

### ISSUE THREAD

**Issue by hongyuyi** [Kuingsmile/PicList#99]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.6.1

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

希望能加个百度云BOS存储

**Comment by Kuingsmile** [comment]
https://cloud.baidu.com/doc/BOS/s/Fjwvyq9xo  

@hongyuyi  我看了下是兼容S3的，试下s3插件可以用么，不行的话我后面加进来哈，要节后了，十一我要回家结婚 😆 
https://github.com/wayjam/picgo-plugin-s3

**Comment by hongyuyi** [comment]
恭喜兄弟哈，提前祝你新婚快乐。
S3插件我试了，是能连接上，就是图片无法上传到百度云的存储桶里，提示成功，文件夹也创建了，就是没有文件。权限什么都给了，还是有问题。

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/PicList/assets/96409857/5306ae81-f8ba-4da4-8669-f46997c8f44e)
![image](https://github.com/Kuingsmile/PicList/assets/96409857/ed6e82e3-7882-4d6e-8b39-70af12795d4f)
![image](https://github.com/Kuingsmile/PicList/assets/96409857/b62246ef-a852-421a-8164-30c144fb1a32)
我试了一下，可以上传成功呀~ 存储桶里也有文件

**Comment by hongyuyi** [comment]
是的，我的问题=-=，我的路径没有填{}，直接写名称了哈哈，加上确实可以了。
另外大大，我根据一位老哥的代码，简单修改了下，已经能用百度云BOS的插件配置和上传了。
https://github.com/hongyuyi/picgo-plugin-baiduBos-uploader/
